// @author bdth 2074055628@qq.com
// 文件用途 英雄联盟增强的中英文案表，启动时合并进主语言表
using System.Collections.Generic;

namespace PaviseApp
{
    internal static class LolLang
    {
        public static readonly Dictionary<string, string[]> Table = new Dictionary<string, string[]>
        {
            { "lol.act.waitclient", new[]{ "等待英雄联盟客户端", "Waiting for the League client" } },
            { "lol.act.waitinstall", new[]{ "等待英雄联盟安装目录", "Waiting for the League install folder" } },
            { "lol.act.disabled", new[]{ "英雄联盟增强已停用", "League enhancement is off" } },
            { "lol.act.cleaned", new[]{ "已净化 {0} 个附加进程", "Cleaned {0} add-on processes" } },
            { "lol.act.cleanidle", new[]{ "运行环境已净化", "Runtime already clean" } },
            { "lol.act.recovering", new[]{ "净化完成 正在用 WeGame 恢复登录链", "Cleanup done; restoring the login chain through WeGame" } },
            { "lol.act.headless", new[]{ "对局真无头已启用", "Headless match mode is on" } },
            { "lol.act.restored", new[]{ "英雄联盟大厅界面已恢复", "League lobby UI restored" } },
            { "lol.act.cleanupcircuit", new[]{ "附加进程反复重生 本局已暂停自动净化", "Add-on processes keep respawning; automatic cleanup paused for this match" } },
            { "lol.act.uxcircuit", new[]{ "大厅进程反复重启 本局已停用无头模式", "The lobby process keeps restarting; headless mode disabled for this match" } },
            { "lol.act.wegamestarted", new[]{ "WeGame 已启动", "WeGame started" } },
            { "lol.act.wegamestarting", new[]{ "正在等待 WeGame 就绪", "Waiting for WeGame to get ready" } },
            { "lol.act.wegamerunning", new[]{ "WeGame 已在运行 无需重复启动", "WeGame is already running" } },
            { "lol.err.wegamenostart", new[]{ "WeGame 未能在预期时间内启动", "WeGame did not start in time" } },
            { "lol.btn.wegamerunning", new[]{ "WeGame 运行中", "WeGame running" } },
            { "lol.err.noinstall", new[]{ "未找到英雄联盟安装目录", "League install folder not found" } },
            { "lol.err.notready", new[]{ "英雄联盟登录会话尚未就绪", "The League login session is not ready yet" } },
            { "lol.err.nosession", new[]{ "无法取得本机英雄联盟恢复会话", "Could not obtain the local League recovery session" } },
            { "lol.err.sessionlost", new[]{ "净化后英雄联盟登录会话失去响应", "The League login session stopped responding after cleanup" } },
            { "lol.err.killux", new[]{ "英雄联盟大厅界面收起失败", "Could not hide the League lobby UI" } },
            { "lol.err.gameidentity", new[]{ "无法确认本局游戏进程身份 已取消无头操作", "Could not verify the game process for this match; headless action cancelled" } },
            { "lol.err.lease", new[]{ "无法安全写入本局恢复租约 已取消无头操作", "Could not safely write the recovery lease for this match; headless action cancelled" } },
            { "lol.err.watchdog", new[]{ "独立恢复器未确认进入守护 已取消无头操作", "The standalone recovery guard did not confirm; headless action cancelled" } },
            { "lol.err.restore", new[]{ "英雄联盟大厅界面恢复失败", "Could not restore the League lobby UI" } },
            { "lol.err.restorepending", new[]{ "英雄联盟大厅界面恢复失败 独立恢复器将继续接管", "Could not restore the League lobby UI; the standalone recovery guard keeps trying" } },
            { "lol.err.leaseclear", new[]{ "英雄联盟大厅已显示 恢复租约清理失败 将继续重试", "The lobby is visible but the recovery lease could not be cleared; retrying" } },
            { "lol.err.uxcircuitrestore", new[]{ "反复重启保护已触发 大厅界面显示失败", "Restart-loop protection triggered; the lobby UI could not be shown" } },
            { "lol.err.cycle", new[]{ "英雄联盟运行时监控发生异常", "The League runtime monitor hit an error" } },
            { "lol.err.nowegame", new[]{ "未找到 WeGame", "WeGame not found" } },
            { "lol.err.wegamestart", new[]{ "WeGame 启动失败", "WeGame failed to start" } },
            { "lol.scan.cancel", new[]{ "取消扫描", "Cancel scan" } },
            { "lol.state.columnoff", new[]{ "增强已停用 操作已锁定", "Enhancement off; actions locked" } },

            { "col.state.off", new[]{ "增强已停用", "Enhancement off" } },
            { "col.state.scanning", new[]{ "正在扫描安装目录", "Scanning for the install folder" } },
            { "col.state.headless", new[]{ "对局无头运行中", "Match running headless" } },
            { "col.state.linked", new[]{ "链路已接管", "Link taken over" } },
            { "col.state.wait", new[]{ "等待客户端", "Waiting for the client" } },
            { "col.cell.install", new[]{ "安装", "Install" } },
            { "col.cell.lcu", new[]{ "LCU", "LCU" } },
            { "col.cell.phase", new[]{ "阶段", "Phase" } },
            { "col.cell.ux", new[]{ "界面", "Lobby UI" } },
            { "col.install.found", new[]{ "已定位", "Located" } },
            { "col.install.none", new[]{ "未发现", "Not found" } },
            { "col.install.wait", new[]{ "等待自动扫描", "Waiting for the scan" } },
            { "col.lcu.on", new[]{ "已连接", "Connected" } },
            { "col.lcu.off", new[]{ "未连接", "Not connected" } },
            { "col.client.off", new[]{ "客户端未运行", "Client not running" } },
            { "col.ux.closed", new[]{ "已关闭", "Hidden" } },
            { "col.ux.visible", new[]{ "大厅可见", "Visible" } },
            { "col.proc.none", new[]{ "未运行", "Not running" } },
            { "col.phase.ingame", new[]{ "对局中", "In match" } },
            { "col.phase.champselect", new[]{ "英雄选择", "Champion select" } },
            { "col.phase.matchmaking", new[]{ "匹配中", "Matchmaking" } },
            { "col.phase.readycheck", new[]{ "等待接受", "Ready check" } },
            { "col.phase.stats", new[]{ "结算中", "Post-game" } },
            { "col.phase.lobby", new[]{ "组队大厅", "Party lobby" } },
            { "col.phase.idle", new[]{ "大厅待命", "Idle in lobby" } },
            { "col.cleanup", new[]{ "借壳启动", "Shell launch" } },
            { "col.cleanup.tip", new[]{ "允许正常登录与启动 LCU 确认大厅可用后 精确退出 WeGame Cross 与腾讯附加进程 不注入 不改内存 不碰游戏核心文件", "Log in and launch normally; once the LCU confirms the lobby is up, WeGame, Cross and Tencent add-on processes are exited precisely. No injection, no memory edits, no game files touched." } },
            { "col.headless", new[]{ "对局真无头", "Headless match" } },
            { "col.headless.tip", new[]{ "进入对局后用客户端原生接口关闭大厅界面 游戏结束由守护链自动拉起并回显", "Once a match starts, the lobby UI is closed through the client's own API; when the match ends, the guard chain brings it back automatically." } },
            { "col.btn.launch", new[]{ "脱壳启动", "Launch without shell" } },
            { "col.btn.clean", new[]{ "立即净化", "Clean now" } },
            { "col.btn.restore", new[]{ "恢复界面", "Restore UI" } },
            { "col.btn.delete", new[]{ "删除附加层", "Delete add-ons" } },
            { "col.btn.cancel", new[]{ "取消扫描", "Cancel scan" } },
            { "col.busy.launch", new[]{ "正在启动 WeGame", "Starting WeGame" } },
            { "col.busy.clean", new[]{ "正在执行精准净化", "Running precise cleanup" } },
            { "col.busy.restore", new[]{ "正在恢复客户端界面", "Restoring the client UI" } },
            { "col.addon.tip", new[]{ "直接删除 AI 教练 iCreate 录制等附加层 客户端更新会重新下载 无需保留副本", "Deletes add-on layers such as AI Coach and iCreate recording outright. The client re-downloads them on update, so no copy is kept." } },
            { "col.addon.locked", new[]{ "客户端运行中 文件操作已锁定", "Client running; file actions locked" } },
            { "col.addon.busy", new[]{ "文件操作进行中", "File action in progress" } },
            { "col.addon.blocked", new[]{ "检测到占用进程 请完全退出客户端", "Blocking process detected; exit the client fully" } },
            { "col.addon.blockedby", new[]{ "{0} 仍在运行 请完全退出", "{0} still running; exit it fully" } },
            { "col.addon.helpers", new[]{ "WeGame 残留 {0} 删除时会先结束", "WeGame leftover {0} will be ended before deleting" } },
            { "col.addon.confirm.helpers", new[]{ "\r\n\r\nWeGame 退出后仍留着辅助进程 {0} 会先把它们结束再删除", "\r\n\r\nWeGame left helper processes behind ({0}). They will be ended first, then the deletion runs." } },
            { "col.addon.ready", new[]{ "可删除 {0} 项 共 {1}", "{0} deletable, {1} in total" } },
            { "col.addon.clean", new[]{ "未发现可删除的附加层", "No deletable add-ons found" } },
            { "col.addon.inspecting", new[]{ "正在检查附加层", "Checking add-ons" } },
            { "col.addon.deleting", new[]{ "正在删除附加层", "Deleting add-ons" } },
            { "col.addon.confirm", new[]{ "将直接删除识别出的英雄联盟附加层目录 AI 教练 iCreate 录制等\r\n\r\n此操作不可恢复 客户端更新或修复时会重新下载这些组件 游戏本体 登录链路和更新器不在删除范围\r\n\r\n请确认英雄联盟与 WeGame 已完全退出", "The detected League add-on folders (AI Coach, iCreate recording and similar) will be deleted outright.\r\n\r\nThis cannot be undone. The client re-downloads these components on update or repair. The game itself, the login chain and the updater are not touched.\r\n\r\nMake sure League and WeGame are fully closed." } },

            { "lolq.err.noinput", new[]{ "未提供英雄联盟目录", "No League folder given" } },
            { "lolq.err.badformat", new[]{ "英雄联盟目录格式无效", "Invalid League folder format" } },
            { "lolq.err.notroot", new[]{ "目录不是有效的国服英雄联盟安装根目录", "Folder is not a valid CN League install root" } },
            { "lolq.err.enumproc", new[]{ "无法枚举系统进程", "Could not enumerate system processes" } },
            { "lolq.proc.unknown", new[]{ "未知进程", "Unknown process" } },
            { "lolq.err.clientrunning", new[]{ "检测到运行中的客户端 {0}", "Running client detected {0}" } },
            { "lolq.item.notdir", new[]{ "目标不是目录 未处理", "Target is not a folder; skipped" } },
            { "lolq.item.vanished", new[]{ "源目录在执行前发生变化", "Source folder changed before the action ran" } },
            { "lolq.err.srcreparse", new[]{ "目标路径包含重解析点", "Target path contains a reparse point" } },
            { "lolq.item.deleted", new[]{ "已删除", "Deleted" } },
            { "lolq.item.deletefail", new[]{ "删除失败 {0}", "Delete failed {0}" } },
            { "lolq.err.deleteincomplete", new[]{ "目录未能完全删除 可能仍被占用", "Folder not fully deleted; it may still be in use" } },
            { "lolq.msg.deldone", new[]{ "已删除英雄联盟附加层", "League add-ons deleted" } },
            { "lolq.msg.delpartial", new[]{ "仅完成部分删除 请关闭占用后重试", "Only partly deleted; close whatever is using it and retry" } },
            { "lolq.msg.delnone", new[]{ "未删除任何内容", "Nothing was deleted" } },
            { "lolq.err.rootunresolved", new[]{ "暂时无法确认安装目录结构 客户端可能正在更新", "Cannot confirm the install layout right now; the client may be updating" } },
            { "lolq.err.closefirst", new[]{ "请先关闭英雄联盟和 WeGame {0}", "Close League and WeGame first {0}" } },
            { "lolq.err.nocandidate", new[]{ "未检测到可删除的附加层目录", "No deletable add-on folder detected" } },
            { "lolq.err.generic", new[]{ "操作失败", "Action failed" } },
            { "lolq.err.candnotdir", new[]{ "候选路径不是目录", "Candidate path is not a folder" } },
            { "lolq.err.candreparse", new[]{ "候选目录是重解析点", "Candidate folder is a reparse point" } },
            { "lolq.err.scanfail", new[]{ "扫描不完整 {0}", "Scan incomplete {0}" } },
            { "lolq.err.filereparse", new[]{ "目录包含文件重解析点 {0}", "Folder contains a file reparse point {0}" } },
            { "lolq.err.readfile", new[]{ "无法读取文件信息 {0}", "Could not read file info {0}" } },
            { "lolq.err.dirreparse", new[]{ "目录包含子目录重解析点 {0}", "Folder contains a subfolder reparse point {0}" } },
            { "lolq.err.readdir", new[]{ "无法读取目录信息 {0}", "Could not read folder info {0}" } },
            { "lolq.err.outsideroot", new[]{ "路径超出英雄联盟目录", "Path is outside the League folder" } },
            { "lolq.err.outsiderootr", new[]{ "目标路径超出英雄联盟目录", "Target path is outside the League folder" } },
            { "lolq.err.pathreparse", new[]{ "目标路径包含重解析点", "Target path contains a reparse point" } },
            { "lolq.err.pathinvalid", new[]{ "目标路径无效", "Target path is invalid" } },
        };
    }
}
