// @author bdth 2074055628@qq.com
// 文件用途 集中维护界面多语言文本

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.IO;
using System.Net;
using System.Runtime.InteropServices;
using System.Threading;
using System.Windows.Forms;
using Microsoft.Win32;

namespace PaviseApp
{
    internal static class Lang
    {
        public static int Cur;

        private static readonly Dictionary<string, string[]> M = new Dictionary<string, string[]>
        {
            { "nav.tame", new[]{ "反作弊" } },
            { "nav.white", new[]{ "白名单" } },
            { "nav.log", new[]{ "日志" } },
            { "nav.set", new[]{ "设置" } },
            { "nav.about", new[]{ "关于" } },
            { "nav.overview", new[]{ "概览" } },
            { "nav.library", new[]{ "游戏库" } },
            { "nav.policy", new[]{ "优化策略" } },
            { "search.name", new[]{ "搜索设置" } },
            { "search.hint", new[]{ "搜索各页面的设置和开关" } },
            { "search.sub", new[]{ "输入关键字 跨页面匹配 回车直达" } },
            { "search.empty", new[]{ "没有匹配的设置" } },
            { "v15.about.identity", new[]{ "Windows 性能守护" } },
            { "notes.title", new[]{ "版本说明" } },
            { "notes.sub", new[]{ "当前安装版本 {0}" } },
            { "notes.current", new[]{ "当前版本" } },
            { "notes.open", new[]{ "查看版本说明" } },
            { "notes.online", new[]{ "在 GitHub 查看全部" } },
            { "notes.close", new[]{ "关闭" } },
            { "v15.about.update", new[]{ "版本更新" } },
            { "v15.about.update.sub", new[]{ "只读取版本号 不上传设备数据 直连不通会自动换国内镜像线路" } },
            { "set.wipe.title", new[]{ "清除全部配置" } },
            { "set.wipe.desc", new[]{ "升级后莫名卡顿掉帧可以试这个 游戏库 白名单 开关和日志全部删掉 删之前先还原改过的系统项 有一项还不回去就一个文件都不删 清完自动退出" } },
            { "wipe.confirm", new[]{ "要清除 Pavise 的全部配置吗\r\n\r\n游戏库 白名单 开关和日志都会删掉 删了找不回来\r\n\r\n删之前会先把 Pavise 改过的系统项还原 还原不成功就一项都不删\r\n\r\n清完 Pavise 自动退出 重新打开就是全新的" } },
            { "wipe.ingame", new[]{ "对局进行中 先退出游戏再清除配置" } },
            { "wipe.done", new[]{ "配置已清除 删掉 {0} 个文件 系统改动已还原\r\n\r\n点确定后 Pavise 退出 重新打开就是全新的" } },
            { "wipe.failed", new[]{ "已中止 一个文件都没删\r\n\r\n这些项没能还原 {0}\r\n\r\n先处理掉再试一次" } },
            { "v15.restore.title", new[]{ "恢复全部系统改动" } },
            { "v15.restore.desc", new[]{ "把 Pavise 写过的注册表项 服务状态 电源计划一次性还原回原值 你的配置 游戏库和白名单都留着 不是重置 注意游戏还开着的时候 守护会在几秒后重新接管 想彻底停手先关掉总开关或退出游戏" } },
            { "mode.source.global", new[]{ "全局默认" } },
            { "mode.global.title", new[]{ "全局默认模式" } },
            { "mode.global.sub", new[]{ "所有游戏统一使用" } },
            { "mode.policy.active", new[]{ "当前实际行为 {0}" } },
            { "mode.tray.current", new[]{ "当前模式 {0} 打开面板可切换" } },
            { "mode.pick.standard", new[]{ "后台先轻压 一直抢资源的才加码 平时用这个" } },
            { "mode.pick.competitive", new[]{ "游戏之外能压的立刻全压 开着窗口的浏览器语音也不例外" } },
            { "mode.pick.extreme", new[]{ "在竞技之上再把停服务 停更新这些一起锁死 后台会明显变慢" } },
            { "mode.pick.custom", new[]{ "全按你的开关来 激进功能不会自己打开" } },
            { "set.pqos", new[]{ "禁止前台无输入降级" } },
            { "set.pqos.n", new[]{ "系统判定你一段时间没动键鼠就认为人不在 把前台程序降一档服务质量 而手柄游戏 看过场动画 挂机刷本这些场景键鼠本来就不会动 正好全中招 表现为放着不管一会儿帧数就掉 这项在对局期间告诉系统人一直在 退出游戏自动解除" } },
            { "set.awake", new[]{ "对局期间阻止息屏与睡眠" } },
            { "set.awake.n", new[]{ "同上一个原因 系统按键鼠活动判断有没有人 手柄游戏和长过场动画最容易被判成挂机 屏幕说黑就黑 严重的直接进睡眠 这项在对局期间持续告诉系统别休息 退出游戏自动解除 不改你的电源计划里的超时设置" } },
            { "v15.overview.sub", new[]{ "模式从右上角切换" } },
            { "v15.guard.state", new[]{ "PAVISE 守护状态" } },
            { "v15.effective.mode", new[]{ "实际生效模式" } },
            { "v15.master.short", new[]{ "认出你在玩的游戏就接管 退出后原样还原" } },
            { "v15.tile.game", new[]{ "游戏资源" } },
            { "v15.tile.game.sub", new[]{ "只给真正出画面的游戏进程提速" } },
            { "v15.tile.background", new[]{ "后台边界" } },
            { "v15.tile.background.sub", new[]{ "系统 声音 白名单绝不误伤" } },
            { "v15.tile.environment", new[]{ "电源与调度" } },
            { "v15.tile.environment.sub", new[]{ "电源和调度跟着模式走" } },
            { "v15.library.sub", new[]{ "随便选游戏目录里的哪个 EXE 都行 真正的渲染进程按前台全屏和 GPU 占用现场选举 选错也没关系" } },
            { "v15.library.empty", new[]{ "尚未添加游戏\r\n最省心的加法 先把游戏打开进到画面再点添加" } },
            { "v15.library.add", new[]{ "添加游戏" } },
            { "v15.library.drop", new[]{ "EXE LNK Steam 快捷方式都行 直接拖进窗口也可以 最省心的加法是先把游戏打开进到画面再点添加 正在出画面的进程会被自动标出并勾选\r\n\r\n模拟器 云游戏 老游戏这类识别不到的 选中条目点强制接管 进程一起来就直接进对局" } },
            { "scan.title", new[]{ "添加游戏" } },
            { "scan.browse", new[]{ "浏览文件" } },
            { "scan.running.tag", new[]{ "运行中" } },
            { "scan.renderer.tag", new[]{ "正在出画面 GPU {0}%" } },
            { "set.light", new[]{ "亮色模式" } },
            { "set.light.n", new[]{ "浅色界面 切换立即生效 默认暗色" } },
            { "scan.busy", new[]{ "正在读取各平台的安装记录" } },
            { "scan.busy.deep", new[]{ "正在遍历所选目录 大目录会久一点" } },
            { "scan.count", new[]{ "找到 {0} 个 其中 {1} 个尚未加入" } },
            { "scan.stage.running", new[]{ "正在枚举有窗口的运行中程序" } },
            { "scan.stage.gpu", new[]{ "正在采样 GPU 找出真正在出画面的那个 要几秒" } },
            { "scan.stage.count", new[]{ "{0}   已找到 {1} 个" } },
            { "scan.live", new[]{ "列表每 3 秒自动补一次 新打开的程序会自己出现" } },
            { "scan.none", new[]{ "没有找到已安装的游戏 可以试试深度扫描指定盘符" } },
            { "scan.all", new[]{ "全选" } },
            { "scan.already", new[]{ "已在库中" } },
            { "scan.add.n", new[]{ "添加 {0} 个" } },
            { "scan.deep", new[]{ "深度扫描" } },
            { "scan.running.btn", new[]{ "正在运行" } },
            { "scan.pick.confirm", new[]{ "加入游戏库" } },
            { "scan.deep.pick", new[]{ "选择要遍历的盘符或目录 用于找出没有安装记录的绿色版游戏" } },
            { "scan.added", new[]{ "已加入 {0} 个游戏" } },
            { "v15.library.running", new[]{ "运行中" } },
            { "v15.library.ready", new[]{ "已就绪" } },
            { "v15.library.force", new[]{ "强制接管" } },
            { "v15.library.force.on", new[]{ "强制接管 已开" } },
            { "v15.library.forced.tag", new[]{ "强制" } },
            { "v15.library.force.confirm", new[]{ "对 {0} 开启强制接管\r\n\r\n开了之后 只要这个 EXE 的进程还活着就算在对局中 不再看前台窗口 不看渲染画面 也不受内置的非游戏名单限制 模拟器 云游戏 老游戏 没有独占全屏的程序都能这样接管\r\n\r\n代价是它不会自己收场 如果指到一个常驻后台的程序上 Pavise 会一直待在游戏模式 后台压制不解除 电源计划也一直锁着 整机反而变慢\r\n\r\n只对你会主动开关的程序用这个 平时开着不管的别用" } },
            { "v15.library.force.noexe", new[]{ "这个条目只记了游戏目录 没有确切的 EXE 开不了强制接管\r\n\r\n删掉重新添加一次 直接选那个 EXE 文件" } },
            { "v15.policy.sub", new[]{ "右上角显示当前模式与实际来源" } },
            { "v15.policy.mode.hint", new[]{ "自定义之外的模式会接管部分开关 被接管的项会写明强制开还是强制关 并锁住不给点" } },
            { "v15.policy.core", new[]{ "全模式核心控制" } },
            { "policy.tab.core", new[]{ "核心控制" } },
            { "env.tab.kernel", new[]{ "内核调度" } },
            { "env.tab.device", new[]{ "设备链路" } },
            { "env.tab.input", new[]{ "键鼠链路" } },
            { "v17.env.kernel", new[]{ "显示 安全与调度内核项 多数要重启" } },
            { "v17.env.device", new[]{ "中断亲和 设备电源与网络限流" } },
            { "v17.env.input", new[]{ "键鼠输入路径上的系统项" } },
            { "policy.tab.custom", new[]{ "预设细节" } },
            { "policy.tab.extras", new[]{ "会话附加" } },
            { "plan.pick.title", new[]{ "对局电源计划" } },
            { "plan.pick.off", new[]{ "不切换" } },
            { "plan.pick.managed", new[]{ "PG托管" } },
            { "plan.pick.local", new[]{ "本机" } },
            { "plan.pick.desc", new[]{ "退出游戏自动切回来 选你自己的计划时 Pavise 只切换 不改它的任何一项 本机没有卓越性能会自动建一份 有就直接用你那份 最后那项托管方案是另一回事 选中才会创建 各项由 Pavise 按你的处理器写满 名字带本机签名 笔记本嫌太热就选平衡" } },
            { "cpu.place.title", new[]{ "游戏核心范围" } },
            { "cpu.place.overridden", new[]{ "已被核心分配接管" } },
            { "policy.tab.cores", new[]{ "核心分配" } },
            { "v15.policy.cores", new[]{ "逐核指定游戏能用哪些逻辑核" } },
            { "core.band.ccd", new[]{ "CCD {0}" } },
            { "core.band.ccd.cache", new[]{ "CCD {0} · 3D 缓存" } },
            { "core.tag.cache", new[]{ "缓存" } },
            { "core.preset.cache", new[]{ "仅缓存核" } },
            { "core.preset.ccd", new[]{ "CCD {0}" } },
            { "core.bar.spare", new[]{ "其余" } },
            { "core.band.perf", new[]{ "性能核" } },
            { "core.band.eff", new[]{ "能效核" } },
            { "core.band.all", new[]{ "处理器核心" } },
            { "core.band.meta.smt", new[]{ "{0} 物理核 / {1} 线程 · 带超线程" } },
            { "core.band.meta.solo", new[]{ "{0} 物理核 / {1} 线程" } },
            { "core.preset.all", new[]{ "全核" } },
            { "core.preset.physical", new[]{ "关超线程" } },
            { "core.preset.perf", new[]{ "仅性能核" } },
            { "core.preset.invert", new[]{ "反选" } },
            { "core.tag.exclusive", new[]{ "独占" } },
            { "core.tag.game", new[]{ "游戏" } },
            { "core.tag.bg", new[]{ "后台" } },
            { "core.role.game", new[]{ "游戏可用核心" } },
            { "core.role.count", new[]{ "{0} 线程 · {1} 个物理核" } },
            { "core.howto.game", new[]{ "点下面的核把它给游戏用 再点一下收回 也可以用快捷按钮整批选" } },
            { "core.guide.title", new[]{ "怎么用这一页" } },
            { "core.guide.open", new[]{ "使用说明" } },
            { "core.guide.tag", new[]{ "PAVISE // CORE GUIDE" } },
            { "core.guide.s1.t", new[]{ "多数人不需要动它" } },
            { "core.guide.s1.d", new[]{ "留默认的全核就行 系统调度器本来就会把游戏线程放性能核 让能效核去接后台 只有你确认游戏线程被丢到能效核上掉帧 手动划才有意义 划错了是负优化" } },
            { "core.guide.s2.t", new[]{ "划多少才够" } },
            { "core.guide.s2.d", new[]{ "现代游戏的渲染 物理 音频 网络各占线程 划得太少会直接卡死 建议至少留 8 个逻辑核 少于 2 个直接不让应用 想省事就用上面的快捷按钮" } },
            { "core.guide.s3.t", new[]{ "点应用才算数" } },
            { "core.guide.s3.d", new[]{ "格子点完只是待应用状态 上方计数会变成待应用 必须点右边的应用按钮才下发 对局进行中点应用立即生效 不用重启游戏" } },
            { "core.guide.hy.t", new[]{ "你这台是 Intel 大小核" } },
            { "core.guide.hy.d", new[]{ "性能核跑游戏 能效核接后台 这本来就是 Windows 调度器的默认行为 不用你划 值得动手的只有一种情况 你在任务管理器里看到游戏线程大量落在能效核上并且掉帧 那就用只用大核 代价是白扔掉能效核的算力 后台会挤到剩下的核上 12 代到 14 代还要注意关掉不带超线程的能效核没有意义 它们本来就一个核一个线程" } },
            { "core.guide.x3d.t", new[]{ "你这台是 AMD 双 CCD 且一边带 3D 缓存" } },
            { "core.guide.x3d.d", new[]{ "优先让 AMD 的芯片组驱动和 Xbox Game Bar 去判断游戏该用哪块 装好优化驱动的机器这一档就够了 只有你确认驱动没把游戏放到大缓存那块上 才手动选缓存 CCD 少数吃频率不吃缓存的游戏反过来选高频 CCD 换档以后看 1% 最差帧 平均帧一般不会动" } },
            { "core.guide.ccd.t", new[]{ "你这台是 AMD 多 CCD" } },
            { "core.guide.ccd.d", new[]{ "游戏线程分散在两块 CCD 上时 跨 CCD 通信要绕一圈 表现为帧时间毛刺 只用一块完整 CCD 能省掉这一段 代价是可用核心少一半 线程多的游戏反而更卡 所以先跑全核 卡顿明显再试单 CCD 别用快捷按钮乱划半块 CCD 那是两头不讨好" } },
            { "core.guide.smt.t", new[]{ "关超线程不是提升" } },
            { "core.guide.smt.d", new[]{ "同一个物理核的两个线程共用执行单元 关掉一半确实让剩下的线程独占 但现代游戏基本吃得下多线程 砍掉一半线程通常是净亏 只有极少数老游戏或者你明确测出来收益才值得 快捷按钮里的关超线程是给这种场景准备的 不是默认建议" } },
            { "core.guide.judge.t", new[]{ "怎么判断有没有用" } },
            { "core.guide.judge.d", new[]{ "看 1% 最差帧和帧时间毛刺 不要看平均帧 核心划分改善的是卡顿不是上限 平均帧一般纹丝不动 同一张图同一段路来回跑两次对比 改完立刻觉得变流畅多半是错觉" } },
            { "core.guide.s4.t", new[]{ "后台不用你操心" } },
            { "core.guide.s4.d", new[]{ "被重压的后台会收缩到哪几个核 由算法跟着你的划分实时重算 永远不会和你划给游戏的核重叠 也不会切开一对超线程 这一项没有需要你设置的地方" } },
            { "core.guide.note", new[]{ "以上全部只在对局中下发给游戏进程 退出游戏自动还原 不写注册表也不改系统设置 关掉 Pavise 一切恢复原样" } },
            { "cpu.place.manual", new[]{ "手动" } },
            { "core.bg.ok", new[]{ "后台 {0} 核 {1}" } },
            { "core.bg.landing", new[]{ "重压后台落点 核 {0} 共 {1} 核" } },
            { "core.bg.toofull", new[]{ "剩不下 {0} 个核给后台 独占不生效" } },
            { "core.bg.allcores", new[]{ "不分区 后台按档位处理" } },
            { "core.land.squeezed", new[]{ "重压后台落点 核 {0} · 从 {1} 个核挤到 {2} 个" } },
            { "core.land.plain", new[]{ "重压后台落点 核 {0}" } },
            { "core.land.narrow", new[]{ "重压后台落点 核 {0} · 已经够窄 不再挤" } },
            { "core.land.nowhole", new[]{ "重压后台落点 核 {0} · 都是超线程的另一半 不挤" } },
            { "core.land.none", new[]{ "游戏核占满 重压后台没有可去的核" } },
            { "core.topo.line", new[]{ "{0} 物理核 · {1} 逻辑核 · 其中 {2} 个带超线程" } },
            { "core.topo.unknown", new[]{ "未知处理器" } },
            { "core.topo.default", new[]{ "未自定义" } },
            { "core.apply", new[]{ "应用" } },
            { "core.state.applied", new[]{ "已生效 游戏 {0} 核 覆盖 {1} 个物理核" } },
            { "core.state.dirty", new[]{ "待应用 游戏 {0} 核 覆盖 {1} 个物理核" } },
            { "core.state.few", new[]{ "至少要留两个逻辑核 否则游戏会卡死" } },
            { "core.state.scope", new[]{ "只在对局中下发给游戏进程 退出游戏自动还原 不写注册表也不改系统设置 关掉 Pavise 一切恢复原样" } },
            { "cpu.place.all", new[]{ "全核" } },
            { "cpu.place.ccd", new[]{ "单 CCD" } },
            { "cpu.place.performance", new[]{ "只用大核" } },
            { "cpu.place.partition", new[]{ "游戏分区" } },
            { "cpu.place.cache", new[]{ "缓存 CCD" } },
            { "cpu.place.freq", new[]{ "高频 CCD" } },
            { "cpu.place.pending", new[]{ "对局结束后生效" } },
            { "cpu.place.x3d.desc", new[]{ "拿不准就留默认的全核 由 AMD 驱动决定游戏用哪块 装了 3D V-Cache 优化驱动的机器这档就够 怀疑驱动没把游戏放到大缓存上 再选单 CCD 想逐个核自己挑就选手动 所有模式都按这里选 " } },
            { "cpu.place.x3d3.desc", new[]{ "拿不准就留默认的全核 由 AMD 驱动决定 装了 3D V-Cache 优化驱动的机器这档就够 缓存 CCD 适合绝大多数游戏 高频 CCD 只对少数吃频率的游戏有用 换档看 1% 最差帧 平均帧一般不会动 切换即时生效 对局中会等对局结束" } },
            { "cpu.place.ccd.desc", new[]{ "拿不准就留默认的全核 单 CCD 只让游戏用一个完整处理器 Die 省掉跨 CCD 通信 代价是核心少一半 线程多的游戏全核更稳 卡顿明显再试单 CCD 想逐个核自己挑就选手动 所有模式都按这里选 " } },
            { "cpu.place.ccd3.desc", new[]{ "拿不准就留默认的全核 选定一块后游戏只用它 后台和中断归另一块 省掉跨 CCD 通信 代价是核心少一半 哪块更好因机而异 两块都可以试 换档看 1% 最差帧 平均帧一般不会动 切换即时生效 对局中会等对局结束" } },
            { "cpu.place.hybrid.desc", new[]{ "留默认的全核就行 系统调度器本来就把游戏线程放 P 核 让 E 核接后台 多数情况这样最好 只有确认游戏线程被丢到 E 核掉帧时才选只用大核 那会白扔掉 E 核的算力 想逐个核自己挑就选手动 所有模式都按这里选 " } },
            { "cpu.place.generic.desc", new[]{ "默认全核 游戏分区会留几个核心给后台 游戏不去挤它们 后台程序多 一边挂东西一边打的机器值得开 系统干净就留全核 改善的是卡顿和 1% 最差帧 平均帧一般不会动 想逐个核自己挑就选手动 所有模式都按这里选 " } },
            { "cpu.place.unavailable.desc", new[]{ "本机物理核较少 自动分出后台核心的算力损失盖过隔离收益 所以没做游戏分区这档 想逐个核自己挑就选手动 所有模式都按这里选" } },
            { "v15.policy.custom", new[]{ "自定义预设细节" } },
            { "v15.policy.extras", new[]{ "会话附加动作 所有模式生效" } },
            { "v15.boost.sub", new[]{ "同时抬高游戏进程的 CPU 优先级 IO 优先级 内存页优先级 并把它标成显卡侧的高优先级客户端 目标只认真正在出画面的那个进程 启动器 游戏平台和更新器不会被误当成游戏提速 提优在对局中下发 退出即还原" } },
            { "v15.notif.sub", new[]{ "微信 QQ 和系统通知不再弹出来抢焦点 全屏独占的游戏被弹窗切出去时最容易掉帧甚至丢操作 副作用是对局期间你收不到任何提醒 退出游戏自动恢复" } },
            { "addon.open", new[]{ "英雄联盟附加层清理" } },
            { "addon.open.sub", new[]{ "删掉 AI 教练 录制这类附加组件 腾出磁盘也少几个后台进程 游戏本体和登录链路不动 点一下直接删 客户端更新时可能重新下回来 相关程序在跑时不会动手" } },
            { "addon.noroot", new[]{ "游戏库里没找到英雄联盟 先去游戏库添加" } },
            { "addon.hint.fail", new[]{ "检查失败" } },
            { "addon.hint.clean", new[]{ "没有可删的附加层 已经是干净的" } },
            { "addon.hint.ready", new[]{ "可删 {0} 项 共 {1}" } },
            { "addon.hint.deleting", new[]{ "正在删除" } },
            { "addon.hint.done", new[]{ "已删除 {0} 项 腾出 {1}" } },
            { "v15.anticheat.sub", new[]{ "跟游戏模式无关 只管下面列出来的这些反作弊程序" } },
            { "v14.master", new[]{ "Pavise 智能守护" } },
            { "preset.standard", new[]{ "常规" } },
            { "preset.competitive", new[]{ "竞技" } },
            { "preset.extreme", new[]{ "极限" } },
            { "preset.custom", new[]{ "自定义" } },
            { "v14.cpu.topology", new[]{ "CPU 调度拓扑" } },
            { "v14.boost.status", new[]{ "游戏提权状态" } },
            { "v14.boost.disabled", new[]{ "游戏提优已关闭" } },
            { "v14.boost.wait", new[]{ "等游戏画面出来" } },
            { "v14.boost.no.renderer", new[]{ "看到启动器了 还在等游戏本体" } },
            { "v14.boost.applying", new[]{ "正在提速 {0}" } },
            { "v14.boost.verified", new[]{ "已生效 {0}\r\n提速已写进系统并确认" } },
            { "v14.boost.protected", new[]{ "{0} 被反作弊保护 优先级改不动\r\n策略页开 后备提优 下次进游戏由系统直接给高优先级 其余优化照常生效" } },
            { "v14.boost.protected.ifeo", new[]{ "{0} 被反作弊保护 后备提优已安排 下次进游戏由系统直接给高优先级\r\n其余优化照常生效" } },
            { "v14.bg.master", new[]{ "后台压制 总开关" } },
            { "v14.bg.master.sub", new[]{ "这一项管的是要不要动后台程序的优先级 效率模式 IO 与内存页优先级 关掉之后一个后台程序都不碰 下面那些相关开关随之全部失效 无论开关状态如何 游戏本体 反作弊 系统核心组件 其他用户账户下的进程和白名单里的程序 任何时候都不在压制范围内" } },
            { "v14.preset.forced.on", new[]{ "预设强制开" } },
            { "v14.preset.forced.off", new[]{ "预设强制关" } },
            { "v14.anticheat.boundary", new[]{ "反作弊只在这里管 不跟着游戏模式走" } },
            { "v14.anticheat.master.sub", new[]{ "只动下面列出的反作弊程序 不会把游戏平台和登录器当成反作弊" } },
            { "v14.anticheat", new[]{ "反作弊专项" } },
            { "v14.cpu.multigroup", new[]{ "多处理器组 CPU Sets 跨组调度 游戏核心范围可手动选择" } },
            { "v14.cpu.hybrid", new[]{ "混合架构 默认全核 游戏核心范围可切到只用大核或手动逐核挑" } },
            { "v14.cpu.x3d", new[]{ "非对称 L3 X3D 默认全核 需要时可手动切到大缓存 CCD" } },
            { "v14.cpu.generic", new[]{ "{0} 逻辑处理器 常规按需升级 竞技立即全力压制后台" } },
            { "detect.learned", new[]{ "命中已确认的渲染进程" } },
            { "detect.fullscreen", new[]{ "前台全屏画面" } },
            { "detect.window", new[]{ "所选 EXE 自带前台窗口" } },
            { "detect.gpu", new[]{ "GPU 3D 引擎主导 {0}%" } },
            { "detect.gpu.pending", new[]{ "窗口化候选 等待 GPU 证据确认" } },
            { "detect.forced", new[]{ "强制接管 进程在就算一局" } },
            { "title.noelev", new[]{ "未提权 压制类功能无效" } },
            { "title.admin", new[]{ "管理员权限" } },
            { "title.guard", new[]{ "守护中 {0}" } },
            { "title.idle", new[]{ "待命" } },

            { "btn.browse", new[]{ "浏览 exe" } },
            { "btn.remove", new[]{ "移除选中" } },

            { "st.off", new[]{ "已关闭" } },
            { "st.mon", new[]{ "监控中 未检测到列表内的游戏" } },
            { "st.armed", new[]{ "已就位 {0} 进入对局画面自动接管" } },
            { "st.grace", new[]{ "{0} 已退出 还有 {1} 秒宽限 后台已先还原 重进游戏无缝续接" } },
            { "st.active", new[]{ "激活中 {0} 已压制 {1} 个进程" } },
            { "st.boost", new[]{ "已提优 {0} {1}" } },
            { "st.hp", new[]{ "高性能电源" } },
            { "st.pr", new[]{ "电源就绪" } },

            { "tame.toggle", new[]{ "反作弊压制 总开关" } },
            { "set.nvmax", new[]{ "NVIDIA 电源模式 最高性能优先" } },
            { "set.nvmax.n", new[]{ "驱动默认按负载自适应调频 从低频爬到满频要一小段时间 这段时间里帧数是不稳的 这项让显卡对局期间一直待在高频 省掉爬频那一下 代价是功耗和温度全程更高 笔记本散热压不住的话会更早撞温度墙 结果反而比不开还慢 关掉恢复原样" } },
            { "set.nv.none", new[]{ "没检测到 NVIDIA 驱动 此项停用" } },
            { "set.nvfrl", new[]{ "NVIDIA 驱动级帧率上限" } },
            { "set.nvfrl.n", new[]{ "帧数封了顶之后每帧的间隔更均匀 观感比忽高忽低的高帧更稳 显卡也更凉更省电 屏 3 是取你屏幕刷新率减 3 这是 G-Sync 生效区间的上沿 超过就会退出可变刷新进入撕裂或垂直同步 代价是帧数上限被锁死 跑分和高刷追求上限的别开 选关恢复原样" } },
            { "set.nvll", new[]{ "NVIDIA 低延迟 预渲染队列压到 1" } },
            { "set.nvll.n", new[]{ "驱动默认允许 CPU 提前给显卡排好几帧 排得越多你按下去到看见的间隔越长 这项压到只排一帧 显卡吃满时能明显降低操作延迟 显卡没跑满时队列本来就空 开了没差别 极端情况下会让帧数略降一点点换延迟 不改画质也不动游戏文件 关掉恢复原样" } },
            { "frl.off", new[]{ "关" } },
            { "frl.screen", new[]{ "屏 3" } },
            { "dlss.latest", new[]{ "最新" } },
            { "set.nvdlss", new[]{ "DLSS 换新算法" } },
            { "set.nvdlss.n", new[]{ "只有游戏里已经开了 DLSS 才有意义 游戏内置的算法版本停在发售那天 这项让驱动替换成当前最新的一套 画面更清楚 拖影和锯齿更少 老游戏也吃得到 少数游戏对版本有校验 换了会花屏或直接不启动 遇到就选关恢复原样" } },
            { "set.nvdlss.old", new[]{ "驱动太老 需要 566.14 以上 升级后可用" } },
            { "set.nvdlss.nogpu", new[]{ "本机显卡不是 RTX 卡 没有 DLSS 超分能力 这项用不上 GTX 和更老的卡都不支持" } },
            { "set.nvrebar", new[]{ "ReBAR 强制开启" } },
            { "set.nvrebar.n", new[]{ "没有 ReBAR 时 CPU 每次只能通过一个 256MB 的窗口访问显存 开了就能一次访问整块 NVIDIA 只给自己测过的一批游戏默认开启 名单外的一律关着 这项对名单外的游戏也强开 有的游戏帧数真能涨几个百分点 个别游戏反而掉帧或者花屏 没法预测 同一个游戏开关各打一局最快 前提是 BIOS 里也要开 关掉恢复原样" } },
            { "set.nvrebar.det.on", new[]{ "本机已开启 窗口 {0}" } },
            { "set.nvrebar.det.off", new[]{ "本机未开启 窗口 {0} 要在 BIOS 里打开才有用" } },
            { "set.nvansel", new[]{ "不让 Ansel 进游戏" } },
            { "set.nvansel.n", new[]{ "Ansel 是 NVIDIA 注入进游戏进程的截图拍照组件 它要往游戏里挂钩子 既占一份常驻开销 也是反作弊误报的常见来源 这项不让它加载 代价是 NVIDIA 覆盖层里的照片模式用不了 游戏自带截图和录制不受影响 关掉恢复原样" } },
            { "set.nvbatt", new[]{ "禁用电池模式帧率限制" } },
            { "set.nvbatt.n", new[]{ "笔记本一拔电源 驱动会不声不响把游戏压到 30 或 60 帧省电 很多人以为是游戏卡了 这项让它插不插电都按满血跑 代价很直接 电池掉得快很多 发热也上来 台式机没有这项开销" } },
            { "sec.gfx.session", new[]{ "全局驱动项 打游戏时生效 退出还原" } },
            { "v16.spec.cpu", new[]{ "处理器" } },
            { "v16.spec.gpu", new[]{ "显示适配器" } },
            { "v16.spec.mem", new[]{ "系统内存" } },
            { "v16.spec.hags", new[]{ "硬件加速 GPU 计划" } },
            { "v16.device.hags.on", new[]{ "已开启" } },
            { "v16.device.hags.off", new[]{ "已关闭" } },
            { "v16.device.hags.none", new[]{ "显卡或驱动不支持" } },
            { "v16.device.hags.unknown", new[]{ "读不到状态" } },
            { "rep.log.none", new[]{ "日志为空" } },
            { "rep.clear.log", new[]{ "清除日志" } },
            { "rep.clear.ask", new[]{ "清空运行日志\r\n\r\nPavise.log 会被清空 已归档的 Pavise.log.old 不受影响" } },
            { "gm.standby", new[]{ "对局前清理低优先级待机内存" } },
            { "gm.standby.sub", new[]{ "只清系统自己判定最不可能再用到的那一部分缓存页 耗时约 13 毫秒 不碰整个待机列表 所以不会把有用的文件缓存一起丢掉 内存紧张的机器加载会顺一点 内存充裕的基本无感 每局只做一次" } },
            { "gm.trimbg", new[]{ "对局稳定后回收后台工作集" } },
            { "gm.trimbg.sub", new[]{ "开局 30 秒等加载过去再动手 把已经被重压的后台程序占着的物理内存交还系统 游戏 你正用着的前台 白名单和反作弊一个不碰 内存回到待机列表 游戏随时能拿 后台程序不会被关也不会丢数据 代价是你切回那些程序时第一下会明显卡一下 因为它们要重新把页读回来 低优先级慢慢做 最多 3 秒 退出对局立刻停" } },
            { "gm.stbguard", new[]{ "待机列表超阈值时清空" } },
            { "gm.stbguard.sub", new[]{ "ISLC 那一套 对局中每 5 秒看一眼 待机列表堆到 1G 以上并且可用内存掉到 1G 以下 两个条件同时满足才清一次 治的是待机列表堆太大引发的周期性微卡 不是给你多变出内存 代价说在前面 这一下会把系统缓存整个丢掉 之后所有程序读文件都要重新走硬盘 内存大的机器基本触发不了这个条件" } },
            { "gm.pausewu", new[]{ "对局期间暂停 Windows 更新" } },
            { "gm.pausewu.sub", new[]{ "免得对局打到一半突然开始下载安装 硬盘和 CPU 被整块占走 卡顿藏都藏不住 暂停的是更新动作本身 不改你系统里的更新设置和策略 退出对局自动恢复" } },
            { "set.usbaffinity", new[]{ "USB 控制器中断避让" } },
            { "set.usbaffinity.n", new[]{ "4K 8K 高回报率鼠标每秒要打断 CPU 几千次 这些打断如果全落在游戏正用的核上 渲染线程就得反复被抢走再换回来 表现为甩枪时掉帧 这项把 USB 控制器的中断改投到专门接中断的那几个核上 默认关闭 只建议 4K 以上回报率的鼠标开 1000Hz 及以下打断次数低一个量级 开了基本没收益 反而可能换来空闲后第一下操作发木 需要重启电脑或重新插拔设备才生效 可恢复" } },
            { "usbaffinity.warn", new[]{ "这一项会把键盘鼠标所在的 USB 控制器中断绑死在固定几个核上 核心不多的机器上这几个核同时还是后台压制的落点 而且它们空闲时会进深度睡眠 中断只能等它醒过来 真机上出现过放着不动一会儿 回来第一下点击明显发木的情况\n\n只有 4K 8K 高回报率鼠标才值得冒这个险 1000Hz 及以下的鼠标开了基本没有收益\n\n确定要开吗 出问题就把这个开关拨回去" } },
            { "set.pointerprec", new[]{ "关闭指针精度增强" } },
            { "set.pointerprec.n", new[]{ "系统默认开着一条鼠标加速曲线 甩得快同样的物理距离在屏幕上走得更远 这不是延迟问题是一致性问题 手上的肌肉记忆永远对不准 竞技射击一般都关 走 Raw Input 的游戏本来就绕过它 关掉只影响桌面和没走 Raw Input 的游戏 立即生效 可恢复" } },
            { "set.gmguard", new[]{ "Windows 游戏模式守护" } },
            { "set.gmguard.n", new[]{ "游戏模式的实际作用是挡住对局中的驱动安装和重启弹窗 而不是提升帧数 它常被旧优化教程当成负优化关掉 这项把它拨回开启 本来就开着就什么都不做 立即生效 可恢复" } },
            { "set.netthrottle", new[]{ "网络限流值校正" } },
            { "set.netthrottle.n", new[]{ "系统默认每毫秒最多处理 10 个非多媒体网络包 把它改成无限是常见教程做法 但实测反而抬高网络驱动的延迟 而游戏那点流量根本碰不到这个上限 改了纯亏 当前值正常就什么都不做 只有被改坏的才修回默认 重启生效" } },
            { "netthrottle.ok", new[]{ "当前值 {0} 在正常范围内 不用校正" } },
            { "netthrottle.broken", new[]{ "当前值 {0} 超出有效范围 建议校正回系统默认 10" } },
            { "set.clock", new[]{ "平台时钟校正" } },
            { "set.clock.n", new[]{ "往启动配置里写强制 HPET 和关闭动态时钟是当年的提帧秘籍 在现代平台上是纯减益 系统默认用的 TSC 读一次只要几纳秒 HPET 要走总线 慢几个数量级 而游戏每帧要读很多次时间 这项把陈旧的覆盖清掉回到系统自选 启动配置本来就干净的什么都不做 重启生效 可还原" } },
            { "clock.ok", new[]{ "启动配置干净 没有陈旧的时钟覆盖 不用校正" } },
            { "clock.repaired", new[]{ "已校正 启动配置回到系统默认计时" } },
            { "clock.broken", new[]{ "检测到陈旧覆盖 {0} 建议校正" } },
            { "netthrottle.absent", new[]{ "当前没设这个值 就是系统默认 不用校正" } },
            { "gm.upyield", new[]{ "后台上传限速" } },
            { "gm.upyield.sub", new[]{ "上行被占满时数据包要在本机排队才出得去 游戏的每一个操作都得排在网盘同步和 BT 做种后面 延迟成倍抬高 而下行占满对延迟的影响远没这么大 所以只限上行 语音和白名单内的程序不限 退出对局解除" } },
            { "set.quantum", new[]{ "前台时间片校正" } },
            { "set.quantum.n", new[]{ "这个值决定前台程序每次拿到 CPU 能连续跑多久 老教程爱把它调大 想让游戏多占一点 实际结果是别的线程要等更久才轮到 一旦游戏在等它们 反而变成卡顿 系统默认值是权衡过的 没被改过就什么都不做 只把被改过的修回默认 立即生效" } },
            { "quantum.ok", new[]{ "当前已是系统默认 不用校正" } },
            { "quantum.broken", new[]{ "当前值 {0} 不是系统默认 建议校正回默认 2" } },
            { "quantum.absent", new[]{ "当前没设这个值 就是系统默认 不用校正" } },
            { "set.devpower", new[]{ "禁止网卡节能断电" } },
            { "set.devpower.n", new[]{ "系统闲一会儿会给网卡断电省电 再有流量时要先唤醒 这段唤醒期间的包直接丢 表现为无缘无故一次卡顿加掉线重连 笔记本无线网上尤其明显 只改这一项 不动网卡别的高级设置 立即生效 可恢复" } },
            { "set.accesskeys", new[]{ "辅助功能按键拦截" } },
            { "set.accesskeys.n", new[]{ "筛选键按微软自己的定义就是让键盘忽略短促和重复的击键 开着等于在你的输入路径上主动插了一段延迟 这是键鼠这一环里唯一能救回两位数毫秒的软件项 多数人是游戏里长按 Shift 被弹窗误开的 这项把筛选键 粘滞键 切换键的生效位连同触发热键一起清掉 免得以后再被误开 不需要管理员也不用重启 需要这些辅助功能的别开 可还原" } },
            { "set.hidpower", new[]{ "禁止键鼠设备选择性暂停" } },
            { "set.hidpower.n", new[]{ "系统会给闲置的 USB 设备断电挂起 键鼠也在其列 微软自己的选择性暂停文档承认退出挂起的延迟会表现为屏幕上的顿挫 治的是空闲一会儿之后第一下操作发飘 持续操作时的延迟不受影响 别指望它降稳态延迟 台式机没有代价 笔记本要拿续航换 只碰键鼠所在的端口和根集线器 不碰 U 盘和声卡 可恢复" } },
            { "set.inputqueue", new[]{ "键鼠队列长度校正" } },
            { "set.inputqueue.n", new[]{ "这个值决定驱动能缓存多少条还没被处理的输入 它决定的是容量不是速度 所以调大调小都不影响延迟 网上教你调低它来降延迟是彻底的误传 而调低之后高回报率鼠标一次快速甩动就可能撑爆队列 直接丢输入 这项把被第三方工具改过的值改回系统默认 100 没被改过就什么都不做 重启生效 可还原" } },
            { "audit.pollprobe", new[]{ "鼠标回报率实测" } },
            { "audit.poll.probing", new[]{ "请一直画圈移动鼠标 静止时鼠标不上报就测不出来" } },
            { "audit.poll.ok", new[]{ "回报率实测 {0} Hz 间隔中位数 {1} 毫秒 取自 {2} 个样本" } },
            { "audit.poll.weak", new[]{ "偏低 每次移动最多要等 {0} 毫秒才被系统看见 去鼠标驱动或官方软件里调到 1000Hz 这是外设段能拿到的最大一笔" } },
            { "audit.poll.good", new[]{ "已经到位 再往上到 8000Hz 的收益不足 1 毫秒 还要吃掉单核百分之二三 CPU 吃紧的游戏里反而可能换来卡顿" } },
            { "audit.poll.fail", new[]{ "回报率实测失败 {0}" } },
            { "audit.poll.nostart", new[]{ "起不了 Raw Input 监听 这一项本次测不了" } },
            { "tame.lvl.eco", new[]{ "温和" } },
            { "tame.lvl.res", new[]{ "均衡" } },
            { "tame.lvl.iso", new[]{ "强力" } },

            { "gs.moff", new[]{ "总开关关闭" } },
            { "gs.noff", new[]{ "未开启" } },
            { "gs.noproc", new[]{ "未检测到进程" } },
            { "gs.thr", new[]{ "已压制 {0}" } },
            { "gs.prot", new[]{ "另有 {0} 个受内核保护压不动" } },

            { "white.page.sub", new[]{ "这里列出的程序永远不会被压制 把 EXE 或快捷方式拖进来就行 作用范围自动判断" } },
            { "white.page.empty", new[]{ "白名单是空的\r\n把程序拖进来 或点右边选运行中的程序" } },
            { "white.page.pick", new[]{ "选运行中的程序" } },
            { "white.page.drop", new[]{ "把 EXE 或快捷方式直接拖进左边就能加\r\n\r\n普通程序会连它拉起的子进程一起保护 命令行和脚本宿主这类只保护它自己 规则自动判断 不用你选\r\n\r\n想改范围就右键条目" } },
            { "white.page.platforms", new[]{ "这些游戏平台的客户端已经内置豁免 不用手动加 {0}" } },
            { "white.badge.family", new[]{ "连子进程" } },
            { "white.badge.only", new[]{ "仅此程序" } },
            { "white.badge.name", new[]{ "按进程名" } },
            { "white.badge.name.sub", new[]{ "同名进程都算 不看路径" } },
            { "white.state.running", new[]{ "{0} 个在跑" } },
            { "white.state.idle", new[]{ "没在跑" } },
            { "white.menu.narrow", new[]{ "只保护这一个 不含子进程" } },
            { "white.menu.widen", new[]{ "连子进程一起保护" } },
            { "white.required.locked", new[]{ "这是系统必需的内置项 不能删" } },
            { "white.group.builtin", new[]{ "系统内置 {0} 项 不可删" } },
            { "white.browse.filter", new[]{ "程序或快捷方式|*.exe;*.lnk|程序|*.exe|快捷方式|*.lnk" } },
            { "white.pick.title", new[]{ "选运行中的程序" } },
            { "white.pick.sub", new[]{ "只列出你自己开着的有窗口的程序 系统进程和反作弊不在其中" } },
            { "white.pick.busy", new[]{ "正在看有哪些程序开着" } },
            { "white.pick.none", new[]{ "没有可加的程序 开着的都已经在白名单里了" } },
            { "white.pick.count", new[]{ "找到 {0} 个可加的程序" } },
            { "white.pick.add", new[]{ "加入白名单" } },
            { "white.pick.add.n", new[]{ "加入 {0} 个" } },
            { "white.pick.procs", new[]{ "{0} 进程" } },
            { "white.kind.family", new[]{ "应用家族" } },
            { "white.kind.path", new[]{ "精确 EXE 路径" } },
            { "white.kind.name", new[]{ "进程名" } },
            { "white.matches", new[]{ "当前匹配 {0} 个" } },
            { "white.matches.pending", new[]{ "正在核对当前匹配" } },
            { "white.duplicate", new[]{ "这条规则已经有了 或者输入的不是有效的 EXE 和进程名" } },
            { "white.save.failed", new[]{ "白名单没能安全写入磁盘 这次修改没生效 检查一下数据目录权限或磁盘状态" } },
            { "white.required", new[]{ "Windows 稳定运行必需的内置保护 删不得 它只认受信的系统路径" } },
            { "white.required.badge", new[]{ "内置保护" } },
            { "white.reset.confirm", new[]{ "恢复默认预设会删掉全部自定义白名单规则 无法撤销" } },
            { "btn.reset", new[]{ "恢复默认预设" } },

            { "btn.openlog", new[]{ "打开日志文件" } },

            { "set.gpu", new[]{ "逐游戏 GPU 偏好 强制独显" } },
            { "set.gpu.n", new[]{ "双显卡笔记本上系统有时会把游戏判给核显 帧数直接腰斩 而且很多人不会去翻系统设置里那个逐程序的偏好列表 这项把游戏库里的每个游戏都写成高性能 GPU 只写偏好 不改驱动也不禁用核显 下次启动游戏生效 关掉即还原" } },
            { "set.dvr", new[]{ "关闭 Game DVR 与 Xbox 后台录制" } },
            { "set.dvr.sub", new[]{ "Game DVR 开着时系统会一直在后台滚动缓存最近几分钟的画面 显卡编码单元和内存被长期占着 而多数人从来不用这个回放 关掉之后 Xbox 的即时回放和录制热键会失效 靠这个功能录集锦的别开 自定义才能自己选 竞技和极限强制开 常规强制关" } },
            { "set.notif", new[]{ "游戏时免打扰" } },
            { "gm.squeezebg", new[]{ "重压后台绑核收缩" } },
            { "gm.squeezebg.sub", new[]{ "把已经被重压的后台从铺满全机收缩到少数几个物理核上 治的是它们并发访存挤占内存带宽 这一项优先级和效率模式都管不到 落点由算法跟着你划的游戏核实时算 一个核不会既给游戏又当落点 代价是那些后台程序会明显变慢 压缩解压 编译 转码这类会拖长几倍 你切过去用它的那一刻立即放开 默认开" } },
            { "gm.squeezebg.none", new[]{ "本机只有 {0} 个物理核 少于 {1} 个 收缩之后剩给后台的核不够它运转 这项在本机始终不生效" } },
            { "gm.squeezebg.multigroup", new[]{ "本机是多处理器组 亲和掩码跨不了组 这项不生效" } },
            { "gm.squeezebg.narrow", new[]{ "当前划分下后台只剩 {0} 个物理核 已经比收缩后还窄 没有可挤的余地 这项暂时不动手 把游戏核收回一些它就会重新生效" } },
            { "gm.gpudemote", new[]{ "后台 GPU 优先级降级" } },
            { "gm.gpudemote.sub", new[]{ "后台程序提交显卡任务时会插进游戏的队列里 游戏就得等它画完才轮到自己 表现为帧时间忽然拉长 这项把它们的显卡优先级压到游戏之下 副作用是直播推流 录屏 视频硬解会明显掉帧 用这些先把 OBS 这类加进白名单" } },
            { "gm.boost", new[]{ "游戏进程提优" } },
            { "gm.lane", new[]{ "渲染线程单独提优" } },
            { "gm.lane.sub", new[]{ "游戏有上百个线程 真正决定帧数的常常只有一个 开局认出它再单独抬一档 游戏内部线程互相抢 CPU 时优先保出画面 6 核 12 线程这类容易被吃满的机器收益最大 认不出来时退回整个进程一起提优 不会乱抬" } },
            { "gm.ifeo", new[]{ "后备提优 由系统在启动时下发" } },
            { "gm.ifeo.sub", new[]{ "内核级反作弊会拦住外部程序改游戏优先级 Pavise 拿不到句柄权限 这项改走另一条路 让 Windows 在游戏进程创建的那一刻就把优先级设好 反作弊挡不住 只写优先级一项 不碰调试器劫持相关的键 下次启动游戏才生效 关掉本开关立即清除已写入的项" } },
            { "gm.aggressive", new[]{ "后台压制范围与力度加码" } },
            { "gm.aggressive.sub", new[]{ "开了才把后台压到最狠那一档 范围也跟着放宽 开着窗口的浏览器 语音 IDE 也照压 只有你正在用的前台程序和它的子进程不动 游戏 反作弊 加速器 白名单和系统核心永远安全 输入法和外设驱动请自己加白名单 只有自定义模式能自己选 竞技和极限强制开 常规强制关 默认关" } },
            { "gm.pausedl", new[]{ "暂停后台下载与传递优化" } },
            { "gm.pausedl.sub", new[]{ "Windows 更新和传递优化会在后台闷头收发 传递优化还会把你的机器当成局域网内其他电脑的更新源 上行被占满就直接体现为 ping 抬高 对局中停掉这两条 退出恢复 不改你系统里的更新设置 自定义才能自己选 竞技和极限强制开 常规强制关" } },
            { "gm.pausesvc", new[]{ "暂停搜索索引与预读服务" } },
            { "gm.pausesvc.sub", new[]{ "SysMain 和 WSearch 会在后台持续翻硬盘建索引 机械盘上磁头一响帧数就抖 固态硬盘上几乎测不出差别 没必要开 停服务本身要几秒 所以挪到对局稳定 20 秒后才做 退出恢复 自定义才能自己选 极限强制开 竞技和常规强制关" } },
            { "gm.wlanguard", new[]{ "对局期间抑制无线后台扫描" } },
            { "gm.wlanguard.sub", new[]{ "系统每隔几十秒会扫一遍全部信道找可用网络 扫描那一瞬间网卡必须离开你正连着的频道 数据包只能排队等它回来 无线玩家周期性的 ping 突刺多半来自这里 副作用是对局中不会自动发现新 Wi-Fi 有线和无无线网卡的机器完全无感 退出恢复" } },
            { "gm.svcyield", new[]{ "系统服务核心让路" } },
            { "gm.svcyield.sub", new[]{ "遥测 诊断 错误上报 打印这类服务跑在共享宿主进程里 常规压制够不着它们 这项把整个宿主进程引到后台核心上 只挪位置不停服务 功能一切照常 一个宿主里只要混进白名单内的服务就整个不动 免得误伤 退出对局恢复 Pavise 意外退出下次启动自动还原 自定义才能自己选 极限强制开 竞技和常规强制关" } },
            { "set.autostart", new[]{ "开机自启" } },
            { "set.autostart.n", new[]{ "走管理员计划任务 开机不会弹 UAC 确认框" } },
            { "set.autohide", new[]{ "检测到游戏后自动收起窗口" } },
            { "set.autohide.n", new[]{ "检测到游戏 10 秒后窗口自动缩回托盘 每局只收一次 之后你再打开就不会又被收走" } },
            { "set.hint", new[]{ "这里只放应用自己的偏好和维护工具 显卡相关在显卡页 改动系统的开关在系统环境页" } },
            { "sec.pergame", new[]{ "逐游戏 对局开始时下发 结束后还原" } },
            { "sec.app", new[]{ "应用自身" } },
            { "dlg.ok", new[]{ "知道了" } },
            { "dlg.confirm", new[]{ "确定" } },
            { "dlg.cancel", new[]{ "取消" } },
            { "dlg.tag.info", new[]{ "提示" } },
            { "dlg.tag.warn", new[]{ "注意" } },
            { "dlg.tag.danger", new[]{ "警告" } },
            { "dlg.tag.done", new[]{ "完成" } },
            { "sec.maint", new[]{ "维护" } },
            { "nav.graphics", new[]{ "显卡" } },
            { "nav.env", new[]{ "系统环境" } },
            { "nav.audit", new[]{ "系统体检" } },
            { "contact.title", new[]{ "反馈与交流" } },
            { "contact.sub", new[]{ "遇到 Bug 想提功能需求 或者只是想聊聊 都可以直接找到我" } },
            { "contact.wechat", new[]{ "作者微信 功能需求和 BUG 反馈" } },
            { "contact.qq", new[]{ "QQ 一群" } },
            { "contact.qq2", new[]{ "QQ 二群" } },
            { "contact.qq3", new[]{ "QQ 三群" } },
            { "contact.douyin", new[]{ "作者抖音号" } },
            { "contact.pan", new[]{ "官方网盘 提取码 {0}" } },
            { "contact.pan.value", new[]{ "百度网盘" } },
            { "contact.open", new[]{ "打开" } },
            { "contact.update", new[]{ "版本更新" } },
            { "contact.update.check", new[]{ "检查更新" } },
            { "contact.copy", new[]{ "复制" } },
            { "contact.copied", new[]{ "已复制" } },
            { "contact.copyfail", new[]{ "复制失败" } },
            { "contact.free.n", new[]{ "最新版和源码更新永远在微信群 QQ 群免费提供 花钱买到的是被骗了 去要求退款" } },
            { "contact.close", new[]{ "关闭" } },
            { "contact.open.title", new[]{ "反馈与交流" } },
            { "nav.hardware", new[]{ "硬件与系统" } },
            { "audit.sub", new[]{ "只查不改 看这台机器什么能用 什么已经开了" } },
            { "audit.start", new[]{ "开始体检" } },
            { "audit.idle.title", new[]{ "还没有体检结果" } },
            { "audit.idle.hint", new[]{ "检测约需 4 秒 期间只读取不改动任何设置" } },
            { "audit.phase.capability", new[]{ "正在读取本机写入能力" } },
            { "audit.phase.measure", new[]{ "正在实测中断分布和整机负载" } },
            { "audit.phase.persistent", new[]{ "正在读取持久系统设置" } },
            { "audit.phase.verdict", new[]{ "正在汇总结论" } },
            { "audit.phase.done", new[]{ "完成" } },
            { "audit.nv.summary", new[]{ "{0} 项写入生效 共 {1} 项" } },
            { "audit.rerun", new[]{ "重新体检 3 秒" } },
            { "audit.precise", new[]{ "精确测量 30 秒" } },
            { "audit.nvprobe", new[]{ "NVIDIA 写入实测" } },
            { "audit.failed", new[]{ "体检失败 接口不可用" } },
            { "audit.nv.probing", new[]{ "正在实际写一个测试值再读回来核对" } },
            { "audit.nv.unavailable", new[]{ "本机没有 NVIDIA 驱动接口" } },
            { "audit.nv.failed", new[]{ "写入实测失败" } },
            { "audit.nv.result", new[]{ "写入实测" } },
            { "audit.sec.capability", new[]{ "写入能力 这些功能在本机能不能用" } },
            { "audit.sec.machine", new[]{ "本机实测 这台机器的实际情况" } },
            { "audit.sec.persistent", new[]{ "持久系统设置 重启生效 卸载后保留" } },
            { "audit.sec.verdicts", new[]{ "结论清单 每条都标注依据" } },
            { "audit.evidence", new[]{ "依据" } },
            { "audit.footer", new[]{ "依据等级 本机实测是在这台机器上测过 台架实测是合成负载配对实验 机制明确是原理清楚但没有量化数据 未验证是没有测过" } },
            { "v16.graphics.sub", new[]{ "显卡相关的开关 逐游戏的项只在打游戏时生效 退出自动还原" } },
            { "v16.env.sub", new[]{ "这一页动的是系统底层 都要重启才生效 卸载 Pavise 也不会自动改回来 想恢复请先在这里关掉" } },
            { "v17.log.sub", new[]{ "最近 220 行 切到本页自动刷新 每局结束的时长 压制数量和成效也记在这里" } },
            { "sec.env.kernel", new[]{ "内核与驱动 需重启 改动不随 Pavise 卸载消失" } },
            { "btn.clean", new[]{ "清理" } },
            { "btn.wipe", new[]{ "清除全部配置" } },
            { "set.about", new[]{ "Pavise {0} {1} 本地配置与用户白名单" } },

            { "set.hags", new[]{ "GPU 硬件加速调度 HAGS" } },
            { "set.hags.n", new[]{ "把显存分配和任务排期从系统交给显卡自己的调度器管 少一层中转 部分帧生成功能必须开它才可用 但它对帧数的影响因显卡代次 驱动版本和游戏而异 有的机器上反而掉帧 没有普适答案 建议开关各打一局自己对比 重启生效" } },
            { "hags.reboot", new[]{ "已写入 HAGS 设置 重启电脑后生效" } },
            { "set.irqaffinity", new[]{ "显卡中断亲和 绑定游戏核心" } },
            { "set.irqaffinity.n", new[]{ "显卡每完成一帧都要打断 CPU 通知一次 这个打断落在哪个核由系统随机决定 如果落在游戏线程之外的核上 数据就要跨核搬一次 缓存也白热 这项把它固定到游戏正在用的核上 划不出明确的游戏核心时退回让系统就近处理 收益量级不大 属于锦上添花 需要重启电脑或重启显卡设备才生效 可恢复" } },
            { "irqaffinity.igpuonly", new[]{ "本机只有核显 没有可引导的独立显卡中断 此项跳过" } },
            { "irqaffinity.reboot", new[]{ "已写入中断亲和设置 重启该设备或重启电脑后生效" } },
            { "set.vbs", new[]{ "关掉虚拟化安全 VBS" } },
            { "vbs.state.on", new[]{ "VBS 开着 关闭会降低安全性 帧数变化因机器而异 请自己对比" } },
            { "vbs.state.off", new[]{ "VBS 没在跑 本机已经没有这项开销" } },
            { "vbs.state.pending", new[]{ "已设为关闭 重启电脑后生效" } },
            { "vbs.state.unknown", new[]{ "状态未知 查不到 WMI" } },
            { "vbs.warn", new[]{ "关闭 VBS 和内存完整性 并停掉虚拟化底层\r\n\r\n系统安全性会下降 WSL2 Docker Hyper-V 沙盒会用不了 帧数提升因机器而异 自己前后对比\r\n\r\n重启后生效 将来恢复也要再重启一次" } },
            { "vbs.needadmin", new[]{ "改 VBS 和 hypervisor 需要管理员权限 请以管理员身份运行 Pavise" } },
            { "vbs.done", new[]{ "已关闭 VBS 并停用 hypervisor\r\n重启电脑生效 重启后 WSL2 Docker Hyper-V 沙盒将无法使用 要恢复请回到这里关掉此开关再重启" } },
            { "vbs.restored", new[]{ "已恢复 VBS 和 hypervisor 启动类型改回原值\r\n重启电脑生效 之后 WSL2 Docker 等恢复可用" } },
            { "vbs.restorefail", new[]{ "还原没完全成功 bcdedit 可能失败了 原状态快照已保留 可以再试一次 详见日志" } },

            { "btn.shader", new[]{ "清理着色器缓存" } },
            { "set.shader.n", new[]{ "驱动更新后画面出花屏或卡顿可以清一次 清完每个游戏首次启动要重新编译 开头几分钟会更卡" } },
            { "shader.busy", new[]{ "正在清理" } },
            { "shader.confirm", new[]{ "清空 NVIDIA AMD Intel DirectX 的着色器缓存\r\n\r\n怀疑驱动更新后缓存坏了可以清一次 不保证清完就流畅\r\n\r\n清理前先退出游戏 之后每个游戏首次启动要重新编译 开头可能更卡" } },
            { "shader.freed", new[]{ "已清理着色器缓存 释放 {0}" } },
            { "shader.skip", new[]{ "{0} 个文件正被占用已跳过 关闭游戏后可以再清一次" } },
            { "shader.note", new[]{ "每个游戏下次启动都可能重新编译着色器 首次运行可能额外卡顿" } },

            { "tray.aclist", new[]{ "反作弊列表" } },
            { "tray.reset", new[]{ "恢复默认配置" } },
            { "tray.resetask", new[]{ "把所有开关 反作弊选择和白名单恢复为默认 游戏列表保留" } },
            { "tm.gpu", new[]{ "高性能 GPU 偏好" } },
            { "tm.dvr", new[]{ "关闭 Game DVR" } },
            { "tm.notif", new[]{ "游戏时免打扰" } },
            { "tm.plan", new[]{ "游戏时切换电源计划" } },
            { "tm.autostart", new[]{ "开机自启" } },

            { "about.desc", new[]{ "把系统资源让给游戏的 Windows 工具" } },
            { "about.author", new[]{ "作者" } },
            { "about.repo", new[]{ "源码仓库" } },
            { "about.lic", new[]{ "许可协议" } },
            { "about.lic.value", new[]{ "Pavise 许可协议 禁止销售" } },
            { "about.wechat", new[]{ "微信" } },
            { "about.contact.hint", new[]{ "反馈 Bug 提新功能建议或者交流使用问题 可以加作者微信 也欢迎在 GitHub 提 Issue" } },
            { "btn.checkupd", new[]{ "检查更新" } },
            { "btn.download", new[]{ "前往下载" } },
            { "upd.checking", new[]{ "正在检查更新" } },
            { "upd.latest", new[]{ "已是最新版本 {0}" } },
            { "upd.newver", new[]{ "发现新版本 {0} 当前 {1} 点前往下载获取" } },
            { "upd.route", new[]{ "线路 {0}" } },
            { "upd.fail", new[]{ "检查版本更新失败 用反馈与交流里的官方网盘或群里拿最新版" } },
            { "bal.update", new[]{ "发现新版本 {0} 打开面板的关于页查看" } },

            { "dlg.pickproc", new[]{ "选择进程" } },
            { "btn.add", new[]{ "添加" } },
            { "btn.cancel", new[]{ "取消" } },
            { "dlg.bgsvc", new[]{ "后台服务" } },
            { "ofd.game", new[]{ "选择游戏 EXE 或 Windows 快捷方式" } },
            { "ofd.filter", new[]{ "游戏程序或快捷方式 (*.exe;*.lnk;*.url)|*.exe;*.lnk;*.url|程序 (*.exe)|*.exe|快捷方式 (*.lnk;*.url)|*.lnk;*.url" } },
            { "pick.busy", new[]{ "正在统计资源占用" } },
            { "pick.count", new[]{ "共 {0} 个可执行程序 同路径实例合并显示" } },
            { "msg.taskfail", new[]{ "计划任务操作失败 需要管理员权限运行 Pavise" } },

            { "tray.open", new[]{ "打开面板" } },
            { "btn.panic", new[]{ "一键恢复已记录项" } },
            { "tray.exit", new[]{ "退出" } },
            { "tray.active", new[]{ "Pavise 守护中 {0}" } },
            { "tray.idle", new[]{ "Pavise 待命 未检测到游戏" } },
            { "tray.armed", new[]{ "Pavise 已就位 {0} 进对局自动接管" } },
            { "tray.noelev", new[]{ "Pavise 未提权 压制类功能无效" } },
            { "bal.noelev", new[]{ "当前不是管理员运行 压制类功能不会生效" } },
            { "panic.done", new[]{ "能确认的改动都已还原 电源和调度交还给系统\r\n游戏还开着的话几秒后会重新接管 想彻底停用就关掉游戏模式和反作弊压制" } },
            { "panic.timeout", new[]{ "还有一部分没确认还原完 Pavise 会继续自动重试 想彻底停用就关掉游戏模式和反作弊压制" } },
            { "panic.failedcount", new[]{ "未确认完成 {0} 项 共 {1} 项" } },
            { "rep.done", new[]{ "{0} 本局 {1} 压制 {2} 个后台进程 它们合计用了 {3} CPU" } },
            { "rep.top", new[]{ " · 最高 {0} {1}" } },
            { "rep.pavise.cpu", new[]{ " · Pavise 自身平均 CPU {0}%" } },
            { "rep.gputhrottle", new[]{ " · 显卡受限 {0}" } },

            { "lolq.err.noinput", new[]{ "未提供英雄联盟目录" } },
            { "lolq.err.badformat", new[]{ "英雄联盟目录格式无效" } },
            { "lolq.err.notroot", new[]{ "目录不是有效的国服英雄联盟安装根目录" } },
            { "lolq.err.enumproc", new[]{ "无法枚举系统进程" } },
            { "lolq.proc.unknown", new[]{ "未知进程" } },
            { "lolq.err.clientrunning", new[]{ "检测到运行中的客户端 {0}" } },
            { "lolq.item.notdir", new[]{ "目标不是目录 没处理" } },
            { "lolq.item.vanished", new[]{ "源目录在执行前变了" } },
            { "lolq.err.srcreparse", new[]{ "目标路径包含重解析点" } },
            { "lolq.item.deleted", new[]{ "已删除" } },
            { "lolq.item.deletefail", new[]{ "删除失败 {0}" } },
            { "lolq.err.deleteincomplete", new[]{ "目录没能完全删除 可能还被占用" } },
            { "lolq.msg.deldone", new[]{ "已删除英雄联盟附加层" } },
            { "lolq.msg.delpartial", new[]{ "删除只完成了一部分 关掉占用后重试" } },
            { "lolq.msg.delnone", new[]{ "没删除任何内容" } },
            { "lolq.err.rootunresolved", new[]{ "安装目录形状暂时确认不了 客户端可能正在更新" } },
            { "lolq.err.closefirst", new[]{ "先关掉英雄联盟和 WeGame {0}" } },
            { "lolq.err.nocandidate", new[]{ "没检测到可删除的附加层目录" } },
            { "lolq.err.generic", new[]{ "操作失败" } },
            { "lolq.err.candnotdir", new[]{ "候选路径不是目录" } },
            { "lolq.err.candreparse", new[]{ "候选目录是重解析点" } },
            { "lolq.err.scanfail", new[]{ "扫描不完整 {0}" } },
            { "lolq.err.filereparse", new[]{ "目录包含文件重解析点 {0}" } },
            { "lolq.err.readfile", new[]{ "读不到文件信息 {0}" } },
            { "lolq.err.dirreparse", new[]{ "目录包含子目录重解析点 {0}" } },
            { "lolq.err.readdir", new[]{ "读不到目录信息 {0}" } },
            { "lolq.err.outsideroot", new[]{ "路径超出英雄联盟目录" } },
            { "lolq.err.outsiderootr", new[]{ "目标路径超出英雄联盟目录" } },
            { "lolq.err.pathreparse", new[]{ "目标路径包含重解析点" } },
            { "lolq.err.pathinvalid", new[]{ "目标路径无效" } },

            { "ac.ace.n", new[]{ "ACE 反作弊专家 腾讯" } },
            { "ac.ace.d", new[]{ "英雄联盟国服 无畏契约国服 三角洲行动 CF 等" } },
            { "ac.tp.n", new[]{ "TenProtect TP 腾讯" } },
            { "ac.tp.d", new[]{ "ACE 前身 穿越火线等老游戏仍在用" } },
            { "ac.vanguard.n", new[]{ "Vanguard Riot" } },
            { "ac.vanguard.d", new[]{ "无畏契约 英雄联盟 vgk 是内核驱动压不动" } },
            { "ac.eac.n", new[]{ "EasyAntiCheat Epic" } },
            { "ac.eac.d", new[]{ "俗称小蓝熊 Apex 堡垒之夜 永劫无间 幻兽帕鲁等" } },
            { "ac.battleye.n", new[]{ "BattlEye" } },
            { "ac.battleye.d", new[]{ "PUBG 彩虹六号 DayZ 逃离塔科夫 BEDaisy 是驱动" } },
            { "ac.eaac.n", new[]{ "EA Javelin EA 反作弊" } },
            { "ac.eaac.d", new[]{ "战地 2042 战地 6 FC 等 EA 游戏 另有内核驱动" } },
            { "ac.gameguard.n", new[]{ "nProtect GameGuard" } },
            { "ac.gameguard.d", new[]{ "DNF 等部分韩系网游" } },
            { "ac.faceit.n", new[]{ "FACEIT 反作弊" } },
            { "ac.faceit.d", new[]{ "CS2 第三方竞技平台" } },
            { "ac.neac.n", new[]{ "NEAC 反作弊 网易" } },
            { "ac.neac.d", new[]{ "部分网易游戏 另有内核组件" } },
        };

        public static void Init()
        {
            Cur = 0;
        }

        public static void Set(int i)
        {
            Cur = 0;
            Settings.SaveStr("Lang", "zh");
        }

#if PAVISE_SELFTEST
        internal static List<string> AllKeys()
        {
            var keys = new List<string>();
            foreach (var kv in M) keys.Add(kv.Key);
            return keys;
        }

        internal static string[] Row(string key)
        {
            string[] a;
            return M.TryGetValue(key, out a) ? a : null;
        }
#endif

        public static string T(string key)
        {
            string[] a;
            if (M.TryGetValue(key, out a)) return a[Cur < a.Length ? Cur : 0];
            return key;
        }

        public static string F(string key, params object[] args) { return string.Format(T(key), args); }

        public static bool HasKey(string key) { return key != null && M.ContainsKey(key); }
    }

}
