// @author bdth 2074055628@qq.com
// 文件用途 集中维护界面多语言文本

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.IO;
using System.Net;
using System.Runtime.InteropServices;
using System.Threading;
using System.Windows.Forms;
using Microsoft.Win32;

namespace PaviseApp
{
    internal static class Lang
    {
        public static int Cur;

        private static readonly Dictionary<string, string[]> M = new Dictionary<string, string[]>
        {
            { "nav.tame", new[]{ "反作弊" } },
            { "nav.white", new[]{ "白名单" } },
            { "nav.log", new[]{ "日志" } },
            { "nav.set", new[]{ "设置" } },
            { "nav.about", new[]{ "关于" } },
            { "nav.overview", new[]{ "概览" } },
            { "nav.library", new[]{ "游戏库" } },
            { "nav.policy", new[]{ "优化策略" } },
            { "nav.column", new[]{ "游戏专栏" } },
            { "search.name", new[]{ "搜索设置" } },
            { "search.hint", new[]{ "搜索各页面的设置和开关" } },
            { "search.sub", new[]{ "输入关键字跨页面匹配，回车直达对应设置。" } },
            { "search.empty", new[]{ "没有匹配的设置" } },
            { "v15.about.identity", new[]{ "Windows 性能守护" } },
            { "notes.title", new[]{ "版本说明" } },
            { "notes.sub", new[]{ "当前安装版本 {0}" } },
            { "notes.current", new[]{ "当前版本" } },
            { "notes.open", new[]{ "查看版本说明" } },
            { "notes.online", new[]{ "在 GitHub 查看全部" } },
            { "notes.close", new[]{ "关闭" } },
            { "v15.about.update", new[]{ "版本更新" } },
            { "v15.about.update.sub", new[]{ "仅读取版本号，不上传设备数据。直连失败时自动切换至国内镜像线路。" } },
            { "set.wipe.title", new[]{ "清除全部配置" } },
            { "set.wipe.desc", new[]{ "删除游戏库、白名单、开关设置和日志。执行前先还原已修改的系统项，任意一项还原失败则不删除任何文件。清除完成后自动退出。适用于升级后出现异常卡顿的排查。" } },
            { "wipe.confirm", new[]{ "确认清除 Pavise 的全部配置？\r\n\r\n游戏库、白名单、开关设置和日志将被删除，且无法恢复。\r\n\r\n执行前先还原 Pavise 修改过的系统项，还原失败则不删除任何文件。\r\n\r\n清除完成后 Pavise 自动退出，下次启动为初始状态。" } },
            { "wipe.ingame", new[]{ "对局进行中，请先退出游戏再清除配置。" } },
            { "wipe.done", new[]{ "配置已清除，删除 {0} 个文件，系统改动已还原。\r\n\r\n确定后 Pavise 退出，下次启动为初始状态。" } },
            { "wipe.failed", new[]{ "已中止，未删除任何文件。\r\n\r\n以下项未能还原：{0}\r\n\r\n处理后请重试。" } },
            { "v15.restore.title", new[]{ "恢复全部系统改动" } },
            { "v15.restore.desc", new[]{ "将 Pavise 写入的注册表项、服务状态和电源计划一次性还原为原值，配置、游戏库和白名单予以保留，不等同于重置。游戏仍在运行时，守护会在数秒后重新接管；需要完全停止请先关闭总开关或退出游戏。" } },
            { "mode.source.global", new[]{ "全局默认" } },
            { "mode.source.game", new[]{ "来自 {0} 的独立配置" } },
            { "lib.column.tag", new[]{ "专栏" } },
            { "col.sub", new[]{ "面向单个游戏的深度整合 通用优化项在游戏库的独立配置里逐游戏覆盖" } },
            { "col.tab.lol", new[]{ "英雄联盟" } },
            { "col.tab.lol.sub", new[]{ "国服 WeGame 链路" } },
            { "col.hero.title", new[]{ "英雄联盟 极限链路" } },
            { "col.hero.sub", new[]{ "不注入 不改内存 不触碰游戏核心文件 WeGame 只负责认证与拉起 大厅就绪后退出附加进程 对局中关闭客户端界面 赛后自动回显" } },
            { "col.hero.freed", new[]{ "本次累计释放" } },
            { "col.hero.killed", new[]{ "累计终止 {0} 个进程" } },
            { "col.state.off", new[]{ "专栏已停用" } },
            { "col.state.scanning", new[]{ "正在扫描安装目录" } },
            { "col.state.headless", new[]{ "对局无头运行中" } },
            { "col.state.linked", new[]{ "链路已接管" } },
            { "col.state.wait", new[]{ "等待客户端" } },
            { "col.sec.link", new[]{ "实时链路状态" } },
            { "col.sec.protocol", new[]{ "自动协议" } },
            { "col.sec.cmd", new[]{ "手动指令" } },
            { "col.sec.addon", new[]{ "附加层清理" } },
            { "col.cell.install", new[]{ "客户端安装" } },
            { "col.cell.lcu", new[]{ "LCU 会话" } },
            { "col.cell.phase", new[]{ "游戏阶段" } },
            { "col.install.found", new[]{ "已定位" } },
            { "col.install.none", new[]{ "未发现" } },
            { "col.install.wait", new[]{ "等待自动扫描" } },
            { "col.lcu.on", new[]{ "已连接" } },
            { "col.lcu.off", new[]{ "未连接" } },
            { "col.lcu.client", new[]{ "LeagueClient 后端在线" } },
            { "col.client.off", new[]{ "客户端未运行" } },
            { "col.game.on", new[]{ "游戏进程在线" } },
            { "col.game.off", new[]{ "未进入对局" } },
            { "col.wegame.sub", new[]{ "大厅确认后精确退出" } },
            { "col.cross.sub", new[]{ "AI 教练 录制 覆盖层" } },
            { "col.ux.closed", new[]{ "已关闭" } },
            { "col.ux.restore", new[]{ "赛后自动回显" } },
            { "col.ux.visible", new[]{ "大厅界面可见" } },
            { "col.proc.exit", new[]{ "已退出" } },
            { "col.proc.none", new[]{ "未运行" } },
            { "col.proc.count", new[]{ "{0} 个进程" } },
            { "col.phase.ingame", new[]{ "对局中" } },
            { "col.phase.champselect", new[]{ "英雄选择" } },
            { "col.phase.matchmaking", new[]{ "匹配中" } },
            { "col.phase.readycheck", new[]{ "等待接受" } },
            { "col.phase.stats", new[]{ "结算中" } },
            { "col.phase.lobby", new[]{ "组队大厅" } },
            { "col.phase.idle", new[]{ "大厅待命" } },
            { "col.cleanup", new[]{ "WeGame 借壳启动" } },
            { "col.cleanup.sub", new[]{ "允许正常登录与启动 LCU 确认大厅可用后 精确退出 WeGame Cross 与腾讯附加进程" } },
            { "col.headless", new[]{ "对局真无头" } },
            { "col.headless.sub", new[]{ "进入对局后用客户端原生接口关闭大厅界面 游戏结束由守护链自动拉起并回显" } },
            { "col.proto.on", new[]{ "自动" } },
            { "col.proto.off", new[]{ "关闭" } },
            { "col.btn.launch", new[]{ "启动 WeGame" } },
            { "col.btn.clean", new[]{ "立即净化" } },
            { "col.btn.restore", new[]{ "恢复客户端界面" } },
            { "col.btn.delete", new[]{ "删除附加层" } },
            { "col.busy.launch", new[]{ "正在启动 WeGame" } },
            { "col.busy.clean", new[]{ "正在执行精准净化" } },
            { "col.busy.restore", new[]{ "正在恢复客户端界面" } },
            { "col.ready", new[]{ "READY // 等待指令" } },
            { "col.addon.title", new[]{ "附加层直接删除" } },
            { "col.addon.sub", new[]{ "直接删除 AI 教练 iCreate 录制等附加层 客户端更新会重新下载 无需保留副本" } },
            { "col.addon.locked", new[]{ "客户端运行中 文件操作已锁定" } },
            { "col.addon.busy", new[]{ "文件操作进行中" } },
            { "col.addon.blocked", new[]{ "检测到占用进程 请完全退出客户端" } },
            { "col.addon.ready", new[]{ "可删除 {0} 项 共 {1}" } },
            { "col.addon.clean", new[]{ "未发现可删除的附加层" } },
            { "col.addon.deleting", new[]{ "正在删除附加层" } },
            { "col.addon.confirm", new[]{ "将直接删除识别出的英雄联盟附加层目录 AI 教练 iCreate 录制等\r\n\r\n此操作不可恢复 客户端更新或修复时会重新下载这些组件 游戏本体 登录链路和更新器不在删除范围\r\n\r\n请确认英雄联盟与 WeGame 已完全退出" } },
            { "lol.act.waitclient", new[]{ "等待英雄联盟客户端" } },
            { "lol.act.waitinstall", new[]{ "等待英雄联盟安装目录" } },
            { "lol.act.disabled", new[]{ "英雄联盟专栏已停用" } },
            { "lol.act.cleaned", new[]{ "已净化 {0} 个附加进程" } },
            { "lol.act.cleanidle", new[]{ "运行环境已净化" } },
            { "lol.act.recovering", new[]{ "净化完成 正在用 WeGame 恢复登录链" } },
            { "lol.act.headless", new[]{ "对局真无头已启用" } },
            { "lol.act.restored", new[]{ "英雄联盟大厅界面已恢复" } },
            { "lol.act.cleanupcircuit", new[]{ "附加进程反复重生 本局已暂停自动净化" } },
            { "lol.act.uxcircuit", new[]{ "大厅进程反复重启 本局已停用无头模式" } },
            { "lol.act.wegamestarted", new[]{ "WeGame 已启动" } },
            { "lol.act.wegamestarting", new[]{ "正在等待 WeGame 就绪" } },
            { "lol.act.wegamerunning", new[]{ "WeGame 已在运行 无需重复启动" } },
            { "lol.err.wegamenostart", new[]{ "WeGame 未能在预期时间内启动" } },
            { "lol.btn.wegamerunning", new[]{ "WeGame 运行中" } },
            { "lol.err.noinstall", new[]{ "未找到英雄联盟安装目录" } },
            { "lol.err.notready", new[]{ "英雄联盟登录会话尚未就绪" } },
            { "lol.err.nosession", new[]{ "无法取得本机英雄联盟恢复会话" } },
            { "lol.err.sessionlost", new[]{ "净化后英雄联盟登录会话失去响应" } },
            { "lol.err.killux", new[]{ "英雄联盟大厅界面收起失败" } },
            { "lol.err.gameidentity", new[]{ "无法确认本局游戏进程身份 已取消无头操作" } },
            { "lol.err.lease", new[]{ "无法安全写入本局恢复租约 已取消无头操作" } },
            { "lol.err.watchdog", new[]{ "独立恢复器未确认进入守护 已取消无头操作" } },
            { "lol.err.restore", new[]{ "英雄联盟大厅界面恢复失败" } },
            { "lol.err.restorepending", new[]{ "英雄联盟大厅界面恢复失败 独立恢复器将继续接管" } },
            { "lol.err.leaseclear", new[]{ "英雄联盟大厅已显示 恢复租约清理失败 将继续重试" } },
            { "lol.err.uxcircuitrestore", new[]{ "反复重启保护已触发 大厅界面显示失败" } },
            { "lol.err.cycle", new[]{ "英雄联盟运行时监控发生异常" } },
            { "lol.err.nowegame", new[]{ "未找到 WeGame" } },
            { "lol.err.wegamestart", new[]{ "WeGame 启动失败" } },
            { "lol.scan.cancel", new[]{ "取消扫描" } },
            { "lol.state.columnoff", new[]{ "专栏已停用 操作已锁定" } },
            { "lib.config", new[]{ "独立配置" } },
            { "lib.config.tag", new[]{ "独配 {0} 项" } },
            { "lib.rename", new[]{ "重命名" } },
            { "lib.rename.sub", new[]{ "给 {0} 换个显示名称 只影响列表和日志 识别不受影响" } },
            { "lib.store.readonly", new[]{ "游戏档案读取失败 本次运行为只读 这里的修改不会保存 档案已备份 重启 Pavise 重试" } },
            { "audit.fix", new[]{ "一键修复" } },
            { "audit.fixall", new[]{ "一键修复 {0} 项" } },
            { "audit.fixall.none", new[]{ "无待修项" } },
            { "audit.fix.revert", new[]{ "还原修复" } },
            { "cfg.title", new[]{ "{0} 的独立配置" } },
            { "cfg.back", new[]{ "返回游戏库" } },
            { "cfg.sub", new[]{ "各项默认跟随全局 改动只对这个游戏生效 立即保存 下一局应用 顶栏搜索可直达任意一项" } },
            { "cfg.count", new[]{ "已覆盖 {0} 项 点击定位" } },
            { "cfg.count.none", new[]{ "全部跟随全局" } },
            { "cfg.copy", new[]{ "套用到其它游戏" } },
            { "cfg.copy.sub", new[]{ "把 {0} 的这套覆盖复制给勾选的游戏 对方已有的覆盖会被替换" } },
            { "cfg.copy.none", new[]{ "库里没有其它游戏" } },
            { "cfg.copy.done", new[]{ "已套用到 {0} 个游戏" } },
            { "cfg.clear", new[]{ "全部清除" } },
            { "cfg.clear.confirm", new[]{ "清除 {0} 的全部 {1} 项覆盖\r\n\r\n之后该游戏完全跟随全局配置 此操作立即保存" } },
            { "cfg.frozen", new[]{ "对局进行中 本局配置已冻结 这里的修改下一局生效" } },
            { "cfg.follow", new[]{ "跟随全局" } },
            { "cfg.on", new[]{ "开" } },
            { "cfg.off", new[]{ "关" } },
            { "cfg.state.follow", new[]{ "全局 {0}" } },
            { "cfg.state.over", new[]{ "已覆盖 全局 {0}" } },
            { "cfg.group.mode", new[]{ "模式" } },
            { "cfg.group.bg", new[]{ "后台压制" } },
            { "cfg.group.core", new[]{ "核心" } },
            { "cfg.group.mempower", new[]{ "内存与电源" } },
            { "cfg.group.env", new[]{ "系统环境" } },
            { "cfg.group.gpu", new[]{ "显卡" } },
            { "cfg.mode", new[]{ "运行模式" } },
            { "cfg.mode.sub", new[]{ "给这个游戏固定一档模式 其余时间照全局走" } },
            { "cfg.strictcores", new[]{ "游戏核心分区" } },
            { "cfg.domainalt", new[]{ "核心分区换块" } },
            { "cfg.coremask", new[]{ "自定义核心" } },
            { "cfg.plan.sub", new[]{ "是否在这个游戏的对局中切换电源计划 切到哪个计划仍在策略页统一选" } },
            { "cfg.core.range.sub", new[]{ "跟随全局或给这个游戏固定核心范围 手动可以逐核指定 点应用才生效 对局结束自动还原" } },
            { "cfg.core.over", new[]{ "已覆盖 {0}" } },
            { "cfg.tab.bg", new[]{ "后台压制" } },
            { "cfg.tab.bg.sub", new[]{ "压制范围与游戏提优 逐项覆盖" } },
            { "cfg.sub.range", new[]{ "压制范围" } },
            { "cfg.tab.core", new[]{ "核心" } },
            { "cfg.tab.core.sub", new[]{ "这个游戏的核心范围与逐核分配" } },
            { "cfg.tab.env", new[]{ "系统环境" } },
            { "cfg.tab.env.sub", new[]{ "内存 电源与系统环境项" } },
            { "cfg.tab.gpu", new[]{ "显卡" } },
            { "cfg.tab.gpu.sub", new[]{ "驱动项 对局开始时按本游戏下发" } },
            { "cfg.sub.boost", new[]{ "游戏提优" } },
            { "cfg.sub.net", new[]{ "网络与更新" } },
            { "cfg.sub.presence", new[]{ "通知与在场" } },
            { "mode.global.title", new[]{ "全局默认模式" } },
            { "mode.global.sub", new[]{ "所有游戏统一使用" } },
            { "mode.policy.active", new[]{ "当前实际行为 {0}" } },
            { "mode.tray.current", new[]{ "当前模式 {0}，打开面板可切换" } },
            { "mode.pick.standard", new[]{ "后台先轻度压制，持续抢占资源的再加码，适合日常使用。" } },
            { "mode.pick.competitive", new[]{ "游戏之外可压制的立即全部压制，包含有窗口的浏览器和语音程序。" } },
            { "mode.pick.custom", new[]{ "完全按自定义开关执行，激进功能不会自动启用。" } },
            { "set.pqos", new[]{ "禁止前台无输入降级" } },
            { "set.pqos.n", new[]{ "系统在一段时间未收到键鼠输入后会判定用户离开，将前台程序降低一档服务质量。手柄游戏、过场动画和挂机场景本就没有键鼠活动，因此普遍受影响，表现为静置一段时间后帧数下降。本项在对局期间持续告知系统用户在场，退出游戏后自动解除。" } },
            { "set.awake", new[]{ "对局期间阻止息屏与睡眠" } },
            { "set.awake.n", new[]{ "成因同上：系统按键鼠活动判断用户是否在场，手柄游戏和长过场动画容易被判定为挂机，导致息屏甚至进入睡眠。本项在对局期间持续告知系统保持唤醒，退出游戏后自动解除，不修改电源计划中的超时设置。" } },
            { "v15.overview.sub", new[]{ "模式从右上角切换" } },
            { "v15.guard.state", new[]{ "PAVISE 守护状态" } },
            { "v15.effective.mode", new[]{ "实际生效模式" } },
            { "v15.master.short", new[]{ "识别到游戏后接管，退出后原样还原。" } },
            { "v15.tile.game", new[]{ "游戏资源" } },
            { "v15.tile.game.sub", new[]{ "仅对实际渲染画面的进程提速" } },
            { "v15.tile.background", new[]{ "后台边界" } },
            { "v15.tile.background.sub", new[]{ "系统组件、音频和白名单不受影响" } },
            { "v15.tile.environment", new[]{ "电源与调度" } },
            { "v15.tile.environment.sub", new[]{ "电源和调度随模式变化" } },
            { "v15.library.sub", new[]{ "可选择游戏目录中的任意 EXE。实际的渲染进程由前台全屏状态和 GPU 占用现场判定，选择偏差不影响识别结果。" } },
            { "v15.library.empty", new[]{ "尚未添加游戏\r\n建议先启动游戏并进入画面，再点击添加" } },
            { "v15.library.add", new[]{ "添加游戏" } },
            { "v15.library.drop", new[]{ "支持 EXE、LNK 和 Steam 快捷方式，也可直接拖入窗口。建议先启动游戏并进入画面再点击添加，正在渲染的进程会被自动标注并勾选。\r\n\r\n模拟器、云游戏等无法识别的程序，可选中条目后开启强制接管，进程启动即进入对局。" } },
            { "scan.title", new[]{ "添加游戏" } },
            { "scan.browse", new[]{ "浏览文件" } },
            { "scan.running.tag", new[]{ "运行中" } },
            { "scan.renderer.tag", new[]{ "正在渲染 GPU {0}%" } },
            { "set.light", new[]{ "亮色模式" } },
            { "set.light.n", new[]{ "切换为浅色界面，立即生效，默认为暗色。" } },
            { "scan.busy", new[]{ "正在读取各平台的安装记录" } },
            { "scan.busy.deep", new[]{ "正在遍历所选目录，目录较大时耗时较长" } },
            { "scan.count", new[]{ "找到 {0} 个，其中 {1} 个尚未加入" } },
            { "scan.stage.running", new[]{ "正在枚举有窗口的运行中程序" } },
            { "scan.stage.gpu", new[]{ "正在采样 GPU 以确定渲染进程，需要数秒" } },
            { "scan.stage.count", new[]{ "{0}   已找到 {1} 个" } },
            { "scan.live", new[]{ "列表每 3 秒自动刷新，新启动的程序会自动出现。" } },
            { "scan.none", new[]{ "未找到已安装的游戏，可尝试对指定盘符执行深度扫描。" } },
            { "scan.all", new[]{ "全选" } },
            { "scan.already", new[]{ "已在库中" } },
            { "scan.add.n", new[]{ "添加 {0} 个" } },
            { "scan.deep", new[]{ "深度扫描" } },
            { "scan.running.btn", new[]{ "正在运行" } },
            { "scan.pick.confirm", new[]{ "加入游戏库" } },
            { "scan.deep.pick", new[]{ "选择要遍历的盘符或目录，用于查找没有安装记录的免安装版游戏。" } },
            { "scan.added", new[]{ "已加入 {0} 个游戏" } },
            { "v15.library.running", new[]{ "运行中" } },
            { "v15.library.ready", new[]{ "已就绪" } },
            { "v15.library.force", new[]{ "强制接管" } },
            { "v15.library.force.on", new[]{ "强制接管 已开" } },
            { "v15.library.forced.tag", new[]{ "强制" } },
            { "v15.library.force.confirm", new[]{ "对 {0} 开启强制接管？\r\n\r\n开启后，只要该 EXE 的进程存在即判定为对局中，不再依据前台窗口和渲染画面，也不受内置非游戏名单限制。适用于模拟器、云游戏、老游戏以及没有独占全屏的程序。\r\n\r\n代价是对局不会自动结束。若指向常驻后台的程序，Pavise 将持续处于游戏模式，后台压制不解除、电源计划保持锁定，整机性能反而下降。\r\n\r\n请仅对需要手动启停的程序使用。" } },
            { "v15.library.force.noexe", new[]{ "该条目只记录了游戏目录，缺少明确的 EXE，无法开启强制接管。\r\n\r\n请删除后重新添加，并直接选择 EXE 文件。" } },
            { "v15.policy.sub", new[]{ "右上角显示当前模式与实际来源" } },
            { "v15.policy.mode.hint", new[]{ "自定义之外的模式会接管部分开关。被接管的项会标注强制开启或强制关闭，并锁定为不可修改。" } },
            { "v15.policy.core", new[]{ "全模式核心控制" } },
            { "policy.tab.core", new[]{ "核心控制" } },
            { "env.tab.kernel", new[]{ "内核调度" } },
            { "env.tab.device", new[]{ "设备链路" } },
            { "env.tab.input", new[]{ "键鼠链路" } },
            { "v17.env.kernel", new[]{ "显示、安全与调度内核项，多数需要重启" } },
            { "v17.env.device", new[]{ "中断亲和、设备电源与网络限流" } },
            { "v17.env.input", new[]{ "键鼠输入路径上的系统项" } },
            { "policy.tab.custom", new[]{ "预设细节" } },
            { "policy.tab.extras", new[]{ "会话附加" } },
            { "plan.pick.title", new[]{ "对局电源计划" } },
            { "power.name", new[]{ "对局电源计划" } },
            { "plan.fly.cur", new[]{ "当前系统计划 {0} 对局中切到所选 退出自动切回" } },
            { "plan.pick.off", new[]{ "不切换" } },
            { "plan.pick.managed", new[]{ "PG托管" } },
            { "plan.pick.local", new[]{ "本机" } },
            { "plan.pick.desc", new[]{ "退出游戏后自动切回。默认使用 Pavise 托管方案，首次对局自动创建，各项参数按本机处理器写入，名称带 PG 标签和本机签名，一键还原会连它删掉。选择本机已有计划时，Pavise 只负责切换，不修改该计划的任何参数。笔记本发热偏高时可改选平衡。" } },
            { "cpu.place.title", new[]{ "游戏核心范围" } },
            { "cpu.place.overridden", new[]{ "已被核心分配接管" } },
            { "policy.tab.cores", new[]{ "核心分配" } },
            { "v15.policy.cores", new[]{ "逐核指定游戏可用的逻辑核心" } },
            { "core.band.ccd", new[]{ "CCD {0}" } },
            { "core.band.ccd.cache", new[]{ "CCD {0} · 3D 缓存" } },
            { "core.tag.cache", new[]{ "缓存" } },
            { "core.preset.cache", new[]{ "仅缓存核" } },
            { "core.preset.ccd", new[]{ "CCD {0}" } },
            { "core.bar.spare", new[]{ "其余" } },
            { "core.band.perf", new[]{ "性能核" } },
            { "core.band.eff", new[]{ "能效核" } },
            { "core.band.all", new[]{ "处理器核心" } },
            { "core.band.meta.smt", new[]{ "{0} 物理核 / {1} 线程 · 带超线程" } },
            { "core.band.meta.solo", new[]{ "{0} 物理核 / {1} 线程" } },
            { "core.preset.all", new[]{ "全核" } },
            { "core.preset.physical", new[]{ "关超线程" } },
            { "core.preset.perf", new[]{ "仅性能核" } },
            { "core.preset.invert", new[]{ "反选" } },
            { "core.tag.exclusive", new[]{ "独占" } },
            { "core.tag.game", new[]{ "游戏" } },
            { "core.tag.bg", new[]{ "后台" } },
            { "core.role.game", new[]{ "游戏可用核心" } },
            { "core.role.count", new[]{ "{0} 线程 · {1} 个物理核" } },
            { "core.howto.game", new[]{ "点击核心分配给游戏，再次点击收回，也可使用快捷按钮批量选择。" } },
            { "core.guide.title", new[]{ "本页使用说明" } },
            { "core.guide.open", new[]{ "使用说明" } },
            { "core.guide.tag", new[]{ "PAVISE // CORE GUIDE" } },
            { "core.guide.s1.t", new[]{ "多数场景无需调整" } },
            { "core.guide.s1.d", new[]{ "建议保持默认的全核。系统调度器本就会将游戏线程置于性能核，由能效核承接后台。仅在确认游戏线程被分配到能效核并导致掉帧时，手动划分才有意义；划分不当会造成负优化。" } },
            { "core.guide.s2.t", new[]{ "核心数量的下限" } },
            { "core.guide.s2.d", new[]{ "现代游戏的渲染、物理、音频和网络各占用独立线程，核心过少会导致卡死。建议至少保留 8 个逻辑核心，少于 2 个时不允许应用。可使用上方的快捷按钮快速选择。" } },
            { "core.guide.s3.t", new[]{ "需点击应用才会下发" } },
            { "core.guide.s3.d", new[]{ "勾选后仅为待应用状态，上方计数会显示为待应用，须点击右侧的应用按钮才会下发。对局进行中点击应用立即生效，无需重启游戏。" } },
            { "core.guide.hy.t", new[]{ "本机为 Intel 混合架构" } },
            { "core.guide.hy.d", new[]{ "性能核运行游戏、能效核承接后台是 Windows 调度器的默认行为，无需手动划分。仅在任务管理器中观察到游戏线程大量落在能效核并伴随掉帧时，才建议改为仅性能核，代价是放弃能效核的算力，后台将挤占剩余核心。另外，12 至 14 代的能效核不带超线程，对其关闭超线程没有意义。" } },
            { "core.guide.x3d.t", new[]{ "本机为 AMD 双 CCD，其中一侧带 3D 缓存" } },
            { "core.guide.x3d.d", new[]{ "建议优先由 AMD 芯片组驱动和 Xbox Game Bar 判定游戏应使用的 CCD，已安装优化驱动的机器保持默认即可。仅在确认驱动未将游戏分配到大缓存 CCD 时，才手动选择缓存 CCD；少数依赖频率而非缓存的游戏可反向选择高频 CCD。切换后应观察 1% 最差帧，平均帧通常不会变化。" } },
            { "core.guide.ccd.t", new[]{ "本机为 AMD 多 CCD" } },
            { "core.guide.ccd.d", new[]{ "游戏线程分散在多块 CCD 时，跨 CCD 通信会带来额外开销，表现为帧时间毛刺。限定单块完整 CCD 可以避免该开销，代价是可用核心减半，线程数量需求高的游戏反而更卡。建议先使用全核，卡顿明显时再尝试单 CCD。不要用快捷按钮划出半块 CCD，该配置两侧收益均无法取得。" } },
            { "core.guide.smt.t", new[]{ "关闭超线程不等于提升" } },
            { "core.guide.smt.d", new[]{ "同一物理核的两个线程共用执行单元，关闭其一确实让剩余线程独占，但现代游戏普遍能利用多线程，减半线程数通常为净损失。仅极少数老游戏或有明确实测收益时才值得使用。快捷按钮中的关超线程用于该场景，不作为默认建议。" } },
            { "core.guide.judge.t", new[]{ "效果判定方式" } },
            { "core.guide.judge.d", new[]{ "应观察 1% 最差帧和帧时间毛刺，而非平均帧。核心划分改善的是卡顿而非帧率上限，平均帧通常不会变化。建议在同一场景、同一段路径下往返对比两次；调整后立即感到流畅多为主观错觉。" } },
            { "core.guide.s4.t", new[]{ "后台无需手动配置" } },
            { "core.guide.s4.d", new[]{ "被重压后台的收缩落点由算法跟随当前划分实时重算，不会与分配给游戏的核心重叠，也不会拆开一对超线程。本项没有需要手动设置的部分。" } },
            { "core.guide.note", new[]{ "以上配置仅在对局中下发给游戏进程，退出游戏后自动还原，不写入注册表也不修改系统设置。关闭 Pavise 后一切恢复原状。" } },
            { "cpu.place.manual", new[]{ "手动" } },
            { "core.bg.ok", new[]{ "后台 {0} 核 {1}" } },
            { "core.bg.landing", new[]{ "重压后台落点 核 {0}，共 {1} 核" } },
            { "core.bg.toofull", new[]{ "剩余核心不足 {0} 个，独占不生效" } },
            { "core.bg.allcores", new[]{ "不分区，后台按档位处理" } },
            { "core.land.squeezed", new[]{ "重压后台落点 核 {0} · 由 {1} 个核收缩至 {2} 个" } },
            { "core.land.plain", new[]{ "重压后台落点 核 {0}" } },
            { "core.land.narrow", new[]{ "重压后台落点 核 {0} · 已达下限，不再收缩" } },
            { "core.land.nowhole", new[]{ "重压后台落点 核 {0} · 均为超线程的另一半，不收缩" } },
            { "core.land.none", new[]{ "游戏核心已占满，重压后台没有可用核心" } },
            { "core.topo.line", new[]{ "{0} 物理核 · {1} 逻辑核 · 其中 {2} 个带超线程" } },
            { "core.topo.unknown", new[]{ "未知处理器" } },
            { "core.topo.default", new[]{ "未自定义" } },
            { "core.apply", new[]{ "应用" } },
            { "core.state.applied", new[]{ "已生效，游戏 {0} 核，覆盖 {1} 个物理核" } },
            { "core.state.dirty", new[]{ "待应用，游戏 {0} 核，覆盖 {1} 个物理核" } },
            { "core.state.few", new[]{ "至少需保留两个逻辑核心，否则游戏会卡死" } },
            { "core.state.scope", new[]{ "仅在对局中下发给游戏进程，退出游戏后自动还原，不写入注册表也不修改系统设置。关闭 Pavise 后一切恢复原状。" } },
            { "cpu.place.all", new[]{ "全核" } },
            { "cpu.place.ccd", new[]{ "单 CCD" } },
            { "cpu.place.performance", new[]{ "只用大核" } },
            { "cpu.place.partition", new[]{ "游戏分区" } },
            { "cpu.place.cache", new[]{ "缓存 CCD" } },
            { "cpu.place.freq", new[]{ "高频 CCD" } },
            { "cpu.place.pending", new[]{ "对局结束后生效" } },
            { "cpu.place.x3d.desc", new[]{ "建议保持默认的全核，由 AMD 驱动判定游戏使用哪一块。已安装 3D V-Cache 优化驱动的机器保持该档即可。怀疑驱动未将游戏分配到大缓存 CCD 时，再选择单 CCD；需要逐核指定请选择手动。所有模式均按此处设置执行。" } },
            { "cpu.place.x3d3.desc", new[]{ "建议保持默认的全核，由 AMD 驱动判定。已安装 3D V-Cache 优化驱动的机器保持该档即可。缓存 CCD 适用于绝大多数游戏，高频 CCD 仅对少数依赖频率的游戏有效。切换后应观察 1% 最差帧，平均帧通常不会变化。切换即时生效，对局中会等待对局结束。" } },
            { "cpu.place.ccd.desc", new[]{ "建议保持默认的全核。单 CCD 限定游戏只使用一块完整处理器 Die，可避免跨 CCD 通信开销，代价是可用核心减半，线程数量需求高的游戏在全核下更稳定。卡顿明显时再尝试单 CCD；需要逐核指定请选择手动。所有模式均按此处设置执行。" } },
            { "cpu.place.ccd3.desc", new[]{ "建议保持默认的全核。选定一块后游戏只使用该块，后台和中断归入另一块，可避免跨 CCD 通信开销，代价是可用核心减半。何者更优因机而异，两块均可尝试。切换后应观察 1% 最差帧，平均帧通常不会变化。切换即时生效，对局中会等待对局结束。" } },
            { "cpu.place.hybrid.desc", new[]{ "建议保持默认的全核。系统调度器本就将游戏线程置于 P 核、由 E 核承接后台，多数情况下即为最优。仅在确认游戏线程被分配到 E 核并导致掉帧时才选择只用大核，该配置会放弃 E 核的算力。需要逐核指定请选择手动。所有模式均按此处设置执行。" } },
            { "cpu.place.generic.desc", new[]{ "默认全核。游戏分区会保留若干核心给后台，游戏不占用这些核心，适用于后台程序较多、边挂载任务边游戏的机器；系统较为干净时保持全核即可。改善的是卡顿和 1% 最差帧，平均帧通常不会变化。需要逐核指定请选择手动。所有模式均按此处设置执行。" } },
            { "cpu.place.unavailable.desc", new[]{ "本机物理核心较少，划分后台核心的算力损失超过隔离收益，因此不提供游戏分区档。需要逐核指定请选择手动。所有模式均按此处设置执行。" } },
            { "v15.policy.custom", new[]{ "自定义预设细节" } },
            { "v15.policy.extras", new[]{ "会话附加动作，所有模式生效" } },
            { "v15.boost.sub", new[]{ "同时提升游戏进程的 CPU 优先级、IO 优先级和内存页优先级，并将其标记为显卡侧的高优先级客户端。目标仅限实际渲染画面的进程，启动器、游戏平台和更新器不会被误判为游戏。提优在对局中下发，退出后即还原。" } },
            { "v15.anticheat.sub", new[]{ "与游戏模式无关，仅作用于下列反作弊程序。" } },
            { "v14.master", new[]{ "Pavise 智能守护" } },
            { "preset.standard", new[]{ "常规" } },
            { "preset.competitive", new[]{ "竞技" } },
            { "preset.custom", new[]{ "自定义" } },
            { "sec.theme", new[]{ "模式主题色" } },
            { "theme.hint", new[]{ "为常规 / 竞技 / 自定义各挑一个强调色，「默认」块回到内置配色，切到该模式即时生效。" } },
            { "v14.cpu.topology", new[]{ "CPU 调度拓扑" } },
            { "v14.boost.status", new[]{ "游戏提权状态" } },
            { "v14.boost.disabled", new[]{ "游戏提优已关闭" } },
            { "v14.boost.wait", new[]{ "等待游戏画面输出" } },
            { "v14.boost.no.renderer", new[]{ "已识别启动器，等待游戏本体" } },
            { "v14.boost.applying", new[]{ "正在提速 {0}" } },
            { "v14.boost.verified", new[]{ "已生效 {0}\r\n提速已写入系统并通过回读确认" } },
            { "v14.boost.protected", new[]{ "{0} 受反作弊保护，优先级无法修改\r\n可在策略页开启后备提优，下次进入游戏由系统直接赋予高优先级，其余优化照常生效" } },
            { "v14.boost.protected.ifeo", new[]{ "{0} 受反作弊保护，后备提优已安排，下次进入游戏由系统直接赋予高优先级\r\n其余优化照常生效" } },
            { "v14.bg.master", new[]{ "后台压制 总开关" } },
            { "v14.bg.master.sub", new[]{ "控制是否调整后台程序的优先级、效率模式、IO 与内存页优先级。关闭后不会修改任何后台程序，下方相关开关随之全部失效。无论开关状态如何，游戏本体、反作弊、系统核心组件、其他用户账户下的进程以及白名单中的程序，任何时候都不在压制范围内。" } },
            { "v14.preset.forced.on", new[]{ "预设强制开" } },
            { "v14.preset.forced.off", new[]{ "预设强制关" } },
            { "v14.anticheat.boundary", new[]{ "反作弊仅在此处配置，不随游戏模式变化" } },
            { "v14.anticheat.master.sub", new[]{ "仅作用于下列反作弊程序，不会将游戏平台和登录器判定为反作弊。" } },
            { "v14.cpu.multigroup", new[]{ "多处理器组，CPU Sets 跨组调度，游戏核心范围可手动选择" } },
            { "v14.anticheat", new[]{ "反作弊专项" } },
            { "v14.cpu.hybrid", new[]{ "混合架构，默认全核，游戏核心范围可切换为只用大核或逐核手动指定" } },
            { "v14.cpu.x3d", new[]{ "非对称 L3（X3D），默认全核，可手动切换至大缓存 CCD" } },
            { "v14.cpu.generic", new[]{ "{0} 逻辑处理器，常规按需升级，竞技立即全力压制后台" } },
            { "detect.learned", new[]{ "命中已确认的渲染进程" } },
            { "detect.fullscreen", new[]{ "前台全屏画面" } },
            { "detect.window", new[]{ "所选 EXE 自带前台窗口" } },
            { "detect.gpu", new[]{ "GPU 3D 引擎主导 {0}%" } },
            { "detect.gpu.pending", new[]{ "窗口化候选，等待 GPU 证据确认" } },
            { "detect.forced", new[]{ "强制接管，进程存在即判定为对局" } },
            { "title.noelev", new[]{ "未提权，压制类功能无效" } },
            { "title.admin", new[]{ "管理员权限" } },
            { "title.guard", new[]{ "守护中 {0}" } },
            { "title.idle", new[]{ "待命" } },

            { "btn.browse", new[]{ "浏览 exe" } },
            { "btn.remove", new[]{ "移除选中" } },

            { "st.off", new[]{ "已关闭" } },
            { "st.mon", new[]{ "监控中，未检测到列表内的游戏" } },
            { "st.armed", new[]{ "已就位 {0}，进入对局画面自动接管" } },
            { "st.grace", new[]{ "{0} 已退出，剩余 {1} 秒宽限，后台已先行还原，重新进入游戏可无缝续接" } },
            { "st.active", new[]{ "激活中 {0}，已压制 {1} 个进程" } },
            { "st.boost", new[]{ "已提优 {0} {1}" } },
            { "st.hp", new[]{ "高性能电源" } },
            { "st.pr", new[]{ "电源就绪" } },

            { "tame.toggle", new[]{ "反作弊压制 总开关" } },
            { "set.nvmax", new[]{ "NVIDIA 电源模式 最高性能优先" } },
            { "set.nvmax.n", new[]{ "驱动默认按负载自适应调频，从低频升至满频需要一段时间，期间帧数不稳定。本项使显卡在对局期间保持高频，省去升频过程，代价是功耗和温度全程更高。散热能力不足的笔记本会更早触及温度墙，结果可能低于不开启。关闭后恢复原状。" } },
            { "set.nv.none", new[]{ "未检测到 NVIDIA 驱动，本项停用" } },
            { "set.nvfrl", new[]{ "NVIDIA 驱动级帧率上限" } },
            { "set.nvfrl.n", new[]{ "限制帧率后每帧间隔更均匀，观感比波动较大的高帧更稳定，显卡温度和功耗也更低。拖动滑块在 30 到 500 之间任意锁定上限，点击后滚轮可逐帧微调。「屏 3」取本机所有屏幕中最高的刷新率减 3，为 G-Sync 生效区间的上沿，超出后会退出可变刷新并出现撕裂或垂直同步；多屏且游戏在低刷新率屏上时建议改用固定数值。代价是帧率上限被锁定，跑分和追求高刷上限的场景不建议开启。选择关即恢复原状。" } },
            { "set.nvll", new[]{ "NVIDIA 低延迟" } },
            { "set.nvll.n", new[]{ "驱动默认允许 CPU 为显卡预排多帧，排队越多，从操作到画面呈现的间隔越长。「低延迟」将队列限制为一帧；「超低延迟 Ultra」在此之上让 CPU 恰好赶在显卡取帧前才提交，显卡满载时延迟进一步下降，NVIDIA 官方数据最多再降三成。两档都只对 DX9 与 DX11 游戏生效，DX12 和 Vulkan 由游戏自管队列；游戏内建 Reflex 时以 Reflex 为准。显卡未跑满时收益趋零。选择关即恢复原状。" } },
            { "nvll.on", new[]{ "低延迟" } },
            { "nvll.ultra", new[]{ "超低延迟 Ultra" } },
            { "set.nvsmooth", new[]{ "NVIDIA Smooth Motion 驱动插帧" } },
            { "set.nvsmooth.n", new[]{ "驱动级 AI 插帧，在两张真实画面之间推算一帧，帧率视觉上接近翻倍，不需要游戏支持 DLSS 帧生成。代价是输入延迟会增加约半帧到一帧，竞技对战游戏不要开启，适合单机大作追求观感。基础帧率低于 60 时插出的帧瑕疵明显，建议先把画质调到基础帧稳定再开。对 DX11、DX12 和 Vulkan 游戏生效。关闭后恢复原状。" } },
            { "set.nvsmooth.nogpu", new[]{ "需要 RTX 40 或 50 系显卡，本机显卡不支持驱动插帧" } },
            { "set.nvsmooth.old", new[]{ "驱动版本过低，需要 {0} 以上，升级后可用" } },
            { "set.nvshader", new[]{ "NVIDIA 着色器缓存无上限" } },
            { "set.nvshader.n", new[]{ "驱动默认限制着色器磁盘缓存的总大小，缓存装满后会淘汰旧游戏的编译产物，下次再玩时重新编译，表现为进图后一段时间的连续卡顿。本项对该游戏解除上限，编译过的着色器长期保留，代价是占用更多磁盘空间。虚幻 5 等着色器数量巨大的游戏收益最明显。关闭后恢复默认上限。" } },
            { "frl.off", new[]{ "关" } },
            { "frl.screen", new[]{ "屏 3" } },
            { "dlss.latest", new[]{ "最新" } },
            { "set.nvdlss", new[]{ "DLSS 换新算法" } },
            { "set.nvdlss.n", new[]{ "仅在游戏内已开启 DLSS 时有效。游戏内置的算法版本停留在发布时的状态，本项由驱动替换为当前最新版本，画面更清晰，拖影和锯齿更少，老游戏同样适用。少数游戏对版本有校验，替换后可能花屏或无法启动，遇到时选择关即恢复原状。" } },
            { "set.nvdlss.old", new[]{ "驱动版本过低，需要 566.14 以上，升级后可用" } },
            { "set.nvdlss.nogpu", new[]{ "本机显卡非 RTX，不具备 DLSS 超分能力，本项不可用。GTX 及更早型号均不支持。" } },
            { "set.nvrebar", new[]{ "ReBAR 强制开启" } },
            { "set.nvrebar.n", new[]{ "未启用 ReBAR 时，CPU 每次只能通过一个 256MB 的窗口访问显存，启用后可一次访问整块。NVIDIA 仅对经过自身测试的部分游戏默认开启，名单外一律关闭。本项对名单外的游戏也强制开启：部分游戏帧数有数个百分点的提升，个别游戏反而掉帧或花屏，无法预测，建议对同一游戏开关各测一局。前提是 BIOS 中同样需要开启。关闭后恢复原状。" } },
            { "set.nvrebar.det.on", new[]{ "本机已开启，窗口 {0}" } },
            { "set.nvrebar.det.off", new[]{ "本机未开启，窗口 {0}，需在 BIOS 中开启后才有效" } },
            { "set.nvansel", new[]{ "禁止 Ansel 注入游戏" } },
            { "set.nvansel.n", new[]{ "Ansel 是 NVIDIA 注入游戏进程的截图组件，需要在游戏内挂钩，既占用常驻开销，也是反作弊误报的常见来源。本项阻止其加载，代价是 NVIDIA 覆盖层中的照片模式不可用，游戏自带截图和录制不受影响。关闭后恢复原状。" } },
            { "set.nvbatt", new[]{ "禁用电池模式帧率限制" } },
            { "set.nvbatt.n", new[]{ "笔记本断开电源后，驱动会将游戏限制在 30 或 60 帧以节省电量，该行为没有提示，容易被误认为游戏卡顿。本项使插电与否均按完整性能运行，代价是电池消耗和发热明显增加。台式机没有此项开销。" } },
            { "sec.gfx.session", new[]{ "全局驱动项，游戏期间生效，退出后还原" } },
            { "v16.spec.cpu", new[]{ "处理器" } },
            { "v16.spec.gpu", new[]{ "显示适配器" } },
            { "v16.spec.mem", new[]{ "系统内存" } },
            { "v16.spec.hags", new[]{ "硬件加速 GPU 计划" } },
            { "v16.device.hags.on", new[]{ "已开启" } },
            { "v16.device.hags.off", new[]{ "已关闭" } },
            { "v16.device.hags.none", new[]{ "显卡或驱动不支持" } },
            { "v16.device.hags.unknown", new[]{ "无法读取状态" } },
            { "rep.log.none", new[]{ "日志为空" } },
            { "rep.clear.log", new[]{ "清除日志" } },
            { "rep.clear.ask", new[]{ "清空运行日志\r\n\r\nPavise.log 将被清空，已归档的 Pavise.log.old 不受影响。" } },
            { "gm.standby", new[]{ "内存吃紧时清理待机内存" } },
            { "gm.standby.sub", new[]{ "对局中持续监测可用内存，仅当可用物理内存低于 15% 才清理一次低优先级待机页，并带 45 秒冷却防止反复触发。只清系统判定最不可能再用的那部分缓存，不动整个待机列表，不丢弃有价值的文件缓存。8～16G 内存吃紧时能缓解帧时间抖动，内存充裕的机器几乎从不触发、零打扰。默认开启。" } },
            { "gm.pausewu", new[]{ "对局期间暂停 Windows 更新" } },
            { "gm.pausewu.sub", new[]{ "避免对局中途开始下载和安装，导致硬盘与 CPU 被大量占用并造成明显卡顿。暂停的是更新动作本身，不修改系统中的更新设置和策略，退出对局后自动恢复。" } },
            { "set.usbaffinity", new[]{ "USB 控制器中断避让" } },
            { "set.usbaffinity.n", new[]{ "4K、8K 高回报率鼠标每秒会中断 CPU 数千次。若这些中断落在游戏正在使用的核心上，渲染线程会被反复抢占，表现为快速移动视角时掉帧。本项将 USB 控制器的中断改投至专门承接中断的核心。默认关闭，仅建议 4K 以上回报率的鼠标开启；1000Hz 及以下的中断次数低一个数量级，开启基本没有收益，反而可能导致空闲后首次操作出现延迟。需要重启电脑或重新插拔设备后生效，可恢复。" } },
            { "usbaffinity.warn", new[]{ "本项会将键盘和鼠标所在的 USB 控制器中断绑定至固定核心。在核心数量较少的机器上，这些核心同时也是后台压制的落点，且空闲时会进入深度睡眠，中断需等待其唤醒。实机测试中出现过静置一段时间后首次点击明显延迟的情况。\n\n仅 4K、8K 高回报率鼠标值得承担该风险，1000Hz 及以下的鼠标开启基本没有收益。\n\n确认开启？出现问题请将此开关关闭。" } },
            { "set.pointerprec", new[]{ "关闭指针精度增强" } },
            { "set.pointerprec.n", new[]{ "系统默认启用一条鼠标加速曲线，移动越快，相同物理距离在屏幕上的位移越大。这不是延迟问题而是一致性问题，会导致肌肉记忆无法稳定对准，竞技射击类游戏通常将其关闭。使用 Raw Input 的游戏本就绕过该设置，关闭后仅影响桌面和未使用 Raw Input 的游戏。立即生效，可恢复。" } },
            { "set.gmguard", new[]{ "Windows 游戏模式守护" } },
            { "set.gmguard.n", new[]{ "游戏模式的实际作用是阻止对局中的驱动安装和重启提示，而非提升帧数。它常被旧版优化教程当作负优化关闭。本项将其恢复为开启状态，若本就开启则不做任何操作。立即生效，可恢复。" } },
            { "set.netthrottle", new[]{ "网络限流值校正" } },
            { "set.netthrottle.n", new[]{ "系统默认每毫秒最多处理 10 个非多媒体网络包，将其改为无限制是常见的教程做法，但实测反而抬高网络驱动的延迟，而游戏流量远达不到该上限。本项在当前值正常时不做任何操作，仅将被改动的值修复为默认。重启后生效。" } },
            { "netthrottle.ok", new[]{ "当前值 {0} 在正常范围内，无需校正" } },
            { "netthrottle.broken", new[]{ "当前值 {0} 超出有效范围，建议校正回系统默认值 10" } },
            { "set.clock", new[]{ "平台时钟校正" } },
            { "set.clock.n", new[]{ "在启动配置中强制 HPET 并关闭动态时钟是早期的提帧做法，在现代平台上为纯减益。系统默认使用的 TSC 单次读取仅需数纳秒，HPET 需经总线访问，慢数个数量级，而游戏每帧需多次读取时间。本项清除陈旧的覆盖配置，恢复由系统自行选择；启动配置本就干净时不做任何操作。重启后生效，可还原。" } },
            { "clock.ok", new[]{ "启动配置干净，无陈旧的时钟覆盖，无需校正" } },
            { "clock.repaired", new[]{ "已校正，启动配置恢复为系统默认计时" } },
            { "clock.broken", new[]{ "检测到陈旧覆盖 {0}，建议校正" } },
            { "netthrottle.absent", new[]{ "当前未设置该值，即为系统默认，无需校正" } },
            { "set.quantum", new[]{ "前台时间片校正" } },
            { "set.quantum.n", new[]{ "该值决定前台程序每次获得 CPU 后可连续运行的时长。旧版教程倾向于将其调大以让游戏多占用，实际结果是其他线程需等待更久才被调度，一旦游戏依赖这些线程，反而形成卡顿。系统默认值经过权衡，未被修改时不做任何操作，仅将被改动的值修复为默认。立即生效。" } },
            { "quantum.ok", new[]{ "当前已是系统默认，无需校正" } },
            { "quantum.broken", new[]{ "当前值 {0} 非系统默认，建议校正回默认值 2" } },
            { "quantum.absent", new[]{ "当前未设置该值，即为系统默认，无需校正" } },
            { "set.devpower", new[]{ "禁止网卡节能断电" } },
            { "set.devpower.n", new[]{ "系统在空闲一段时间后会对网卡断电以节省电量，再次产生流量时需先唤醒，该期间的数据包会被丢弃，表现为无征兆的单次卡顿并伴随掉线重连，笔记本无线网络上尤为明显。本项仅修改该设置，不涉及网卡的其他高级选项。立即生效，可恢复。" } },
            { "set.accesskeys", new[]{ "辅助功能按键拦截" } },
            { "set.accesskeys.n", new[]{ "筛选键按微软自身的定义即为让键盘忽略短促和重复的击键，开启状态相当于在输入路径上主动加入一段延迟，是键鼠环节中唯一能挽回两位数毫秒的软件项。多数用户是在游戏中长按 Shift 被提示框误开启的。本项清除筛选键、粘滞键和切换键的生效位及其触发热键，避免后续再次误开。无需管理员权限，无需重启。需要使用这些辅助功能的用户请勿开启。可还原。" } },
            { "set.windowedopt", new[]{ "窗口化游戏优化" } },
            { "windowedopt.oldos", new[]{ "这一项由 Windows 11 提供，本机系统版本不支持，开关已停用。" } },
            { "set.windowedopt.n", new[]{ "微软官方背书的降延迟机制，旧 DX10 DX11 游戏窗口化时改走翻转呈现模型，还解锁自动 HDR 与可变刷新率。全屏独占游戏不受影响，个别依赖旧呈现路径的老游戏若画面异常，关掉即可。只写当前用户的显卡偏好设置，不需要管理员。重启游戏后生效，可恢复。" } },
            { "set.hidpower", new[]{ "禁止键鼠设备选择性暂停" } },
            { "set.hidpower.n", new[]{ "系统会对空闲的 USB 设备断电挂起，键鼠也在其列。微软的选择性暂停文档承认退出挂起的延迟会表现为画面上的停顿。本项针对的是空闲一段时间后首次操作的延迟，持续操作时的延迟不受影响，不改善稳态延迟。台式机没有代价，笔记本需以续航为代价。仅涉及键鼠所在的 USB 链路和集线器，不涉及 U 盘和声卡。重启或重插设备后生效，可恢复。" } },
            { "set.inputqueue", new[]{ "键鼠队列长度校正" } },
            { "set.inputqueue.n", new[]{ "该值决定驱动可缓存多少条尚未处理的输入，决定的是容量而非速度，因此调高或调低都不影响延迟。通过调低该值降低延迟的说法并不成立，且调低后高回报率鼠标在一次快速移动中可能撑满队列并丢失输入。本项将被第三方工具修改过的值恢复为系统默认值 100，未被修改时不做任何操作。重启后生效，可还原。" } },
            { "audit.pollprobe", new[]{ "鼠标回报率实测" } },
            { "audit.poll.probing", new[]{ "请持续画圈移动鼠标，静止状态下鼠标不上报，无法测出结果" } },
            { "audit.poll.ok", new[]{ "回报率实测 {0} Hz，间隔中位数 {1} 毫秒，取自 {2} 个样本" } },
            { "audit.poll.weak", new[]{ "偏低，每次移动最多需等待 {0} 毫秒才被系统接收。建议在鼠标驱动或官方软件中调整至 1000Hz，这是外设环节可取得的最大收益。" } },
            { "audit.poll.good", new[]{ "已达标。继续提升至 8000Hz 的收益不足 1 毫秒，且会占用约百分之二至三的单核算力，在 CPU 负载较高的游戏中反而可能引起卡顿。" } },
            { "audit.poll.fail", new[]{ "回报率实测失败 {0}" } },
            { "audit.poll.nostart", new[]{ "无法启动 Raw Input 监听，本项此次无法测量" } },
            { "tame.lvl.eco", new[]{ "温和" } },
            { "tame.lvl.res", new[]{ "均衡" } },
            { "tame.lvl.iso", new[]{ "强力" } },

            { "gs.moff", new[]{ "总开关关闭" } },
            { "gs.noff", new[]{ "未开启" } },
            { "gs.noproc", new[]{ "未检测到进程" } },
            { "gs.thr", new[]{ "已压制 {0}" } },
            { "gs.prot", new[]{ "另有 {0} 个受内核保护，无法压制" } },

            { "white.page.sub", new[]{ "此处列出的程序永远不会被压制。将 EXE 或快捷方式拖入即可添加，作用范围自动判定。" } },
            { "white.page.empty", new[]{ "白名单为空\r\n将程序拖入，或点击右侧从运行中的程序选择" } },
            { "white.page.pick", new[]{ "选运行中的程序" } },
            { "white.page.drop", new[]{ "将 EXE 或快捷方式直接拖入左侧即可添加。\r\n\r\n普通程序会连同其拉起的子进程一并保护，命令行和脚本宿主一类仅保护自身，规则自动判定，无需手动选择。\r\n\r\n需要调整范围请右键条目。" } },
            { "white.page.platforms", new[]{ "以下游戏平台的客户端已内置豁免，无需手动添加：{0}" } },
            { "white.badge.family", new[]{ "连子进程" } },
            { "white.badge.only", new[]{ "仅此程序" } },
            { "white.badge.name", new[]{ "按进程名" } },
            { "white.badge.name.sub", new[]{ "匹配所有同名进程，不校验路径" } },
            { "white.state.running", new[]{ "{0} 个运行中" } },
            { "white.state.idle", new[]{ "未运行" } },
            { "white.menu.narrow", new[]{ "仅保护此程序，不含子进程" } },
            { "white.menu.widen", new[]{ "连同子进程一并保护" } },
            { "white.required.locked", new[]{ "系统必需的内置项，不可删除" } },
            { "white.group.builtin", new[]{ "系统内置 {0} 项，不可删除" } },
            { "white.browse.filter", new[]{ "程序或快捷方式|*.exe;*.lnk|程序|*.exe|快捷方式|*.lnk" } },
            { "white.pick.title", new[]{ "选运行中的程序" } },
            { "white.pick.sub", new[]{ "仅列出当前用户启动且带窗口的程序，不含系统进程和反作弊。" } },
            { "white.pick.busy", new[]{ "正在枚举运行中的程序" } },
            { "white.pick.none", new[]{ "没有可添加的程序，运行中的均已在白名单内。" } },
            { "white.pick.count", new[]{ "找到 {0} 个可添加的程序" } },
            { "white.pick.add", new[]{ "加入白名单" } },
            { "white.pick.add.n", new[]{ "加入 {0} 个" } },
            { "white.pick.procs", new[]{ "{0} 进程" } },
            { "white.kind.family", new[]{ "应用家族" } },
            { "white.kind.path", new[]{ "精确 EXE 路径" } },
            { "white.kind.name", new[]{ "进程名" } },
            { "white.matches", new[]{ "当前匹配 {0} 个" } },
            { "white.matches.pending", new[]{ "正在核对当前匹配" } },
            { "white.duplicate", new[]{ "该规则已存在，或输入的不是有效的 EXE 与进程名。" } },
            { "white.save.failed", new[]{ "白名单未能安全写入磁盘，本次修改未生效。请检查数据目录权限或磁盘状态。" } },
            { "white.required", new[]{ "Windows 稳定运行所必需的内置保护，不可删除，仅匹配受信任的系统路径。" } },
            { "white.required.badge", new[]{ "内置保护" } },
            { "white.reset.confirm", new[]{ "恢复默认预设将删除全部自定义白名单规则，且无法撤销。" } },
            { "btn.reset", new[]{ "恢复默认预设" } },

            { "btn.openlog", new[]{ "打开日志文件" } },

            { "set.gpu", new[]{ "逐游戏 GPU 偏好 强制独显" } },
            { "set.gpu.n", new[]{ "双显卡笔记本上，系统有时会将游戏分配给核显，导致帧数大幅下降，而系统设置中的逐程序偏好列表较为隐蔽，多数用户不会调整。本项将游戏库中的每个游戏写为高性能 GPU，仅写入偏好，不修改驱动也不禁用核显。下次启动游戏时生效，关闭后即还原。" } },
            { "set.dvr", new[]{ "关闭 Game DVR 与 Xbox 后台录制" } },
            { "set.dvr.sub", new[]{ "Game DVR 开启时，系统会持续在后台滚动缓存最近数分钟的画面，长期占用显卡编码单元和内存，而多数用户并不使用该回放功能。关闭后 Xbox 的即时回放和录制热键将失效，依赖该功能录制集锦的用户请勿开启。仅自定义模式可自行选择，竞技强制开启，常规强制关闭。" } },
            { "gm.squeezebg", new[]{ "重压后台绑核收缩" } },
            { "gm.squeezebg.sub", new[]{ "将已被重压的后台由铺满全部核心收缩至少数几个物理核，针对的是其并发访存对内存带宽的挤占，该问题优先级和效率模式均无法覆盖。落点由算法跟随当前游戏核心划分实时计算，同一核心不会既分配给游戏又作为落点。代价是这些后台程序响应明显变慢，压缩解压、编译和转码类任务耗时会成倍增加；切换至该程序的瞬间立即解除。默认开启。" } },
            { "gm.squeezebg.none", new[]{ "本机仅有 {0} 个物理核，少于 {1} 个，收缩后剩余核心不足以支撑后台运行，本项在本机始终不生效。" } },
            { "gm.squeezebg.multigroup", new[]{ "本机为多处理器组，亲和掩码无法跨组，本项不生效。" } },
            { "gm.squeezebg.narrow", new[]{ "当前划分下后台仅剩 {0} 个物理核，已窄于收缩目标，无可收缩余地，本项暂不执行。适当收回游戏核心后将重新生效。" } },
            { "gm.gpudemote", new[]{ "后台 GPU 优先级降级" } },
            { "gm.gpudemote.sub", new[]{ "后台程序提交显卡任务时会插入游戏的队列，游戏须等待其完成后才被调度，表现为帧时间突然拉长。本项将其显卡优先级降至游戏之下。副作用是直播推流、录屏和视频硬解会明显掉帧，使用这类功能请先将 OBS 等程序加入白名单。" } },
            { "gm.boost", new[]{ "游戏进程提优" } },
            { "gm.lane", new[]{ "渲染线程单独提优" } },
            { "gm.lane.sub", new[]{ "游戏通常有上百个线程，实际决定帧数的往往只有一个。开局识别出该线程后单独提升一档，在游戏内部线程互相争抢 CPU 时优先保障画面输出，6 核 12 线程一类容易被占满的机器收益最大。无法识别时退回为整个进程统一提优，不会误提。" } },
            { "gm.ifeo", new[]{ "后备提优 由系统在启动时下发" } },
            { "gm.ifeo.sub", new[]{ "内核级反作弊会阻止外部程序修改游戏优先级，Pavise 无法取得句柄权限。本项改用另一条路径，由 Windows 在游戏进程创建时即设定优先级，不受反作弊阻拦。仅写入优先级一项，不涉及调试器劫持相关的键。下次启动游戏时生效，关闭本开关将立即清除已写入的项。" } },
            { "gm.aggressive", new[]{ "后台压制范围与力度加码" } },
            { "gm.aggressive.sub", new[]{ "开启后将后台压制至最高档，作用范围同步放宽，带窗口的浏览器、语音和 IDE 一并压制，仅当前前台程序及其子进程不受影响。游戏、反作弊、加速器、白名单和系统核心始终不在范围内。输入法和外设驱动请自行加入白名单。仅自定义模式可自行选择，竞技强制开启，常规强制关闭。默认关闭。" } },
            { "gm.pausedl", new[]{ "暂停后台下载与传递优化" } },
            { "gm.pausedl.sub", new[]{ "Windows 更新和传递优化会在后台持续收发数据，传递优化还会将本机作为局域网内其他计算机的更新源，上行被占满会直接表现为延迟升高。本项在对局中停止这两项，退出后恢复，不修改系统中的更新设置。仅自定义模式可自行选择，竞技强制开启，常规强制关闭。" } },
            { "gm.wlanguard", new[]{ "对局期间抑制无线后台扫描" } },
            { "gm.wlanguard.sub", new[]{ "系统每隔数十秒会扫描全部信道以查找可用网络，扫描期间网卡必须离开当前连接的频道，数据包只能排队等待，无线环境下周期性的延迟突刺多源于此。副作用是对局中不会自动发现新的 Wi-Fi。有线连接和无无线网卡的机器不受影响。退出后恢复。" } },
            { "set.autostart", new[]{ "开机自启" } },
            { "set.autostart.n", new[]{ "通过管理员计划任务实现，开机时不会弹出 UAC 确认框。" } },
            { "set.autohide", new[]{ "检测到游戏后自动收起窗口" } },
            { "set.autohide.n", new[]{ "检测到游戏 10 秒后窗口自动收回托盘，每局仅执行一次，之后手动打开不会再被收起。" } },
            { "set.hint", new[]{ "此页仅包含应用自身的偏好与维护工具。显卡相关项在显卡页，修改系统的开关在系统环境页。" } },
            { "sec.pergame", new[]{ "逐游戏，对局开始时下发，结束后还原" } },
            { "sec.amd", new[]{ "AMD 显卡，对局开始时全局生效，结束后还原" } },
            { "set.msifix", new[]{ "显卡 MSI 中断修复" } },
            { "set.msifix.n", new[]{ "检测到显卡的消息信号中断被显式关闭（MSISupported=0），多为旧优化工具残留。中断退回传统线模式会抬高 DPC 延迟和帧时间抖动。本项把该值写回 1，重启后生效；关闭开关即还原原值。现代驱动默认就是 MSI，本项只在被人为关闭时可用。" } },
            { "msifix.clean", new[]{ "本机显卡的消息信号中断未被干预，无需修复，本项停用。" } },
            { "gfx.tab.common", new[]{ "通用" } },
            { "gfx.sub.common", new[]{ "不分厂商，逐游戏下发，结束后还原" } },
            { "set.amd.none", new[]{ "未检测到 AMD 显卡驱动，本项停用" } },
            { "set.rsr", new[]{ "RSR 驱动级升格" } },
            { "set.rsr.n", new[]{ "Radeon Super Resolution：游戏内选低一档分辨率渲染，驱动放大回原生分辨率，几乎全游戏通用。这是拿画质换帧率的交易，画面会整体变软，1080p 屏幕损失明显。对局开始时开启，退出还原。" } },
            { "rsr.warn", new[]{ "开启前请确认：这是画质换帧率的交易。\n\n需要你在游戏内把分辨率调低一档（如原生的 77%）才会生效；画面会整体变软、细节可能闪烁，1080p 屏幕上尤其明显。竞技求帧数可以开，重画质的游戏不建议。\n\n确定开启？" } },
            { "set.gpupower", new[]{ "对局功耗墙拉满" } },
            { "set.gpupower.n", new[]{ "对局中把显卡功耗上限拉到厂商允许的最大值，撞功耗墙的卡能多保住一些频率，退出对局自动还原。发热和风扇噪音会相应增加。笔记本 NVIDIA 显卡的功耗多为固定值，本项可能无效。" } },
            { "set.gpupower.nosup", new[]{ "本机显卡不支持调整功耗上限，或当前已在上限运行" } },
            { "set.amd.nosup", new[]{ "本机 GPU 或驱动版本不支持该功能，本项停用" } },
            { "set.amdalag", new[]{ "AMD Anti-Lag 低延迟" } },
            { "set.amdalag.n", new[]{ "驱动调度层压缩 CPU 提前量，显卡满载时明显降低从操作到画面的延迟，AMD 官方数据最多降三成，显卡未跑满时收益趋零。对 DX9、DX11 和 DX12 游戏生效，纯驱动调度，不注入游戏代码，与反作弊无冲突；游戏内建 Anti-Lag 2 时以游戏内为准。与 Chill 互斥，开启时驱动会暂关 Chill，本软件已连同快照，退出对局一并还原；与「AMD 帧率上限」同开时限帧优先，本项让位。" } },
            { "set.amdfrl", new[]{ "AMD 帧率上限" } },
            { "set.amdfrl.n", new[]{ "驱动级限帧，经 Radeon Chill 锁定帧率，DX9 到 DX12 和 Vulkan 游戏全部生效；老卡不支持 Chill 时回退帧率目标控制（仅 DX11 及更早）。限帧后每帧间隔更均匀，温度和功耗更低。拖动滑块在 30 到 500 之间任意锁定上限，点击后滚轮可逐帧微调，超出驱动允许区间的值会自动钳回。「屏 3」取屏幕刷新率减 3，为 FreeSync 生效区间的上沿，超出后会退出可变刷新并出现撕裂。与 Anti-Lag 驱动互斥，两者同开时限帧优先。对局开始时生效，退出对局恢复原值。" } },
            { "set.amdafmf", new[]{ "AMD 流体运动帧 驱动插帧" } },
            { "set.amdafmf.n", new[]{ "驱动级插帧 AFMF，在两张真实画面之间推算一帧，帧率视觉上接近翻倍，不需要游戏支持。代价是输入延迟明显增加，实测竞技场景可能翻倍，对战游戏不要开启，适合单机大作追求观感。基础帧率低于 60 时瑕疵明显，建议配合可变刷新率屏幕。对 DX11、DX12、Vulkan 和 OpenGL 游戏生效。退出对局恢复原值。" } },
            { "sec.app", new[]{ "应用自身" } },
            { "dlg.ok", new[]{ "知道了" } },
            { "dlg.confirm", new[]{ "确定" } },
            { "dlg.cancel", new[]{ "取消" } },
            { "dlg.tag.info", new[]{ "提示" } },
            { "dlg.tag.warn", new[]{ "注意" } },
            { "dlg.tag.danger", new[]{ "警告" } },
            { "dlg.tag.done", new[]{ "完成" } },
            { "sec.maint", new[]{ "维护" } },
            { "nav.graphics", new[]{ "显卡" } },
            { "nav.env", new[]{ "系统环境" } },
            { "nav.audit", new[]{ "系统体检" } },
            { "contact.title", new[]{ "反馈与交流" } },
            { "contact.sub", new[]{ "Bug 反馈、功能需求和使用问题均可通过以下方式联系。" } },
            { "contact.wechat", new[]{ "作者微信 功能需求和 BUG 反馈" } },
            { "contact.qq", new[]{ "QQ 一群" } },
            { "contact.qq2", new[]{ "QQ 二群" } },
            { "contact.qq3", new[]{ "QQ 三群" } },
            { "contact.douyin", new[]{ "作者抖音号" } },
            { "contact.pan", new[]{ "官方网盘" } },
            { "contact.pan.value", new[]{ "夸克网盘" } },
            { "contact.open", new[]{ "打开" } },
            { "contact.update", new[]{ "版本更新" } },
            { "contact.update.check", new[]{ "检查更新" } },
            { "contact.copy", new[]{ "复制" } },
            { "contact.copied", new[]{ "已复制" } },
            { "contact.copyfail", new[]{ "复制失败" } },
            { "contact.free.n", new[]{ "最新版和源码更新始终在微信群、QQ 群免费提供。付费获取即为受骗，请要求退款。" } },
            { "contact.close", new[]{ "关闭" } },
            { "contact.open.title", new[]{ "反馈与交流" } },
            { "nav.hardware", new[]{ "硬件与系统" } },
            { "audit.sub", new[]{ "只读检查，列出本机可用的能力与当前已启用的项。" } },
            { "audit.start", new[]{ "开始体检" } },
            { "audit.idle.title", new[]{ "还没有体检结果" } },
            { "audit.idle.hint", new[]{ "检测约需 4 秒，期间只读取，不改动任何设置" } },
            { "audit.phase.capability", new[]{ "正在读取本机写入能力" } },
            { "audit.phase.measure", new[]{ "正在实测中断分布和整机负载" } },
            { "audit.phase.persistent", new[]{ "正在读取持久系统设置" } },
            { "audit.phase.verdict", new[]{ "正在汇总结论" } },
            { "audit.phase.done", new[]{ "完成" } },
            { "audit.nv.summary", new[]{ "{0} 项写入生效，共 {1} 项" } },
            { "audit.rerun", new[]{ "重新体检 3 秒" } },
            { "audit.precise", new[]{ "精确测量 30 秒" } },
            { "audit.nvprobe", new[]{ "NVIDIA 写入实测" } },
            { "audit.failed", new[]{ "体检失败，接口不可用" } },
            { "audit.nv.probing", new[]{ "正在写入测试值并回读核对" } },
            { "audit.nv.unavailable", new[]{ "本机没有 NVIDIA 驱动接口" } },
            { "audit.nv.failed", new[]{ "写入实测失败" } },
            { "audit.nv.result", new[]{ "写入实测" } },
            { "audit.sec.capability", new[]{ "写入能力，本机可用的功能范围" } },
            { "audit.sec.machine", new[]{ "本机实测，这台机器的实际情况" } },
            { "audit.sec.persistent", new[]{ "持久系统设置，重启生效，卸载后保留" } },
            { "audit.sec.verdicts", new[]{ "结论清单，每条均标注依据" } },
            { "audit.evidence", new[]{ "依据" } },
            { "audit.footer", new[]{ "依据等级：本机实测指在这台机器上测量所得；台架实测指合成负载配对实验；机制明确指原理清楚但无量化数据；未验证指未经测量。" } },
            { "v16.graphics.sub", new[]{ "显卡相关开关。逐游戏的项仅在游戏期间生效，退出后自动还原。" } },
            { "v16.env.sub", new[]{ "本页修改系统底层设置，均需重启生效，且不随 Pavise 卸载自动还原。需要恢复请先在此处关闭。" } },
            { "v17.log.sub", new[]{ "最近 220 行，切换至本页自动刷新。每局的时长、压制数量和成效同样记录于此。" } },
            { "sec.env.kernel", new[]{ "内核与驱动，需重启，改动不随 Pavise 卸载消失" } },
            { "btn.clean", new[]{ "清理" } },
            { "btn.wipe", new[]{ "清除全部配置" } },
            { "set.about", new[]{ "Pavise {0} {1} 本地配置与用户白名单" } },

            { "set.hags", new[]{ "GPU 硬件加速调度 HAGS" } },
            { "set.hags.n", new[]{ "将显存分配和任务排期由系统交给显卡自身的调度器管理，减少一层中转，部分帧生成功能需要开启后才可用。其对帧数的影响随显卡代次、驱动版本和游戏而异，部分机器上反而掉帧，没有普适结论，建议开关各测一局自行对比。重启后生效。" } },
            { "hags.reboot", new[]{ "已写入 HAGS 设置，重启电脑后生效。" } },
            { "set.irqaffinity", new[]{ "显卡中断亲和 绑定游戏核心" } },
            { "set.irqaffinity.n", new[]{ "显卡每完成一帧都会中断 CPU 通知一次，该中断落在哪个核心由系统决定。若落在游戏线程之外的核心，数据需跨核搬运，缓存也无法命中。本项将其固定至游戏正在使用的核心；无法确定游戏核心时退回为由系统就近处理。收益量级有限，属于补充性优化。需要重启电脑或重启显卡设备后生效，可恢复。" } },
            { "irqaffinity.igpuonly", new[]{ "本机仅有核显，没有可引导的独立显卡中断，本项跳过。" } },
            { "irqaffinity.reboot", new[]{ "已写入中断亲和设置，重启该设备或重启电脑后生效。" } },
            { "set.vbs", new[]{ "关闭虚拟化安全 VBS" } },
            { "vbs.state.on", new[]{ "VBS 已开启。关闭会降低系统安全性，帧数变化因机器而异，请自行对比。" } },
            { "vbs.state.off", new[]{ "VBS 未运行，本机已无此项开销。" } },
            { "vbs.state.pending", new[]{ "已设为关闭，重启电脑后生效。" } },
            { "vbs.state.unknown", new[]{ "状态未知，无法通过 WMI 查询。" } },
            { "vbs.warn", new[]{ "关闭 VBS 与内存完整性，并停用虚拟化底层\r\n\r\n系统安全性将下降，WSL2、Docker、Hyper-V 和 Windows 沙盒将无法使用。帧数提升因机器而异，请自行前后对比。\r\n\r\n重启后生效，后续恢复同样需要重启一次。" } },
            { "vbs.needadmin", new[]{ "修改 VBS 和 hypervisor 需要管理员权限，请以管理员身份运行 Pavise。" } },
            { "vbs.done", new[]{ "已关闭 VBS 并停用 hypervisor\r\n重启电脑后生效。重启后 WSL2、Docker、Hyper-V 和 Windows 沙盒将无法使用。需要恢复请回到此处关闭该开关后重启。" } },
            { "vbs.restored", new[]{ "已恢复 VBS，hypervisor 启动类型已改回原值\r\n重启电脑后生效，之后 WSL2、Docker 等恢复可用。" } },
            { "vbs.restorefail", new[]{ "还原未完全成功，bcdedit 可能执行失败。原状态快照已保留，可重试一次，详见日志。" } },

            { "btn.shader", new[]{ "清理着色器缓存" } },
            { "set.shader.n", new[]{ "驱动更新后出现花屏或卡顿时可清理一次。清理后每个游戏首次启动需重新编译，开头数分钟会更卡。" } },
            { "shader.busy", new[]{ "正在清理" } },
            { "shader.confirm", new[]{ "清空 NVIDIA、AMD、Intel 和 DirectX 的着色器缓存\r\n\r\n怀疑驱动更新后缓存损坏时可清理一次，不保证清理后即恢复流畅。\r\n\r\n清理前请先退出游戏。之后每个游戏首次启动需重新编译，开头可能更卡。" } },
            { "shader.freed", new[]{ "已清理着色器缓存，释放 {0}" } },
            { "shader.skip", new[]{ "{0} 个文件正被占用，已跳过。关闭游戏后可再次清理。" } },
            { "shader.note", new[]{ "每个游戏下次启动都可能重新编译着色器，首次运行可能额外卡顿。" } },

            { "tray.aclist", new[]{ "反作弊列表" } },
            { "tray.reset", new[]{ "恢复默认配置" } },
            { "tray.resetask", new[]{ "将所有开关、反作弊选择和白名单恢复为默认，游戏列表予以保留。" } },
            { "tm.gpu", new[]{ "高性能 GPU 偏好" } },
            { "tm.dvr", new[]{ "关闭 Game DVR" } },
            { "tm.plan", new[]{ "游戏时切换电源计划" } },
            { "tm.autostart", new[]{ "开机自启" } },

            { "about.desc", new[]{ "把系统资源让给游戏的 Windows 工具" } },
            { "about.author", new[]{ "作者" } },
            { "about.repo", new[]{ "源码仓库" } },
            { "about.lic", new[]{ "许可协议" } },
            { "about.lic.value", new[]{ "Pavise 许可协议 禁止销售" } },
            { "about.wechat", new[]{ "微信" } },
            { "about.contact.hint", new[]{ "Bug 反馈、新功能建议和使用问题可添加作者微信，也欢迎在 GitHub 提交 Issue。" } },
            { "btn.checkupd", new[]{ "检查更新" } },
            { "btn.download", new[]{ "前往下载" } },
            { "upd.checking", new[]{ "正在检查更新" } },
            { "upd.latest", new[]{ "已是最新版本 {0}" } },
            { "upd.newver", new[]{ "发现新版本 {0}，当前 {1}，点击前往下载" } },
            { "upd.route", new[]{ "线路 {0}" } },
            { "upd.fail", new[]{ "检查版本更新失败，请通过反馈与交流中的官方网盘或群内获取最新版。" } },
            { "bal.update", new[]{ "发现新版本 {0}，请打开面板的关于页查看" } },

            { "dlg.pickproc", new[]{ "选择进程" } },
            { "btn.add", new[]{ "添加" } },
            { "btn.cancel", new[]{ "取消" } },
            { "dlg.bgsvc", new[]{ "后台服务" } },
            { "ofd.game", new[]{ "选择游戏 EXE 或 Windows 快捷方式" } },
            { "ofd.filter", new[]{ "游戏程序或快捷方式 (*.exe;*.lnk;*.url)|*.exe;*.lnk;*.url|程序 (*.exe)|*.exe|快捷方式 (*.lnk;*.url)|*.lnk;*.url" } },
            { "pick.busy", new[]{ "正在统计资源占用" } },
            { "pick.count", new[]{ "共 {0} 个可执行程序，同路径实例合并显示" } },
            { "msg.taskfail", new[]{ "计划任务操作失败，需要以管理员身份运行 Pavise。" } },

            { "tray.open", new[]{ "打开面板" } },
            { "btn.panic", new[]{ "一键恢复已记录项" } },
            { "tray.exit", new[]{ "退出" } },
            { "tray.active", new[]{ "Pavise 守护中 {0}" } },
            { "tray.idle", new[]{ "Pavise 待命，未检测到游戏" } },
            { "tray.armed", new[]{ "Pavise 已就位 {0}，进入对局自动接管" } },
            { "tray.noelev", new[]{ "Pavise 未提权，压制类功能无效" } },
            { "bal.noelev", new[]{ "当前非管理员运行，压制类功能不会生效" } },
            { "panic.done", new[]{ "可确认的改动均已还原，电源和调度已交还系统。\r\n游戏仍在运行时会在数秒后重新接管，需要完全停用请关闭游戏模式和反作弊压制。" } },
            { "panic.timeout", new[]{ "仍有部分未确认还原完成，Pavise 会继续自动重试。需要完全停用请关闭游戏模式和反作弊压制。" } },
            { "panic.failedcount", new[]{ "未确认完成 {0} 项，共 {1} 项" } },
            { "rep.done", new[]{ "{0} 本局 {1}，压制 {2} 个后台进程，合计占用 {3} CPU" } },
            { "rep.top", new[]{ " · 最高 {0} {1}" } },
            { "rep.pavise.cpu", new[]{ " · Pavise 自身平均 CPU {0}%" } },
            { "rep.gputhrottle", new[]{ " · 显卡受限 {0}" } },
            { "rep.vramspill", new[]{ " · 显存溢出到内存 峰值 {0}，建议降一档纹理质量" } },

            { "lolq.err.noinput", new[]{ "未提供英雄联盟目录" } },
            { "lolq.err.badformat", new[]{ "英雄联盟目录格式无效" } },
            { "lolq.err.notroot", new[]{ "目录不是有效的国服英雄联盟安装根目录" } },
            { "lolq.err.enumproc", new[]{ "无法枚举系统进程" } },
            { "lolq.proc.unknown", new[]{ "未知进程" } },
            { "lolq.err.clientrunning", new[]{ "检测到运行中的客户端 {0}" } },
            { "lolq.item.notdir", new[]{ "目标不是目录，未处理" } },
            { "lolq.item.vanished", new[]{ "源目录在执行前发生变化" } },
            { "lolq.err.srcreparse", new[]{ "目标路径包含重解析点" } },
            { "lolq.item.deleted", new[]{ "已删除" } },
            { "lolq.item.deletefail", new[]{ "删除失败 {0}" } },
            { "lolq.err.deleteincomplete", new[]{ "目录未能完全删除，可能仍被占用" } },
            { "lolq.msg.deldone", new[]{ "已删除英雄联盟附加层" } },
            { "lolq.msg.delpartial", new[]{ "仅完成部分删除，请关闭占用后重试" } },
            { "lolq.msg.delnone", new[]{ "未删除任何内容" } },
            { "lolq.err.rootunresolved", new[]{ "暂时无法确认安装目录结构，客户端可能正在更新" } },
            { "lolq.err.closefirst", new[]{ "请先关闭英雄联盟和 WeGame {0}" } },
            { "lolq.err.nocandidate", new[]{ "未检测到可删除的附加层目录" } },
            { "lolq.err.generic", new[]{ "操作失败" } },
            { "lolq.err.candnotdir", new[]{ "候选路径不是目录" } },
            { "lolq.err.candreparse", new[]{ "候选目录是重解析点" } },
            { "lolq.err.scanfail", new[]{ "扫描不完整 {0}" } },
            { "lolq.err.filereparse", new[]{ "目录包含文件重解析点 {0}" } },
            { "lolq.err.readfile", new[]{ "无法读取文件信息 {0}" } },
            { "lolq.err.dirreparse", new[]{ "目录包含子目录重解析点 {0}" } },
            { "lolq.err.readdir", new[]{ "无法读取目录信息 {0}" } },
            { "lolq.err.outsideroot", new[]{ "路径超出英雄联盟目录" } },
            { "lolq.err.outsiderootr", new[]{ "目标路径超出英雄联盟目录" } },
            { "lolq.err.pathreparse", new[]{ "目标路径包含重解析点" } },
            { "lolq.err.pathinvalid", new[]{ "目标路径无效" } },

            { "ac.ace.n", new[]{ "ACE 反作弊专家 腾讯" } },
            { "ac.ace.d", new[]{ "英雄联盟国服、无畏契约国服、三角洲行动、CF 等" } },
            { "ac.tp.n", new[]{ "TenProtect TP 腾讯" } },
            { "ac.tp.d", new[]{ "ACE 前身，穿越火线等老游戏仍在使用" } },
            { "ac.vanguard.n", new[]{ "Vanguard Riot" } },
            { "ac.vanguard.d", new[]{ "无畏契约、英雄联盟，vgk 为内核驱动，无法压制" } },
            { "ac.eac.n", new[]{ "EasyAntiCheat Epic" } },
            { "ac.eac.d", new[]{ "Apex、堡垒之夜、永劫无间、幻兽帕鲁等" } },
            { "ac.battleye.n", new[]{ "BattlEye" } },
            { "ac.battleye.d", new[]{ "PUBG、彩虹六号、DayZ、逃离塔科夫，BEDaisy 为驱动" } },
            { "ac.eaac.n", new[]{ "EA Javelin EA 反作弊" } },
            { "ac.eaac.d", new[]{ "战地 2042、战地 6、FC 等 EA 游戏，另有内核驱动" } },
            { "ac.gameguard.n", new[]{ "nProtect GameGuard" } },
            { "ac.gameguard.d", new[]{ "DNF 等部分韩系网游" } },
            { "ac.faceit.n", new[]{ "FACEIT 反作弊" } },
            { "ac.faceit.d", new[]{ "CS2 第三方竞技平台" } },
            { "ac.neac.n", new[]{ "NEAC 反作弊 网易" } },
            { "ac.neac.d", new[]{ "部分网易游戏，另有内核组件" } },
        };

        public static void Init()
        {
            Cur = 0;
        }

        public static void Set(int i)
        {
            Cur = 0;
            Settings.SaveStr("Lang", "zh");
        }

#if PAVISE_SELFTEST
        internal static List<string> AllKeys()
        {
            var keys = new List<string>();
            foreach (var kv in M) keys.Add(kv.Key);
            return keys;
        }

        internal static string[] Row(string key)
        {
            string[] a;
            return M.TryGetValue(key, out a) ? a : null;
        }
#endif

        public static string T(string key)
        {
            string[] a;
            if (M.TryGetValue(key, out a)) return a[Cur < a.Length ? Cur : 0];
            return key;
        }

        public static string F(string key, params object[] args) { return string.Format(T(key), args); }

        public static bool HasKey(string key) { return key != null && M.ContainsKey(key); }
    }

}
