// @author bdth 2074055628@qq.com
// 文件用途 集中维护界面多语言文本

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.IO;
using System.Net;
using System.Runtime.InteropServices;
using System.Threading;
using System.Windows.Forms;
using Microsoft.Win32;

namespace AegisApp
{
    internal static class Lang
    {
        public static int Cur;

        private static readonly Dictionary<string, string[]> M = new Dictionary<string, string[]>
        {
            { "nav.game", new[]{ "游戏模式", "Game Mode", "ゲームモード" } },
            { "nav.tame", new[]{ "反作弊", "Anti-Cheat", "アンチチート" } },
            { "nav.white", new[]{ "白名单", "Whitelist", "ホワイトリスト" } },
            { "nav.log", new[]{ "日志", "Log", "ログ" } },
            { "nav.set", new[]{ "设置", "Settings", "設定" } },
            { "nav.about", new[]{ "关于", "About", "情報" } },
            { "nav.overview", new[]{ "概览", "Overview", "概要" } },
            { "nav.columns", new[]{ "深度接管", "DEEP CONTROL", "ディープ制御" } },
            { "nav.library", new[]{ "游戏库", "Game Library", "ゲームライブラリ" } },
            { "nav.policy", new[]{ "优化策略", "Optimization", "最適化ポリシー" } },
            { "nav.reports", new[]{ "报告", "Reports", "レポート" } },
            { "v15.about.identity", new[]{ "单文件 Windows 性能守护", "SINGLE-FILE WINDOWS PERFORMANCE GUARDIAN", "単一ファイル Windows パフォーマンスガード" } },
            { "notes.title", new[]{ "版本说明", "Release notes", "リリースノート" } },
            { "notes.sub", new[]{ "当前安装版本 {0}", "Currently installed: {0}", "現在のインストール版：{0}" } },
            { "notes.current", new[]{ "当前版本", "CURRENT", "現行バージョン" } },
            { "notes.open", new[]{ "查看版本说明", "View release notes", "リリースノートを見る" } },
            { "notes.online", new[]{ "在 GitHub 查看全部", "View all on GitHub", "GitHub ですべて見る" } },
            { "notes.close", new[]{ "关闭", "Close", "閉じる" } },
            { "v15.about.update", new[]{ "版本更新", "VERSION UPDATE", "バージョン更新" } },
            { "v15.about.update.sub", new[]{ "只读取 GitHub Releases 版本号，不上传设备数据。", "Reads the GitHub Releases version only; no device data is uploaded.", "GitHub Releases の版番号のみ取得し、端末情報は送信しません。" } },
            { "v15.restore.title", new[]{ "恢复已记录调度", "RESTORE RECORDED SCHEDULING", "記録済み調度を復元" } },
            { "v15.restore.desc", new[]{ "撤销已记录的压制、提优、电源、网络与通知改动；Power Throttling 会交还系统管理；游戏仍在运行时策略可能再次接管。", "Undo recorded suppression, boost, power, network, and notification changes; Power Throttling returns to system management; an active game may re-engage policy.", "記録済みの抑制、提優、電源、ネット、通知を復元し Power Throttling はシステム管理へ戻します。ゲーム実行中は再適用される場合があります。" } },
            { "mode.source.global", new[]{ "全局默认", "Global default", "全体既定" } },
            { "mode.global.title", new[]{ "全局默认模式", "Global default mode", "全体の既定モード" } },
            { "mode.global.sub", new[]{ "所有游戏统一使用", "Applies to every game", "全ゲーム共通" } },
            { "mode.policy.active", new[]{ "当前实际行为 · {0}", "Effective behavior · {0}", "現在の実動作・{0}" } },
            { "mode.tray.current", new[]{ "当前模式：{0}（打开面板切换）", "Current mode: {0} (open panel to change)", "現在のモード：{0}（パネルで変更）" } },
            { "mode.pick.standard", new[]{ "兼容优先 · 后台先 Eco，持续大户再升级", "Compatibility first · Eco, then escalate sustained contention", "互換性優先・Eco から継続競合のみ強化" } },
            { "mode.pick.competitive", new[]{ "无用户窗口后台立即核心隔离", "Immediate isolation for background processes without user windows", "ユーザー画面を持たない背景プロセスを即時分離" } },
            { "mode.pick.custom", new[]{ "完全按策略开关执行 · 高风险功能不自动开启", "Exact policy switches · risky features never auto-enable", "設定どおり・高リスク機能は自動有効化しない" } },
            { "v15.overview.sub", new[]{ "模式从右上角切换。", "Change mode from the control at the top right.", "モード変更は右上から行います。" } },
            { "v15.guard.state", new[]{ "AEGIS 守护状态", "AEGIS GUARD STATUS", "AEGIS ガード状態" } },
            { "v15.effective.mode", new[]{ "实际生效模式", "EFFECTIVE MODE", "実際の有効モード" } },
            { "v15.master.short", new[]{ "筛选到最可能的游戏画面进程后接管，退出时恢复已记录状态", "Engages after selecting the most likely game process and restores recorded state on exit", "最も可能性の高いゲーム画面候補を選んで動作し 終了時に記録済み状態を復元" } },
            { "v15.tile.game", new[]{ "游戏资源", "Game resources", "ゲーム資源" } },
            { "v15.tile.game.sub", new[]{ "只提优启发式筛选的画面候选", "Only the heuristically selected game candidate is boosted", "ヒューリスティックで選んだゲーム候補だけを提優" } },
            { "v15.tile.background", new[]{ "后台边界", "Background bounds", "背景境界" } },
            { "v15.tile.background.sub", new[]{ "系统 / 音频 / 白名单硬豁免", "Hard safety exemptions", "安全除外を常時維持" } },
            { "v15.tile.environment", new[]{ "系统环境", "Environment", "システム環境" } },
            { "v15.tile.environment.sub", new[]{ "电源与调度按预设执行", "Preset-aware power and scheduling", "プリセット別の電源と調度" } },
            { "v15.library.sub", new[]{ "只从 EXE 或快捷方式添加；自动识别游戏族，只提优启发式筛选的画面候选。", "Add an EXE or shortcut. Aegis identifies the game family and boosts only the heuristically selected display candidate.", "EXE またはショートカットから追加。ゲーム一式を識別し ヒューリスティックで選んだ画面候補だけを提優します。" } },
            { "v15.library.empty", new[]{ "尚未添加游戏\r\n添加 EXE/LNK，或将文件拖到这里", "NO GAMES YET\r\nAdd an EXE/LNK or drop one here", "ゲームはまだありません\r\nEXE/LNK を追加またはここへドロップ" } },
            { "v15.library.add", new[]{ "＋ 添加游戏文件", "+ Add game file", "＋ ゲームファイルを追加" } },
            { "v15.library.drop", new[]{ "EXE / LNK · 支持拖放", "EXE / LNK · DRAG & DROP", "EXE / LNK · ドロップ対応" } },
            { "v15.library.running", new[]{ "运行中", "RUNNING", "実行中" } },
            { "v15.library.ready", new[]{ "已就绪", "READY", "準備完了" } },
            { "v15.policy.sub", new[]{ "右上角显示当前模式与实际来源。", "The active mode and its effective source are shown at the top right.", "現在のモードと由来は右上に表示されます。" } },
            { "v15.policy.mode.hint", new[]{ "常规 / 竞技可能覆盖自定义项；强制生效时会明确标记并锁定", "Standard/Competitive may override custom items; forced behavior is labelled and locked", "標準/競技はカスタム項目を上書きする場合があり、強制時は明示して固定" } },
            { "v15.policy.core", new[]{ "全模式核心控制", "CORE CONTROLS · ALL MODES", "全モード共通の基本制御" } },
            { "v15.policy.custom", new[]{ "自定义预设细节", "CUSTOM PRESET DETAILS", "カスタムプリセット詳細" } },
            { "v15.policy.extreme", new[]{ "极限实验室 · 高风险", "EXTREME LAB · HIGH RISK", "極限ラボ・高リスク" } },
            { "v15.boost.sub", new[]{ "根据入口关系 窗口和路径筛选最可能的画面进程；启动器和平台不会获得游戏优先级", "Selects the most likely game process from entry relationships windows and paths; launchers and platforms are not boosted", "入口関係 ウィンドウ パスから最も可能性の高いゲーム候補を選び ランチャーとプラットフォームは提優しません" } },
            { "v15.plan.sub", new[]{ "游戏期间按当前预设应用可逆电源计划，退出后恢复原计划", "Applies a reversible preset-aware power plan during play and restores it on exit", "プレイ中のみプリセット別の可逆電源プランを適用し、終了時に復元" } },
            { "v15.notif.sub", new[]{ "游戏运行期间抑制系统通知，游戏退出后自动恢复", "Suppresses system notifications during play and restores them afterwards", "ゲーム中のみ通知を抑え、終了後に自動復元" } },
            { "v15.hz.sub", new[]{ "会话期间守护最高刷新率；显示配置异常时可关闭", "Keeps the highest refresh rate during the session; disable if a display misbehaves", "セッション中に最高リフレッシュレートを維持。表示異常時は無効化" } },
            { "v15.custom.override", new[]{ "用于自定义预设；竞技可能按固定策略强制启用", "Used by Custom; Competitive may force its fixed policy", "カスタム用。競技では固定ポリシーで強制される場合あり" } },
            { "v15.trim.sub", new[]{ "仅自定义重压时执行；可能触发后台重新读盘，默认关闭", "Custom heavy mode only; may cause background paging and stays off by default", "カスタム強抑制時のみ。再読込を起こすため既定オフ" } },
            { "def.title", new[]{ "Defender 扫描排除", "Defender scan exclusions", "Defender スキャン除外" } },
            { "def.warn.title", new[]{ "这是拿安全换性能，请先读完再决定", "This trades security for performance — read before deciding", "セキュリティと引き換えの設定です。必ずお読みください" } },
            { "def.warn.body", new[]{ "被排除的目录不再被实时扫描，其中的恶意文件不会被拦截。游戏目录常混有破解版、第三方 mod 和修改器，风险高于普通目录。只排除你信任来源的游戏。", "Excluded folders are no longer scanned in real time, so malicious files inside them are not blocked. Game folders often contain cracks, third-party mods and trainers, making them riskier than ordinary folders. Only exclude games from sources you trust.", "除外したフォルダーはリアルタイム スキャンの対象外となり、内部の悪意あるファイルはブロックされません。ゲームフォルダーは改造版や第三者 MOD が混在しやすく、通常より危険です。信頼できる入手元のみ除外してください。" } },
            { "def.state.on", new[]{ "已排除", "EXCLUDED", "除外中" } },
            { "def.state.off", new[]{ "受保护", "PROTECTED", "保護中" } },
            { "def.confirm", new[]{ "确定要把《{0}》的目录排除出 Defender 实时扫描吗？\r\n\r\n{1}\r\n\r\n该目录下的文件将不再被查杀。只有当你确信这个游戏的来源可靠时才继续。", "Exclude the folder of \"{0}\" from Defender real-time scanning?\r\n\r\n{1}\r\n\r\nFiles in this folder will no longer be scanned. Continue only if you trust where this game came from.", "「{0}」のフォルダーを Defender のリアルタイム スキャンから除外しますか？\r\n\r\n{1}\r\n\r\nこのフォルダー内はスキャンされなくなります。入手元を信頼できる場合のみ続行してください。" } },
            { "def.notours", new[]{ "这条排除不是 Aegis 添加的（可能是你在 Windows 安全中心手动加的），Aegis 不会去动它。需要取消请到 Windows 安全中心操作。", "This exclusion was not added by Aegis (you likely added it in Windows Security), so Aegis will not touch it. Remove it from Windows Security instead.", "この除外は Aegis が追加したものではないため（Windows セキュリティで手動追加された可能性）、Aegis は変更しません。解除は Windows セキュリティから行ってください。" } },
            { "def.failed", new[]{ "操作失败，系统未接受这次修改（可能被安全策略或第三方杀软阻止）。", "The change failed — the system did not accept it (it may be blocked by policy or third-party antivirus).", "変更に失敗しました。ポリシーまたは他社製ウイルス対策によりブロックされた可能性があります。" } },
            { "def.unavailable", new[]{ "无法读取 Defender 设置：可能未安装、已被第三方杀软接管，或当前权限不足。", "Cannot read Defender settings: it may be absent, replaced by third-party antivirus, or unavailable at this privilege level.", "Defender の設定を読み取れません。未導入、他社製品による置き換え、または権限不足の可能性があります。" } },
            { "def.off", new[]{ "Windows Defender 的实时保护当前是关闭的，本功能对你没有意义——没有实时扫描，也就没有扫描开销可省。如果之后重新启用了 Defender，再回来这里即可。", "Windows Defender real-time protection is currently off, so this feature does nothing for you: with no real-time scanning there is no scanning overhead to remove. Come back here if you re-enable Defender later.", "Windows Defender のリアルタイム保護が無効です。リアルタイム スキャンがないため削減できるオーバーヘッドもありません。Defender を再度有効にした場合はここに戻ってください。" } },
            { "def.nogames", new[]{ "游戏库还是空的。先在「游戏库」里添加游戏，这里才会列出可排除的目录。", "Your game library is empty. Add games in the Library page first and their folders will appear here.", "ゲームライブラリが空です。先に「ライブラリ」でゲームを追加してください。" } },
            { "def.clearall", new[]{ "全部取消排除", "Remove all exclusions", "すべての除外を解除" } },
            { "def.clearall.none", new[]{ "Aegis 目前没有添加过任何排除项。", "Aegis has not added any exclusions.", "Aegis が追加した除外はありません。" } },
            { "def.clearall.done", new[]{ "已取消 {0} 个由 Aegis 添加的排除项（你手工添加的不受影响）。", "Removed {0} exclusion(s) added by Aegis. Entries you added manually are untouched.", "Aegis が追加した除外を {0} 件解除しました。手動で追加した項目はそのままです。" } },
            { "def.open", new[]{ "Defender 扫描排除", "Defender scan exclusions", "Defender スキャン除外" } },
            { "def.open.sub", new[]{ "逐个游戏目录手动勾选；会降低这些目录的安全防护", "Opt in per game folder; lowers protection for those folders", "ゲームフォルダーごとに選択。該当フォルダーの保護は低下します" } },
            { "gm.idledisable", new[]{ "竞技模式禁用 CPU 空闲状态", "Disable CPU idle states in Competitive", "競技モードで CPU アイドル状態を無効化" } },
            { "gm.idledisable.sub", new[]{ "省掉核心唤醒延迟；仅竞技+交流供电生效，发热和功耗会上升", "Removes core wake-up latency; Competitive on AC only, raises heat and power draw", "コア復帰遅延を解消。競技かつAC電源時のみ。発熱と消費電力が増加" } },
            { "gm.visualfx", new[]{ "游戏时降级桌面视觉效果", "Downgrade desktop visual effects during games", "ゲーム中はデスクトップの視覚効果を下げる" } },
            { "gm.visualfx.sub", new[]{ "关闭桌面透明与窗口动画，退出后还原（默认关闭）", "Turns off desktop transparency and window animations, restored on exit (off by default)", "透明効果とウィンドウアニメーションを無効化し、終了後に復元（既定オフ）" } },
            { "gm.standby", new[]{ "游戏开始时清理待机内存", "Purge standby memory when a game starts", "ゲーム開始時にスタンバイメモリを解放" } },
            { "gm.standby.sub", new[]{ "只在会话开始、游戏仍在加载时清一次，后台线程执行", "Purged once at session start while the game is still loading, on a background thread", "ロード中に一度だけ、バックグラウンドスレッドで解放" } },
            { "gm.standbymid", new[]{ "游戏进行中也按阈值清理（默认关闭）", "Also purge mid-game when memory runs low (off by default)", "ゲーム中もメモリ逼迫時に解放（既定オフ）" } },
            { "gm.standbymid.sub", new[]{ "仅空闲见底时清最低优先级部分（约 5ms）；全量绝不在游戏中执行", "Lowest-priority only, when free memory runs out (~5 ms); never a full purge mid-game", "空きメモリ枯渇時に最低優先度のみ（約5ms）。全体解放はゲーム中に行いません" } },
            { "v15.anticheat.sub", new[]{ "独立于游戏性能预设，只控制下方明确列出的反作弊用户态组件。", "Independent of performance presets and limited to the explicitly listed user-mode anti-cheat components.", "性能プリセットと独立し、下記のユーザー態アンチチートのみ制御。" } },
            { "v14.overview.sub", new[]{ "按入口关系 窗口和路径筛选最可能的游戏画面候选；启动器和平台进程不会被提优。", "Selects the most likely game candidate from entry relationships windows and paths; launchers and platform clients are not boosted.", "入口関係 ウィンドウ パスから最も可能性の高いゲーム候補を選び ランチャーとプラットフォームは提優しません。" } },
            { "v14.master", new[]{ "Aegis 智能守护", "Aegis Smart Guard", "Aegis スマートガード" } },
            { "v14.master.sub", new[]{ "全局总开关；所有游戏共享当前性能预设", "Global master; every game shares the active preset", "全体スイッチ。全ゲームで現在のプリセットを共有" } },
            { "v14.preset", new[]{ "性能预设", "Performance preset", "性能プリセット" } },
            { "preset.standard", new[]{ "常规", "Standard", "標準" } },
            { "preset.competitive", new[]{ "竞技", "Competitive", "競技" } },
            { "preset.custom", new[]{ "自定义", "Custom", "カスタム" } },
            { "v14.session", new[]{ "当前会话", "Current session", "現在のセッション" } },
            { "v14.cpu.topology", new[]{ "CPU 调度拓扑", "CPU scheduling topology", "CPU スケジューリング構成" } },
            { "v14.library.sub", new[]{ "选择任意游戏 exe 后自动推断安装根目录；同根目录组件只做家族豁免，只有筛选出的画面候选获得提优。", "Pick any game executable to infer its install root. Family components are exempted, while only the selected display candidate is boosted.", "任意のゲーム exe からルートを推定。同一ルートの構成要素は除外保護し 選択した画面候補だけを提優します。" } },
            { "v14.boost.status", new[]{ "游戏提权状态", "GAME BOOST STATUS", "ゲーム提優状態" } },
            { "v14.boost.disabled", new[]{ "游戏提优已关闭", "Game boost is disabled", "ゲーム提優は無効です" } },
            { "v14.boost.wait", new[]{ "等待游戏画面候选", "Waiting for a game-display candidate", "ゲーム画面候補を待機中" } },
            { "v14.boost.no.renderer", new[]{ "已检测到游戏入口，但尚未筛选到画面候选", "Game entry detected; no game-process candidate selected yet", "ゲーム入口を検出しましたが 画面候補はまだ選ばれていません" } },
            { "v14.boost.applying", new[]{ "正在验证并提优：{0}", "Applying and verifying: {0}", "検証して提優中：{0}" } },
            { "v14.boost.verified", new[]{ "已验证：{0}\r\n高优先级 + 高 I/O 已回读确认", "Verified: {0}\r\nHigh priority + high I/O confirmed by readback", "検証済み：{0}\r\n高優先度 + 高 I/O を読戻し確認" } },
            { "v14.boost.failed", new[]{ "提优未落地：{0}\r\nAegis 正在持续纠偏，请查看日志", "Boost did not stick: {0}\r\nAegis will keep correcting it; see the log", "提優未反映：{0}\r\nAegis が継続補正します。ログを確認" } },
            { "v14.policy.sub", new[]{ "先选择性能预设，再检查安全边界。", "Choose a performance preset, then review its safety boundaries.", "性能プリセットを選び、安全境界を確認します。" } },
            { "v14.policy.performance", new[]{ "性能策略", "Performance policy", "性能ポリシー" } },
            { "v14.preset.choose", new[]{ "选择性能预设", "Choose a performance preset", "性能プリセットを選択" } },
            { "v14.policy.boundary", new[]{ "安全边界与额外开关", "Safety boundaries and overrides", "安全境界と追加設定" } },
            { "v14.bg.master", new[]{ "后台调度 · 总开关", "Background scheduling · master", "背景調度・メイン" } },
            { "v14.bg.master.sub", new[]{ "关闭后所有预设都不再压制普通后台；前台、带主窗口程序家族、游戏 PID 家族、Windows 核心、其它用户会话、Aegis 自身和白名单始终豁免", "Off leaves ordinary apps untouched; foreground and user-window process families, game PIDs, Windows core, other sessions, Aegis, and the whitelist stay exempt", "オフでは全プリセットの背景抑制を停止。前面と主画面を持つプロセス一式、ゲーム PID 群、Windows 中枢、他セッション、Aegis、許可リストは常に除外" } },
            { "v14.cpu.adaptive.sub2", new[]{ "竞技始终启用；常规/自定义可在此额外强制。无安全分区时会自动降级，不伪装成功", "Always on in Competitive; optional for Standard/Custom. Falls back safely when no valid partition exists", "競技では常時有効。標準/カスタムでは任意。安全な分離不可時は自動的に安全側へ縮退" } },
            { "v14.preset.forced", new[]{ "当前预设强制", "forced by preset", "現在のプリセットで強制" } },
            { "v14.anticheat.boundary", new[]{ "反作弊只由此处控制，不跟随性能预设", "Anti-cheat is controlled only here, independently of presets", "アンチチートはプリセットと独立し、ここだけで制御" } },
            { "v14.anticheat.master.sub", new[]{ "只影响下方明确列出的反作弊组件；不会把游戏平台或登录器当成反作弊", "Affects only the listed anti-cheat components; game clients and launchers are not treated as anti-cheat", "下記アンチチートのみ対象。ゲームクライアントやランチャーは対象外" } },
            { "v14.preset.standard.short", new[]{ "常规：优先兼容性；后台先轻压，只有持续争抢资源时才升级。", "Standard: compatibility first; light guard, escalating only sustained contention.", "標準：互換性優先。軽い抑制から、競合が続く場合のみ強化。" } },
            { "v14.preset.standard.for", new[]{ "推荐 · 大多数单机、网游与日常后台共存", "RECOMMENDED · MOST GAMES AND EVERYDAY MULTITASKING", "推奨・大半のゲームと普段使い" } },
            { "v14.preset.standard.title", new[]{ "常规｜稳妥释放性能", "Standard | Balanced performance", "標準｜安定した性能" } },
            { "v14.preset.standard.detail", new[]{ "画面候选提优；无用户窗口后台立即进入 Eco。只有持续 CPU / IO 大户才逐级压制，不自动启用严格核心分区。", "Boosts the selected game candidate and puts background processes without user windows in Eco immediately. Only sustained CPU/IO contention escalates; strict partitioning stays off.", "選択したゲーム候補を提優し ユーザー画面を持たない背景プロセスを直ちに Eco 化します。CPU / IO 競合が続く場合のみ段階強化し 厳格分離は自動有効化しません。" } },
            { "v14.preset.competitive.short", new[]{ "竞技：没有用户窗口的后台进程无需采样等待，立即隔离到专用核心。", "Competitive: background processes without a user-facing window are isolated immediately.", "競技：ユーザー画面を持たない背景プロセスを待機なしで即時分離。" } },
            { "v14.preset.competitive.for", new[]{ "适合明确存在 CPU 后台争抢并愿意使用激进策略的场景", "FOR SYSTEMS WITH MEASURED CPU CONTENTION AND USERS WHO ACCEPT AN AGGRESSIVE POLICY", "CPU の背景競合を確認済みで 強い方針を許容できる場合向け" } },
            { "v14.preset.competitive.title", new[]{ "竞技｜立即隔绝资源争抢", "Competitive | Immediate contention isolation", "競技｜リソース競合を即時分離" } },
            { "v14.preset.competitive.detail", new[]{ "游戏与无用户窗口后台立即分区；前台和带主窗口程序保持豁免，同时启用下载抑制、网络 / MMCSS 调度与 Game DVR 控制。", "Immediately partitions the game from background processes without user windows; foreground and user-facing apps stay exempt while download network/MMCSS and Game DVR controls are enabled.", "ゲームとユーザー画面を持たない背景プロセスを即時分離し 前面アプリと主画面を持つアプリは除外したまま ダウンロード ネットワーク MMCSS Game DVR を制御します。" } },
            { "v14.preset.custom.short", new[]{ "自定义：完全按高级策略开关执行；高风险功能不会被自动开启。", "Custom: follows advanced switches exactly; risky features are never enabled implicitly.", "カスタム：詳細設定どおりに動作。高リスク機能は自動有効化しません。" } },
            { "v14.preset.custom.for", new[]{ "适合 · 明确知道每个调度选项作用的高级用户", "FOR · ADVANCED USERS WHO WANT EXPLICIT CONTROL", "対象・各調度設定を理解し明示制御したい上級者" } },
            { "v14.preset.custom.title", new[]{ "自定义｜逐项决定行为", "Custom | Explicit per-feature control", "カスタム｜機能ごとの明示制御" } },
            { "v14.preset.custom.detail", new[]{ "按高级策略中的开关组合执行。严格分区、工作集修剪和深度冻结均需显式开启，不会由预设偷偷启用。", "Uses the exact advanced-policy switch combination. Strict partitioning, working-set trim, and deep freeze all require explicit opt-in.", "詳細設定の組み合わせどおりに実行。厳格分離、ワーキングセット削減、深度凍結は明示的な有効化が必要です。" } },
            { "v14.bg.staged", new[]{ "预设后台策略", "Preset background policy", "プリセット背景ポリシー" } },
            { "v14.bg.staged.sub", new[]{ "常规：无用户窗口后台轻压 · 竞技：同一边界内立即核心隔离", "Standard: light guard for background processes without user windows · Competitive: immediate CPU isolation inside the same boundary", "標準：ユーザー画面のない背景を軽く抑制・競技：同じ境界内で即時コア分離" } },
            { "v14.cpu.adaptive", new[]{ "严格 CPU 分区", "Strict CPU partition", "厳格な CPU 分離" } },
            { "v14.cpu.adaptive.sub", new[]{ "适配 SMT、混合架构、X3D 与多处理器组；竞技预设自动启用", "SMT, hybrid, X3D and multi-group aware; automatically enabled by Competitive", "SMT、ハイブリッド、X3D、複数グループ対応。競技で自動有効" } },
            { "v14.freeze", new[]{ "深度冻结（高风险）", "Deep freeze (high risk)", "ディープフリーズ（高リスク）" } },
            { "v14.freeze.sub", new[]{ "只冻结持续高干扰且通过全部豁免检查的用户进程；不会因竞技模式自动开启", "Freezes only sustained high-interference user processes after all exemptions; Competitive never enables it automatically", "全除外検査を通過した高干渉ユーザープロセスのみ凍結。競技でも自動有効化しません" } },
            { "v14.anticheat", new[]{ "反作弊专项", "Anti-cheat controls", "アンチチート制御" } },
            { "v14.manage.white", new[]{ "管理白名单", "Manage whitelist", "ホワイトリスト管理" } },
            { "v14.reports.sub", new[]{ "每局保存持续时间、提权回读结果、后台压制与冻结数量；不再运行帧采集器。", "Each session records duration, verified boost state, suppression, and freezes. No frame collector is run.", "各セッションの時間、提優読戻し、背景抑制、凍結数を保存。フレーム収集は行いません。" } },
            { "v14.open.report", new[]{ "打开报告文件", "Open report file", "レポートを開く" } },
            { "v14.cpu.multigroup", new[]{ "多处理器组 · CPU Sets 跨组调度 · 竞技模式物理核优先", "Multiple processor groups · cross-group CPU Sets · Competitive prefers physical cores", "複数プロセッサグループ · CPU Sets 跨グループ制御 · 競技は物理核優先" } },
            { "v14.cpu.hybrid", new[]{ "混合架构 · 后台能效核 · 竞技模式性能核优先", "Hybrid CPU · background on E-cores · Competitive prefers performance cores", "ハイブリッド CPU · 背景は E コア · 競技は性能コア優先" } },
            { "v14.cpu.x3d", new[]{ "非对称 L3 / X3D · 游戏大缓存 CCD · 后台隔离到另一 CCD", "Asymmetric L3 / X3D · game on large-cache CCD · background isolated elsewhere", "非対称 L3 / X3D · ゲームは大容量キャッシュ CCD · 背景は別 CCD へ分離" } },
            { "v14.cpu.generic", new[]{ "{0} 逻辑处理器 · 常规按需升级 · 竞技立即物理核隔离", "{0} logical processors · Standard escalates on demand · Competitive isolates immediately", "{0} 論理プロセッサ · 標準は必要時に強化 · 競技は即時物理核分離" } },
            { "detect.foreground", new[]{ "游戏根目录 + 前台窗口（评分 {0}）", "Game root + foreground window (score {0})", "ゲームルート + 前面ウィンドウ（スコア {0}）" } },
            { "detect.visible", new[]{ "游戏根目录 + 可见窗口（评分 {0}）", "Game root + visible window (score {0})", "ゲームルート + 表示ウィンドウ（スコア {0}）" } },
            { "detect.candidate", new[]{ "游戏根目录内的候选进程（评分 {0}）", "Candidate inside game root (score {0})", "ゲームルート内の候補（スコア {0}）" } },
            { "report.none", new[]{ "暂无游戏会话报告。完成一局游戏后会在这里留下调度结果。", "No game-session reports yet. A completed session will leave scheduling results here.", "ゲームセッションレポートはまだありません。終了後に調度結果が保存されます。" } },
            { "report.read.error", new[]{ "报告读取失败。", "Could not read the report.", "レポートを読み込めませんでした。" } },
            { "report.boost.ok", new[]{ "提权已回读验证", "boost verified by readback", "提優を読戻し確認" } },
            { "report.boost.missed", new[]{ "本局未验证提权", "boost not verified", "提優未検証" } },
            { "report.control", new[]{ "压制 {0} / 冻结 {1}", "restrained {0} / frozen {1}", "抑制 {0} / 凍結 {1}" } },
            { "report.unknown.game", new[]{ "未知游戏", "Unknown game", "不明なゲーム" } },
            { "btn.ok", new[]{ "保存", "Save", "保存" } },

            { "title.noelev", new[]{ "未提权 · 压制类功能无效", "Not elevated · suppression disabled", "権限なし・抑制機能は無効" } },
            { "title.admin", new[]{ "管理员权限", "Administrator", "管理者権限" } },
            { "title.guard", new[]{ "守护中（{0}）", "guarding ({0})", "稼働中（{0}）" } },
            { "title.idle", new[]{ "待命", "standby", "待機中" } },

            { "game.toggle", new[]{ "游戏模式 · 检测到游戏时把系统专供游戏", "Game Mode · dedicate the system to the running game", "ゲームモード・実行中のゲームにシステムを専有" } },
            { "game.toggle.n", new[]{ "后台降优先级 + 锁核 + 效率模式，游戏提优先级 + 高IO + 卓越电源；退出自动还原。", "Background: lower priority + core-lock + eco mode; game: boosted priority + high-IO + Ultimate power. Auto-restored on exit.", "背景は優先度低下 + コア固定 + 効率モード、ゲームは優先度アップ + 高IO + 高性能電源。終了で自動復元。" } },
            { "game.list", new[]{ "游戏列表（游戏本体和启动器都建议加入）", "Game list (add both the game and its launcher)", "ゲーム一覧（本体とランチャー両方を推奨）" } },
            { "btn.pick", new[]{ "＋ 从运行中选择", "＋ Pick from running", "＋ 実行中から選択" } },
            { "btn.browse", new[]{ "＋ 浏览 exe…", "＋ Browse exe…", "＋ exe を参照…" } },
            { "btn.remove", new[]{ "－ 移除选中", "－ Remove selected", "－ 選択を削除" } },

            { "st.off", new[]{ "已关闭", "Off", "オフ" } },
            { "st.mon", new[]{ "监控中，未检测到列表内的游戏", "Monitoring, no listed game detected", "監視中、一覧のゲーム未検出" } },
            { "st.active", new[]{ "激活中（{0}）· 已压制 {1} 个进程", "Active ({0}) · {1} processes throttled", "稼働中（{0}）・{1} プロセス抑制" } },
            { "st.boost", new[]{ " · 已提优 {0} · {1}", " · boosted {0} · {1}", " ・提優 {0}・{1}" } },
            { "st.hp", new[]{ "高性能电源", "high-perf power", "高性能電源" } },
            { "st.pr", new[]{ "电源就绪", "power ready", "電源待機" } },
            { "st.extreme", new[]{ " · 极限模式（冻结 {0}）", " · Extreme (frozen {0})", " ・極限モード（凍結 {0}）" } },

            { "tame.toggle", new[]{ "反作弊压制 · 总开关", "Anti-Cheat Suppression · master", "アンチチート抑制・メイン" } },
            { "tame.caveat", new[]{
                "压制 = 最低优先级 + 锁核 + 效率模式，不杀进程、不阻止检测、不改内存。\r\nVanguard / EAC / BattlEye 会监控自身，压得太狠可能心跳超时掉线；默认只开较稳的 ACE，其它按需开。",
                "Suppress = lowest priority + core-lock + efficiency mode. No killing / no bypassing detection / no memory edits.\r\nVanguard / EAC / BattlEye watch their own state; heavy suppression can cause a heartbeat-timeout disconnect. Only ACE is on by default — enable the rest as needed.",
                "抑制 = 最低優先度 + コア固定 + 効率モード。プロセス終了/検知妨害/メモリ改変なし。\r\nVanguard / EAC / BattlEye は自身を監視するため、強く抑えるとハートビート切れで切断されることがあります。既定は ACE のみ、他は必要に応じて。" } },
            { "tame.footer", new[]{ "只处理当前厂商列表中明确列出的用户态进程；关闭某项会恢复对应进程", "Only explicitly listed user-mode processes are handled; disabling an item restores its processes", "現在のベンダー一覧に明記したユーザーモードプロセスのみ対象 項目をオフにすると復元" } },

            { "gs.moff", new[]{ "总开关关闭", "Master off", "メインオフ" } },
            { "gs.noff", new[]{ "未开启", "Off", "オフ" } },
            { "gs.noproc", new[]{ "未检测到进程", "No process", "プロセス無し" } },
            { "gs.thr", new[]{ "已压制 {0}", "{0} throttled", "{0} 抑制" } },
            { "gs.prot", new[]{ "（{0} 个受内核保护压不动）", " ({0} kernel-protected)", "（{0} 件カーネル保護で不可）" } },

            { "white.desc", new[]{
                "始终豁免清单：这些进程不会进入任何后台策略。增删即时生效；运行中加白会立刻恢复。",
                "Always-exempt list: these processes never enter any background policy. Changes are immediate; adding one restores it at once.",
                "常時除外リスト：これらはどの背景ポリシーの対象にもなりません。変更は即時反映されます。" } },
            { "btn.reset", new[]{ "恢复默认预设", "Reset to preset", "既定に戻す" } },

            { "btn.openlog", new[]{ "打开日志文件", "Open log file", "ログを開く" } },
            { "btn.clearlog", new[]{ "清空日志", "Clear log", "ログをクリア" } },

            { "set.gpu", new[]{ "逐游戏高性能 GPU 偏好", "Per-game High-performance GPU preference", "ゲームごとの高パフォーマンス GPU 設定" } },
            { "set.gpu.n", new[]{ "双显卡笔记本强制走独显，下次启动游戏生效。", "Forces the dGPU on dual-GPU laptops; applies from the next game launch.", "デュアル GPU ノートで dGPU を強制、次回起動から有効。" } },
            { "set.dvr", new[]{ "关闭 Game DVR / Xbox 后台录制", "Disable Game DVR / Xbox recording", "Game DVR / Xbox 録画を無効化" } },
            { "set.fso", new[]{ "逐游戏关闭全屏优化 (FSO)", "Per-game disable Fullscreen Optimizations", "ゲームごとに全画面最適化(FSO)を無効化" } },
            { "set.fso.n", new[]{ "部分游戏降输入延迟，因游戏而异，可以试。", "Lower input latency for some games; varies by title — worth a try.", "一部ゲームで入力遅延を低減、ゲームによる。試す価値あり。" } },
            { "set.notif", new[]{ "游戏时免打扰", "Do-not-disturb during games", "ゲーム中は通知オフ" } },
            { "set.trim", new[]{ "自定义重压时清空后台工作集（可能触发读盘）", "Trim working sets in Custom heavy mode (may cause paging)", "カスタム強抑制時にメモリ解放（再読込あり）" } },
            { "set.hz", new[]{ "刷新率守护（切到最高刷新率）", "Refresh-rate guard (switch to max Hz)", "リフレッシュレート保護（最高 Hz へ）" } },
            { "set.plan", new[]{ "游戏时切换电源计划（卓越性能）", "Switch power plan during games (Ultimate)", "ゲーム中に電源プランを切替（究極のパフォーマンス）" } },
            { "gm.cfg", new[]{ "自定义优化策略", "Custom optimization policy", "カスタム最適化ポリシー" } },
            { "gm.suppress", new[]{ "后台策略（常规轻压 / 竞技隔离）", "Background policy (guard / isolate)", "背景ポリシー（軽減 / 分離）" } },
            { "gm.boost", new[]{ "游戏提优（高优先级 / 绑核 / 高IO / GPU优先）", "Boost the game (high priority / core pinning / high IO / GPU)", "ゲームを最適化（高優先度 / コア割当 / 高 IO / GPU）" } },
            { "gm.strict", new[]{ "严格核心隔离（自定义模式立即分区）", "Strict core isolation (immediate partition in Custom)", "厳格なコア分離（カスタムで即時分離）" } },
            { "gm.aggressive", new[]{ "竞技级压制范围", "Competitive-grade suppression scope", "競技級の抑制範囲" } },
            { "gm.aggressive.sub", new[]{ "开启后与竞技模式完全一致：前台窗口和可见窗口程序（浏览器/语音/IDE等）不再豁免后台压制，只有会话/认证/合成器/音频等核心系统服务还护着（不是整个 C:\\Windows 目录）；电源计划按竞技档调参。竞技始终启用；仅自定义可选，默认关闭", "Matches Competitive exactly: the foreground window and visible-window apps (browser/voice/IDE, etc.) lose their suppression exemption — only core system services (session/auth/compositor/audio, not the whole C:\\Windows tree) stay protected; power plan tuning also matches Competitive. Always on in Competitive; optional in Custom, off by default", "競技と完全に一致：前面ウィンドウと表示ウィンドウのアプリ（ブラウザ/ボイス/IDE等）は抑制対象になり セッション/認証/コンポジタ/オーディオ等の中核システムサービスのみ保護（C:\\Windows 全体ではない）。電源プランも競技相当に調整。競技では常時有効、カスタムでは任意（既定オフ）" } },
            { "gm.freeze", new[]{ "极限冻结（暂停持续高 CPU / IO 的用户后台）", "Extreme freeze (suspend sustained high CPU / IO apps)", "極限凍結（高 CPU / IO の背景アプリを停止）" } },
            { "gm.freeze.warn", new[]{ "极限冻结会暂停持续高 CPU / 磁盘 IO 的用户后台程序，它们在游戏结束前可能表现为无响应。前台与可见窗口程序家族、Windows 路径、游戏、白名单和 Aegis 会被排除；独立看门狗负责崩溃恢复。\r\n\r\n仍要开启？", "Extreme freeze suspends user apps with sustained CPU or disk activity; they may appear unresponsive until the game ends. Foreground and visible-window process families, Windows paths, games, the whitelist, and Aegis are excluded. An independent watchdog handles crash recovery.\r\n\r\nEnable it?", "極限凍結は CPU / ディスク負荷が続くユーザーアプリを停止し ゲーム終了まで応答しないように見える場合があります 前面と表示ウィンドウのプロセス一式 Windows パス ゲーム 許可リスト Aegis は除外し 独立した監視役がクラッシュ復元します\r\n\r\n有効にしますか？" } },
            { "gm.net", new[]{ "网络优化（关闭系统流控）", "Network tweak (disable throttling index)", "ネットワーク最適化（スロットリング無効）" } },
            { "gm.fgboost", new[]{ "前台调度加权（更长时间片给游戏）", "Foreground scheduling boost (longer quanta)", "前面プロセスのスケジューリング優先" } },
            { "gm.mmcss", new[]{ "MMCSS 多媒体调度优先", "MMCSS multimedia scheduling priority", "MMCSS マルチメディア優先" } },
            { "gm.pausedl", new[]{ "暂停后台下载（Windows 更新 / 传递优化）", "Pause background downloads (Windows Update / DO)", "背景ダウンロード停止（更新 / 配信の最適化）" } },
            { "gm.pausesvc", new[]{ "暂停索引 / 预取服务（机械盘收益明显）", "Pause indexing / prefetch services (helps HDDs most)", "インデックス / プリフェッチ停止（HDD で有効）" } },
            { "gm.hint", new[]{ "改动立即生效。极限功能默认关闭；冻结有独立看门狗，崩溃时自动恢复。", "Changes apply instantly. Extreme options default off; a watchdog restores frozen apps after a crash.", "変更は即時反映。極限機能は既定オフ、クラッシュ時は監視役が凍結を復元。" } },
            { "btn.done", new[]{ "完成", "Done", "完了" } },
            { "btn.gmcfg", new[]{ "高级策略配置", "Advanced policy", "詳細ポリシー設定" } },
            { "set.autostart", new[]{ "开机自启", "Start with Windows", "Windows 起動時に自動起動" } },
            { "set.autostart.n", new[]{ "走管理员权限的计划任务。", "Via an administrator scheduled task.", "管理者権限のタスクスケジューラ経由。" } },
            { "set.autohide", new[]{ "检测到游戏后自动收起窗口", "Auto-hide the window once a game starts", "ゲーム開始後にウィンドウを自動的に隠す" } },
            { "set.autohide.n", new[]{ "检测到游戏启动 10 秒后，把主窗口收回托盘。每局只收一次——之后你再打开它就不会又被收走，直到下一局开始。", "Ten seconds after a game is detected, the main window returns to the tray. Once per session only — if you open it again afterwards it stays open until the next game starts.", "ゲーム検出から 10 秒後にメインウィンドウをトレイに戻します。1 試合につき 1 回だけ——その後に開き直した場合は次の試合まで閉じられません。" } },
            { "set.hint", new[]{ "这里只保留持久系统设置和维护工具；游戏期间的调度行为统一放在「优化策略」。", "This page contains persistent system settings and maintenance only; in-game scheduling lives under Optimization.", "ここは永続システム設定と保守のみ。ゲーム中の調度は「最適化ポリシー」に集約。" } },
            { "set.lang", new[]{ "语言", "Language", "言語" } },
            { "sec.pergame", new[]{ "逐游戏", "PER-GAME", "ゲームごと" } },
            { "sec.system", new[]{ "系统", "SYSTEM", "システム" } },
            { "sec.maint", new[]{ "维护", "MAINTENANCE", "メンテナンス" } },
            { "btn.open", new[]{ "打开", "Open", "開く" } },
            { "btn.clean", new[]{ "清理", "Clean", "削除" } },
            { "log.sub", new[]{ "最近 200 行 · 自动刷新", "Last 200 lines · auto-refresh", "直近 200 行・自動更新" } },
            { "set.about", new[]{ "Aegis {0} · {1} · 本地配置与用户白名单", "Aegis {0} · {1} · local configuration and user whitelist", "Aegis {0} · {1} · ローカル設定とユーザー許可リスト" } },

            { "set.hags", new[]{ "开启 GPU 硬件调度 HAGS（需重启）", "Enable GPU Hardware Scheduling (needs reboot)", "GPU ハードウェアスケジューリング（要再起動）" } },
            { "set.hags.n", new[]{ "切换 Windows 的硬件 GPU 调度选项；效果取决于显卡驱动和游戏，部分帧生成功能可能要求开启。", "Toggles Windows hardware GPU scheduling. Results depend on the driver and game; some frame-generation features may require it.", "Windows のハードウェア GPU 調度を切り替えます 効果はドライバとゲーム次第で 一部のフレーム生成機能が必要とする場合があります" } },
            { "hags.reboot", new[]{ "已写入 HAGS 设置，重启电脑后生效。", "HAGS setting written — takes effect after a reboot.", "HAGS 設定を適用しました。再起動後に有効になります。" } },
            { "set.irqaffinity", new[]{ "GPU 中断亲和优化（需重启设备或电脑）", "GPU interrupt affinity tuning (needs a device or system restart)", "GPU 割り込みアフィニティ最適化（デバイスまたは再起動が必要）" } },
            { "set.irqaffinity.n", new[]{ "引导显卡中断靠近游戏所在的核心，减少跨核/跨缓存开销。多适配器或多处理器组系统可能只应用较轻的邻近策略。", "Steers GPU interrupt handling toward the cores your game runs on, reducing cross-core/cross-cache overhead. Multi-adapter or multi processor-group systems may only get the lighter proximity policy.", "GPU の割り込み処理をゲームが動作するコアに近づけ、コア/キャッシュをまたぐオーバーヘッドを減らします。複数アダプタや複数プロセッサグループ環境では軽量な近接ポリシーのみになる場合があります。" } },
            { "irqaffinity.reboot", new[]{ "已写入中断亲和设置，重启该设备或重启电脑后生效。", "Interrupt affinity setting written — takes effect after restarting the device or rebooting.", "割り込みアフィニティ設定を適用しました。デバイスの再起動または再起動後に有効になります。" } },
            { "set.netaffinity", new[]{ "游戏网络优先（需重启网卡或电脑）", "Game network priority (needs a NIC or system restart)", "ゲームネットワーク優先（NICまたはシステムの再起動が必要）" } },
            { "set.netaffinity.n", new[]{ "引导网卡中断靠近游戏所在的核心，并给游戏目录中已添加的可执行文件的流量打上 QoS 优先级标记，减少排队和抖动。", "Steers NIC interrupt handling toward your game's cores and tags traffic from executables already added to your game library with a QoS priority marking, reducing queueing and jitter.", "NIC の割り込み処理をゲームが動作するコアに近づけ、ゲームライブラリに追加済みの実行ファイルの通信に QoS 優先マーキングを付与し、キューイングとジッターを減らします。" } },
            { "netaffinity.reboot", new[]{ "网卡中断设置需要重启该网卡或重启电脑后生效；流量优先级标记会在新建立的网络连接上生效。", "The NIC interrupt setting takes effect after restarting the adapter or rebooting; the traffic priority marking applies to newly established connections.", "NIC の割り込み設定はアダプタの再起動または再起動後に有効になります。トラフィックの優先マーキングは新しく確立された接続に適用されます。" } },
            { "set.vbs", new[]{ "关闭 VBS + 停用 hypervisor（需重启）", "Disable VBS + stop the hypervisor (needs reboot)", "VBS 無効化 + hypervisor 停止（要再起動）" } },
            { "vbs.state.on", new[]{ "当前：VBS 正在运行 —— 关闭会降低系统安全性，性能影响需在本机单独测试", "Now: VBS is running — disabling it reduces system security and any performance effect must be measured on this machine.", "現在 VBS が動作中です 無効化は安全性を下げるため 性能差はこの PC で個別に測定してください" } },
            { "vbs.state.off", new[]{ "当前：VBS 未运行（本机已经没有这项开销）", "Now: VBS is not running (this overhead is already absent)", "現在：VBS は非稼働（このオーバーヘッドは既にありません）" } },
            { "vbs.state.pending", new[]{ "已设为关闭，重启电脑后生效", "Set to disabled — takes effect after you reboot", "無効に設定済み —— 再起動後に有効化されます" } },
            { "vbs.state.unknown", new[]{ "当前状态未知（无法查询 WMI）", "Current state unknown (WMI query unavailable)", "現在の状態は不明（WMI を照会できません）" } },
            { "vbs.warn", new[]{
                "关闭 VBS / 内存完整性，并停用 hypervisor。\r\n\r\n这会降低系统安全性，并让 WSL2 / Docker / Hyper-V 虚拟机 / Windows 沙盒无法使用。性能变化没有通用结论，Aegis 也没有真实游戏基准，请只在理解风险并准备自行对照测试时使用。\r\n\r\n需重启才生效，全机器生效，恢复后也需要再次重启。\r\n\r\n继续吗？",
                "Turn off VBS / Memory Integrity and stop the hypervisor.\r\n\r\nThis reduces system security and prevents WSL2 / Docker / Hyper-V VMs / Windows Sandbox from running. There is no universal performance result and Aegis has no real-game benchmark, so use it only if you understand the risk and will measure the result yourself.\r\n\r\nIt takes effect machine-wide after a reboot and recovery also requires another reboot.\r\n\r\nContinue?",
                "VBS とメモリ整合性を無効化し hypervisor を停止します。\r\n\r\nシステムの安全性が下がり WSL2 Docker Hyper-V VM Windows サンドボックスが使えなくなります。共通の性能結果はなく Aegis に実ゲームベンチマークもありません。リスクを理解し 自分で比較測定する場合だけ使用してください。\r\n\r\n再起動後に PC 全体へ反映され 復元後も再起動が必要です。\r\n\r\n続けますか？" } },
            { "vbs.needadmin", new[]{ "修改 VBS / hypervisor 需要管理员权限，请以管理员身份运行 Aegis。", "Changing VBS / the hypervisor requires administrator rights — run Aegis as administrator.", "VBS / hypervisor の変更には管理者権限が必要です。Aegis を管理者で実行してください。" } },
            { "vbs.done", new[]{ "已关闭 VBS 并停用 hypervisor。\r\n请重启电脑生效。重启后 WSL2 / Docker / Hyper-V / 沙盒将无法使用；要恢复请回到这里关掉此开关再重启。", "VBS disabled and hypervisor stopped.\r\nReboot to apply. After reboot, WSL2 / Docker / Hyper-V / Sandbox won't work — to undo, turn this switch back off here and reboot again.", "VBS を無効化し hypervisor を停止しました。\r\n再起動で有効になります。再起動後は WSL2 / Docker / Hyper-V / サンドボックスが使えません。戻すにはこのスイッチをオフにして再度再起動してください。" } },
            { "vbs.restored", new[]{ "已恢复 VBS 与 hypervisor（hypervisorlaunchtype → 原值）。\r\n请重启电脑生效，之后 WSL2 / Docker 等恢复可用。", "VBS and the hypervisor have been restored (hypervisorlaunchtype → original).\r\nReboot to apply; WSL2 / Docker etc. work again afterwards.", "VBS と hypervisor を復元しました（hypervisorlaunchtype → 元の値）。\r\n再起動で有効になり、その後 WSL2 / Docker などが再び使えます。" } },
            { "vbs.restorefail", new[]{ "还原未完全成功（bcdedit 可能失败），原状态快照已保留，可再试一次。详见日志。", "Restore did not fully succeed (bcdedit may have failed). The snapshot is kept — you can try again. See the log for details.", "復元が完全には成功しませんでした（bcdedit が失敗した可能性）。スナップショットは保持されています。もう一度お試しください。詳細はログを参照。" } },

            { "btn.shader", new[]{ "清理着色器缓存", "Clean shader caches", "シェーダーキャッシュ削除" } },
            { "set.shader.n", new[]{ "怀疑缓存损坏或不兼容时可尝试清理；随后会重新编译着色器，首次运行可能更卡。", "Try this only when cache corruption or incompatibility is suspected. Shaders will be rebuilt and the next run may stutter more.", "キャッシュ破損や非互換が疑われる場合だけ試してください 再コンパイルのため次回起動はカクつきが増える場合があります" } },
            { "shader.size", new[]{ "当前占用约 {0}（NVIDIA / AMD / Intel / DirectX）", "About {0} on disk (NVIDIA / AMD / Intel / DirectX)", "現在約 {0}（NVIDIA / AMD / Intel / DirectX）" } },
            { "shader.busy", new[]{ "正在清理…", "Cleaning…", "クリーンアップ中…" } },
            { "shader.confirm", new[]{
                "清空显卡着色器缓存（NVIDIA / AMD / Intel / DirectX）？\r\n\r\n当你怀疑驱动更新后存在损坏或不兼容缓存时可以把清理作为排查步骤，但 Aegis 无法判断卡顿原因，也不保证清理会改善性能。\r\n\r\n只删缓存文件并保留目录；清理前请退出游戏。之后游戏需要重新编译着色器，首次运行可能出现额外卡顿。\r\n\r\n继续吗？",
                "Clear the GPU shader caches (NVIDIA / AMD / Intel / DirectX)?\r\n\r\nThis can be a troubleshooting step when damaged or incompatible cache data is suspected after a driver update. Aegis cannot identify the cause of stutter and does not promise a performance improvement.\r\n\r\nOnly cache files are removed and folders remain. Close games first. Shaders must be recompiled afterwards, so the next run may stutter more.\r\n\r\nContinue?",
                "GPU シェーダーキャッシュ（NVIDIA / AMD / Intel / DirectX）を削除しますか？\r\n\r\nドライバ更新後に破損または非互換のキャッシュが疑われる場合の切り分け手段です Aegis はカクつきの原因を判定できず 性能改善も保証しません\r\n\r\nキャッシュファイルだけを削除し フォルダは残します ゲームを終了してから実行してください その後はシェーダー再コンパイルが必要なため 次回起動時に追加のカクつきが出る場合があります\r\n\r\n続行しますか？" } },
            { "shader.freed", new[]{ "已清理着色器缓存，释放 {0}。", "Shader caches cleaned — {0} freed.", "シェーダーキャッシュを削除し、{0} を解放しました。" } },
            { "shader.skip", new[]{ "{0} 个文件正被占用已跳过（关闭游戏后可再清一次）。", "{0} files were in use and skipped (close games and clean again).", "使用中のファイル {0} 件をスキップしました（ゲーム終了後に再実行を）。" } },
            { "shader.note", new[]{ "每个游戏下次启动都可能重新编译着色器，首次运行可能出现额外卡顿。", "Games may recompile shaders on the next launch, which can add first-run stutter.", "次回起動時にシェーダーを再コンパイルし 初回のカクつきが増える場合があります" } },

            { "tray.aclist", new[]{ "反作弊列表", "Anti-Cheat list", "アンチチート一覧" } },
            { "tray.reset", new[]{ "恢复默认配置", "Reset to defaults", "設定を既定に戻す" } },
            { "tray.resetask", new[]{ "把所有开关、反作弊选择和白名单恢复为默认？（游戏列表保留）", "Reset all toggles, anti-cheat selection, and the whitelist to defaults? (Your game list is kept.)", "すべてのスイッチ、アンチチート選択、ホワイトリストを既定に戻しますか？(ゲーム一覧は保持されます)" } },
            { "tm.gpu", new[]{ "高性能 GPU 偏好", "High-perf GPU preference", "高性能 GPU 設定" } },
            { "tm.dvr", new[]{ "关闭 Game DVR", "Disable Game DVR", "Game DVR を無効化" } },
            { "tm.fso", new[]{ "关闭全屏优化", "Disable Fullscreen Opt.", "全画面最適化を無効" } },
            { "tm.notif", new[]{ "游戏时免打扰", "Do-not-disturb in game", "ゲーム中は通知オフ" } },
            { "tm.trim", new[]{ "压制时清空后台内存", "Trim background memory", "背景メモリを解放" } },
            { "tm.plan", new[]{ "游戏时切换电源计划", "Switch power plan in game", "ゲーム中に電源プラン切替" } },
            { "tm.autostart", new[]{ "开机自启", "Start with Windows", "起動時に自動起動" } },

            { "about.desc", new[]{
                "管理游戏与无用户窗口后台资源边界的 Windows 工具。\r\n单文件 C# / WinForms · 无第三方依赖 · 为已记录改动提供恢复路径",
                "A Windows tool for managing the resource boundary between a game and background processes without user windows.\r\nSingle-file C# / WinForms · no third-party dependencies · recovery paths for recorded changes",
                "ゲームとユーザー画面を持たない背景プロセスの資源境界を管理する Windows ツール。\r\n単一ファイル C# / WinForms・外部依存なし・記録済み変更に復元経路を提供" } },
            { "about.author", new[]{ "作者", "Author", "作者" } },
            { "about.repo", new[]{ "开源仓库", "Repository", "リポジトリ" } },
            { "about.lic", new[]{ "开源协议", "License", "ライセンス" } },
            { "btn.checkupd", new[]{ "检查更新", "Check for updates", "更新を確認" } },
            { "btn.download", new[]{ "前往下载", "Open download page", "ダウンロード" } },
            { "upd.checking", new[]{ "正在检查更新…", "Checking for updates…", "更新を確認中…" } },
            { "upd.latest", new[]{ "已是最新版本（{0}）", "You are on the latest version ({0}).", "最新バージョンです（{0}）" } },
            { "upd.newver", new[]{ "发现新版本 {0}（当前 {1}），点击「前往下载」获取。", "New version {0} available (current {1}) — click \"Open download page\".", "新バージョン {0} が公開されています（現在 {1}）。「ダウンロード」からどうぞ。" } },
            { "upd.fail", new[]{ "检查更新失败：网络不可用或仓库暂未发布版本。", "Update check failed: network issue or no release published yet.", "更新確認に失敗：ネットワーク不通またはリリース未公開。" } },
            { "bal.update", new[]{ "发现新版本 {0}，请打开面板「关于」页查看。", "New version {0} available — see the About page for details.", "新バージョン {0} が利用可能です。「情報」ページをご確認ください。" } },

            { "dlg.pickproc", new[]{ "选择进程", "Select process", "プロセスを選択" } },
            { "btn.add", new[]{ "添加", "Add", "追加" } },
            { "btn.cancel", new[]{ "取消", "Cancel", "キャンセル" } },
            { "dlg.bgsvc", new[]{ "[后台服务]", "[background service]", "[バックグラウンド]" } },
            { "ofd.game", new[]{ "选择游戏 EXE 或 Windows 快捷方式", "Select a game EXE or Windows shortcut", "ゲーム EXE または Windows ショートカットを選択" } },
            { "ofd.white", new[]{ "选择要加入白名单的 exe", "Select an exe to whitelist", "ホワイトリストに追加する exe を選択" } },
            { "ofd.filter", new[]{ "游戏程序或快捷方式 (*.exe;*.lnk)|*.exe;*.lnk|程序 (*.exe)|*.exe|快捷方式 (*.lnk)|*.lnk", "Game programs or shortcuts (*.exe;*.lnk)|*.exe;*.lnk|Programs (*.exe)|*.exe|Shortcuts (*.lnk)|*.lnk", "ゲームまたはショートカット (*.exe;*.lnk)|*.exe;*.lnk|プログラム (*.exe)|*.exe|ショートカット (*.lnk)|*.lnk" } },
            { "pick.busy", new[]{ "正在统计资源占用…", "Measuring resource usage…", "リソース使用量を集計中…" } },
            { "pick.count", new[]{ "共 {0} 个进程 · 按占用从高到低", "{0} processes · sorted by usage", "{0} 件 · 使用量の多い順" } },
            { "msg.taskfail", new[]{ "计划任务操作失败（需要管理员权限运行 Aegis）", "Scheduled-task operation failed (run Aegis as administrator)", "タスク操作に失敗（管理者で Aegis を実行してください）" } },

            { "tray.open", new[]{ "打开面板", "Open panel", "パネルを開く" } },
            { "btn.panic", new[]{ "一键恢复已记录项", "Restore recorded changes", "記録済み変更を復元" } },
            { "tray.exit", new[]{ "退出", "Exit", "終了" } },
            { "tray.active", new[]{ "Aegis - 守护中（{0}）", "Aegis - guarding ({0})", "Aegis - 稼働中（{0}）" } },
            { "tray.idle", new[]{ "Aegis - 待命，未检测到游戏", "Aegis - standby, no game detected", "Aegis - 待機中、ゲーム未検出" } },
            { "tray.noelev", new[]{ "Aegis - 未提权！压制类功能无效", "Aegis - not elevated! suppression disabled", "Aegis - 権限なし！抑制機能は無効" } },
            { "bal.noelev", new[]{ "当前未以管理员运行，压制类功能不会生效。", "Not running as administrator; suppression features are inactive.", "管理者で実行していないため、抑制機能は動作しません。" } },
            { "panic.done", new[]{ "已恢复能够确认的压制 / 提优 / 电源 / 网络 / 通知记录，Power Throttling 已交还系统管理。\r\n若游戏仍在运行，几秒后会重新进入压制；想彻底停用请关闭游戏模式与反作弊压制开关。", "Restored the recorded suppression, boost, power, network, and notification state that could be verified; Power Throttling was returned to system management.\r\nIf a game is still running they re-engage within seconds — turn off Game Mode / Anti-Cheat taming to stop them entirely.", "確認できた抑制 / 提優 / 電源 / ネット / 通知の記録を復元し Power Throttling はシステム管理へ戻しました。\r\nゲームが動作中なら数秒後に再適用されます。完全に止めるにはゲームモードとアンチチート抑制をオフにしてください。" } },
            { "panic.timeout", new[]{ "恢复流程等待超时。未确认还原的进程快照仍会保留并继续重试；如需彻底停用，请关闭游戏模式与反作弊压制开关。", "Restore timed out. Snapshots for unconfirmed processes were retained for retry; turn off Game Mode and Anti-Cheat taming to stop policy entirely.", "復元処理がタイムアウトしました。未確認のスナップショットは再試行用に保持されています。完全に停止するにはゲームモードとアンチチート抑制をオフにしてください。" } },
            { "rep.done", new[]{ "{0} 本局 {1}，压制 {2} 个后台进程，期间它们合计只用了 {3} CPU", "{0}: {1} played · {2} background processes throttled, together they used only {3} of CPU", "{0}：{1} プレイ・{2} 個を抑制、合計 CPU 使用は {3} のみ" } },
            { "rep.top", new[]{ "，占用最高 {0}（{1}）", "; top consumer: {0} ({1})", "、最多は {0}（{1}）" } },
            { "rep.freeze", new[]{ "，冻结 {0} 个持续高干扰后台", "; froze {0} sustained high-impact apps", "、高負荷背景 {0} 件を凍結" } },

            { "lol.act.waitclient", new[]{ "等待英雄联盟客户端", "Waiting for the League client", "League クライアントを待機中" } },
            { "lol.act.waitinstall", new[]{ "等待英雄联盟安装目录", "Waiting for a League installation", "League のインストール先を待機中" } },
            { "lol.act.disabled", new[]{ "英雄联盟专栏已停用", "League column is disabled", "League 専用機能は停止中" } },
            { "lol.act.cleaned", new[]{ "已净化 {0} 个专栏附加进程", "Closed {0} optional League processes", "付加プロセス {0} 個を終了しました" } },
            { "lol.act.cleanidle", new[]{ "专栏运行环境已净化", "The League runtime is already clean", "League の実行環境はクリーンです" } },
            { "lol.act.recovering", new[]{ "净化完成，正在使用 WeGame 恢复登录链", "Cleanup finished; restoring the sign-in chain through WeGame", "クリーンアップ後、WeGame でログイン経路を復旧中" } },
            { "lol.act.headless", new[]{ "对局真无头已启用", "In-game headless mode is active", "対局中の完全ヘッドレスが有効です" } },
            { "lol.act.restored", new[]{ "英雄联盟大厅界面已恢复", "The League lobby has been restored", "League のロビー画面を復帰しました" } },
            { "lol.act.wegamestarted", new[]{ "WeGame 已启动", "WeGame has been started", "WeGame を起動しました" } },
            { "lol.act.wegamestarting", new[]{ "正在等待 WeGame 就绪…", "Waiting for WeGame to come up…", "WeGame の起動を待機中…" } },
            { "lol.act.wegamerunning", new[]{ "WeGame 已在运行，无需重复启动", "WeGame is already running; no need to launch it again", "WeGame は既に実行中です。再起動は不要です" } },
            { "lol.err.wegamenostart", new[]{ "WeGame 未能在预期时间内启动", "WeGame did not come up within the expected time", "WeGame が既定時間内に起動しませんでした" } },
            { "lol.btn.wegamerunning", new[]{ "WeGame 运行中", "WeGame is running", "WeGame 実行中" } },
            { "lol.err.noinstall", new[]{ "未找到英雄联盟安装目录", "No League installation was found", "League のインストール先が見つかりません" } },
            { "lol.err.notready", new[]{ "英雄联盟登录会话尚未就绪", "The League sign-in session is not ready yet", "League のログインセッションが未準備です" } },
            { "lol.err.nosession", new[]{ "无法取得本机英雄联盟恢复会话", "Could not obtain a local League recovery session", "ローカルの復旧セッションを取得できません" } },
            { "lol.err.sessionlost", new[]{ "净化后英雄联盟登录会话失去响应", "The League sign-in session stopped responding after cleanup", "クリーンアップ後にログインセッションが応答しません" } },
            { "lol.err.killux", new[]{ "英雄联盟大厅界面收起失败", "Could not close the League lobby interface", "ロビー画面を閉じられませんでした" } },
            { "lol.err.restore", new[]{ "英雄联盟大厅界面恢复失败", "Could not restore the League lobby interface", "ロビー画面の復帰に失敗しました" } },
            { "lol.err.restorepending", new[]{ "英雄联盟大厅界面恢复失败，独立恢复器将继续接管", "Lobby restore failed; the detached recovery guard takes over", "ロビー復帰に失敗、独立復旧ガードが引き継ぎます" } },
            { "lol.err.cycle", new[]{ "英雄联盟运行时监控发生异常", "The League runtime monitor hit an error", "League ランタイム監視でエラーが発生しました" } },
            { "lol.err.nowegame", new[]{ "未找到 WeGame", "WeGame was not found", "WeGame が見つかりません" } },
            { "lol.err.wegamestart", new[]{ "WeGame 启动失败", "WeGame failed to start", "WeGame の起動に失敗しました" } },

            { "lolq.err.noinput", new[]{ "未提供英雄联盟目录", "No League directory was provided", "League のディレクトリが指定されていません" } },
            { "lolq.err.badformat", new[]{ "英雄联盟目录格式无效", "The League directory path is malformed", "League のパス形式が無効です" } },
            { "lolq.err.notroot", new[]{ "目录不是有效的国服英雄联盟安装根目录", "Not a valid League of Legends (CN) installation root", "有効な League of Legends（中国版）のルートではありません" } },
            { "lolq.err.enumproc", new[]{ "无法枚举系统进程", "Could not enumerate system processes", "システムプロセスを列挙できません" } },
            { "lolq.proc.unknown", new[]{ "未知进程", "unknown process", "不明なプロセス" } },
            { "lolq.err.createset", new[]{ "无法创建隔离批次：{0}", "Could not create the quarantine batch: {0}", "隔離バッチを作成できません：{0}" } },
            { "lolq.err.writemanifest", new[]{ "无法写入隔离清单，未移动任何目录", "Could not write the manifest; nothing was moved", "記録を書き込めないため、何も移動していません" } },
            { "lolq.err.clientrunning", new[]{ "检测到运行中的客户端：{0}", "Running client detected: {0}", "実行中のクライアントを検出：{0}" } },
            { "lolq.item.notdir", new[]{ "隔离项不是目录，未处理", "The item is not a directory; skipped", "対象がディレクトリではないためスキップ" } },
            { "lolq.item.vanished", new[]{ "源目录在执行前发生变化", "The source directory changed before the move", "移動前に元ディレクトリが変化しました" } },
            { "lolq.item.destexists", new[]{ "隔离目标已存在，未覆盖", "The quarantine target already exists; not overwritten", "隔離先が既に存在するため上書きしません" } },
            { "lolq.err.srcreparse", new[]{ "隔离项路径包含重解析点", "The source path contains a reparse point", "対象パスに再解析ポイントが含まれます" } },
            { "lolq.item.quarantined", new[]{ "已隔离", "Quarantined", "隔離しました" } },
            { "lolq.item.quarantinefail", new[]{ "隔离失败：{0}", "Quarantine failed: {0}", "隔離に失敗：{0}" } },
            { "lolq.msg.qdone", new[]{ "已完成英雄联盟附加层隔离", "The optional League layer has been quarantined", "League の付加層を隔離しました" } },
            { "lolq.msg.qpartial", new[]{ "隔离只完成了一部分，可使用恢复功能安全回滚", "Quarantine partially completed; restore can roll it back safely", "隔離は一部のみ完了。復元で安全に戻せます" } },
            { "lolq.msg.qnone", new[]{ "未移动任何目录", "No directory was moved", "移動したディレクトリはありません" } },
            { "lolq.err.nosuchset", new[]{ "指定的隔离批次不存在或已经恢复", "That quarantine batch does not exist or was already restored", "指定の隔離バッチが存在しないか復元済みです" } },
            { "lolq.err.setreparse", new[]{ "隔离批次路径包含重解析点", "The batch path contains a reparse point", "バッチのパスに再解析ポイントが含まれます" } },
            { "lolq.err.setinvalidex", new[]{ "隔离批次路径无效：{0}", "The batch path is invalid: {0}", "バッチのパスが無効です：{0}" } },
            { "lolq.err.setinvalid", new[]{ "隔离批次路径无效", "The batch path is invalid", "バッチのパスが無効です" } },
            { "lolq.err.manifestunavailable", new[]{ "隔离清单不可用：{0}", "The manifest is unavailable: {0}", "記録を利用できません：{0}" } },
            { "lolq.err.manifestmismatch", new[]{ "隔离清单与当前英雄联盟目录不匹配", "The manifest does not match the current League directory", "記録が現在の League ディレクトリと一致しません" } },
            { "lolq.item.alreadyinplace", new[]{ "该项已在原位置", "Already in its original location", "既に元の位置にあります" } },
            { "lolq.item.payloadmissing", new[]{ "隔离内容缺失，清单保持未恢复状态", "The payload is missing; the manifest stays unrestored", "隔離内容が欠落。記録は未復元のままです" } },
            { "lolq.item.occupied", new[]{ "原位置已有内容，未覆盖", "The original location is occupied; not overwritten", "元の位置に内容があるため上書きしません" } },
            { "lolq.err.payloadreparse", new[]{ "隔离内容路径包含重解析点", "The payload path contains a reparse point", "隔離内容のパスに再解析ポイントが含まれます" } },
            { "lolq.err.parentisfile", new[]{ "原位置的父路径是文件", "The parent of the original location is a file", "元の位置の親パスがファイルです" } },
            { "lolq.item.restored", new[]{ "已恢复", "Restored", "復元しました" } },
            { "lolq.item.restorefail", new[]{ "恢复失败：{0}", "Restore failed: {0}", "復元に失敗：{0}" } },
            { "lolq.msg.rstatefail", new[]{ "目录已恢复，但隔离清单状态写入失败", "Directories restored, but the manifest state could not be written", "復元は完了しましたが記録の状態を書き込めません" } },
            { "lolq.msg.rmissing", new[]{ "检测到隔离内容缺失，清单保持未恢复状态", "Missing payload detected; the manifest stays unrestored", "隔離内容の欠落を検出。記録は未復元のままです" } },
            { "lolq.msg.rdone", new[]{ "已恢复英雄联盟附加层", "The optional League layer has been restored", "League の付加層を復元しました" } },
            { "lolq.msg.rpartial", new[]{ "只恢复了一部分，冲突内容均保持原样", "Restored only partially; conflicting content was left untouched", "一部のみ復元。競合する内容はそのままです" } },
            { "lolq.msg.rnone", new[]{ "未恢复任何目录，冲突内容均保持原样", "Nothing was restored; conflicting content was left untouched", "何も復元されず、競合する内容はそのままです" } },
            { "lolq.err.stillunique", new[]{ "该批次仍有只存在于隔离仓的内容，请先恢复", "This batch still holds content that exists only in quarantine; restore it first", "隔離領域にのみ存在する内容が残っています。先に復元してください" } },
            { "lolq.msg.discardpartial", new[]{ "隔离批次未能完全删除，请关闭占用项后重试", "The batch could not be fully removed; close anything using it and retry", "バッチを完全に削除できません。使用中の項目を閉じて再試行してください" } },
            { "lolq.msg.discarddone", new[]{ "已丢弃隔离批次记录，原位置内容保持不变", "The quarantine record was discarded; the original location is unchanged", "隔離記録を破棄しました。元の位置の内容は変わりません" } },
            { "lolq.err.nodiscard", new[]{ "没有检测到可丢弃的隔离批次", "No discardable quarantine batch was found", "破棄できる隔離バッチがありません" } },
            { "lolq.err.nosetname", new[]{ "未指定需要丢弃的隔离批次", "No quarantine batch was specified", "破棄するバッチが指定されていません" } },
            { "lolq.err.closefirst", new[]{ "请先关闭英雄联盟与 WeGame：{0}", "Close League and WeGame first: {0}", "先に League と WeGame を終了してください：{0}" } },
            { "lolq.err.hasactive", new[]{ "已有未恢复的隔离批次", "An unrestored quarantine batch already exists", "未復元の隔離バッチが既に存在します" } },
            { "lolq.err.nocandidate", new[]{ "没有检测到可隔离的附加层目录", "No optional layer directory was detected", "隔離可能な付加層が検出されません" } },
            { "lolq.err.norestore", new[]{ "没有检测到未恢复的隔离批次", "No unrestored quarantine batch was detected", "未復元の隔離バッチが検出されません" } },
            { "lolq.err.multiset", new[]{ "检测到多个隔离批次，请指定需要恢复的批次", "Multiple batches detected; specify which one to restore", "複数のバッチを検出。復元するバッチを指定してください" } },
            { "lolq.err.generic", new[]{ "操作失败", "The operation failed", "操作に失敗しました" } },
            { "lolq.err.candnotdir", new[]{ "候选路径不是目录", "The candidate path is not a directory", "候補パスがディレクトリではありません" } },
            { "lolq.err.candreparse", new[]{ "候选目录是重解析点", "The candidate directory is a reparse point", "候補ディレクトリが再解析ポイントです" } },
            { "lolq.err.scanfail", new[]{ "无法完整扫描：{0}", "Could not scan completely: {0}", "完全にスキャンできません：{0}" } },
            { "lolq.err.filereparse", new[]{ "目录包含文件重解析点：{0}", "The directory contains a file reparse point: {0}", "ファイルの再解析ポイントを含みます：{0}" } },
            { "lolq.err.readfile", new[]{ "无法读取文件信息：{0}", "Could not read file information: {0}", "ファイル情報を読み取れません：{0}" } },
            { "lolq.err.dirreparse", new[]{ "目录包含子目录重解析点：{0}", "The directory contains a subdirectory reparse point: {0}", "サブディレクトリの再解析ポイントを含みます：{0}" } },
            { "lolq.err.readdir", new[]{ "无法读取目录信息：{0}", "Could not read directory information: {0}", "ディレクトリ情報を読み取れません：{0}" } },
            { "lolq.err.warehousefile", new[]{ "隔离仓路径被同名文件占用", "A file occupies the quarantine store path", "隔離領域のパスが同名ファイルに占有されています" } },
            { "lolq.err.warehousereparse", new[]{ "隔离仓不能是重解析点", "The quarantine store must not be a reparse point", "隔離領域は再解析ポイントであってはなりません" } },
            { "lolq.err.warehouselocked", new[]{ "隔离仓正在使用或不可写：{0}", "The quarantine store is in use or not writable: {0}", "隔離領域が使用中か書き込めません：{0}" } },
            { "lolq.err.readwarehouse", new[]{ "无法读取隔离仓：{0}", "Could not read the quarantine store: {0}", "隔離領域を読み取れません：{0}" } },
            { "lolq.err.enumsets", new[]{ "无法枚举隔离批次：{0}", "Could not enumerate quarantine batches: {0}", "隔離バッチを列挙できません：{0}" } },
            { "lolq.err.setisreparse", new[]{ "隔离批次是重解析点：{0}", "The batch is a reparse point: {0}", "バッチが再解析ポイントです：{0}" } },
            { "lolq.err.setbadmanifest", new[]{ "{0} 清单无效：{1}", "{0} has an invalid manifest: {1}", "{0} の記録が無効です：{1}" } },
            { "lolq.err.setrootmismatch", new[]{ "{0} 清单根目录不匹配", "{0} has a mismatched manifest root", "{0} の記録のルートが一致しません" } },
            { "lolq.err.setstatemismatch", new[]{ "{0} 的物理内容与清单状态不一致", "{0} has content inconsistent with its manifest state", "{0} の実内容が記録の状態と一致しません" } },
            { "lolq.err.setmissing", new[]{ "{0} 有 {1} 项在隔离仓和原位置均缺失", "{0} has {1} item(s) missing from both quarantine and the original location", "{0} は {1} 項目が隔離領域と元の位置の双方で欠落しています" } },
            { "lolq.err.setreadfail", new[]{ "{0} 读取失败：{1}", "{0} could not be read: {1}", "{0} の読み取りに失敗：{1}" } },
            { "lolq.err.manifestlong", new[]{ "清单超出安全长度", "The manifest exceeds the safe length", "記録が安全な長さを超えています" } },
            { "lolq.err.manifestmissing", new[]{ "清单不存在", "The manifest does not exist", "記録が存在しません" } },
            { "lolq.err.manifestformat", new[]{ "清单格式不受支持", "Unsupported manifest format", "記録の形式が未対応です" } },
            { "lolq.err.rootencoding", new[]{ "根目录编码无效", "The root path encoding is invalid", "ルートパスのエンコードが無効です" } },
            { "lolq.err.versionencoding", new[]{ "版本编码无效", "The version encoding is invalid", "バージョンのエンコードが無効です" } },
            { "lolq.err.timefield", new[]{ "时间字段无效", "The timestamp field is invalid", "時刻フィールドが無効です" } },
            { "lolq.err.unknownfield", new[]{ "清单包含未知字段", "The manifest contains an unknown field", "記録に未知のフィールドがあります" } },
            { "lolq.err.baditem", new[]{ "清单候选项无效", "A manifest item is invalid", "記録の項目が無効です" } },
            { "lolq.err.badstate", new[]{ "清单状态无效", "The manifest state is invalid", "記録の状態が無効です" } },
            { "lolq.err.missingfield", new[]{ "清单缺少必要字段", "The manifest is missing a required field", "記録に必須フィールドがありません" } },
            { "lolq.err.outsideroot", new[]{ "路径超出英雄联盟目录", "The path escapes the League directory", "パスが League ディレクトリの外です" } },
            { "lolq.err.outsiderootr", new[]{ "恢复路径超出英雄联盟目录", "The restore path escapes the League directory", "復元パスが League ディレクトリの外です" } },
            { "lolq.err.pathreparse", new[]{ "恢复路径包含重解析点", "The restore path contains a reparse point", "復元パスに再解析ポイントが含まれます" } },
            { "lolq.err.pathinvalid", new[]{ "恢复路径无效", "The restore path is invalid", "復元パスが無効です" } },
            { "lolq.err.crossvolume", new[]{ "隔离目录不在同一卷", "The quarantine directory is on another volume", "隔離先が同一ボリュームにありません" } },

            { "ac.ace.n", new[]{ "ACE 反作弊专家 (腾讯)", "ACE Anti-Cheat (Tencent)", "ACE アンチチート (Tencent)" } },
            { "ac.ace.d", new[]{ "英雄联盟国服 / 无畏契约国服 / 三角洲行动 / CF 等", "LoL & Valorant (CN) / Delta Force / CrossFire etc.", "LoL・Valorant(中国) / Delta Force / CF など" } },
            { "ac.tp.n", new[]{ "TenProtect / TP (腾讯)", "TenProtect / TP (Tencent)", "TenProtect / TP (Tencent)" } },
            { "ac.tp.d", new[]{ "ACE 前身，穿越火线等老游戏仍在用", "Predecessor of ACE, still used by CrossFire etc.", "ACE の前身、CrossFire などで現役" } },
            { "ac.vanguard.n", new[]{ "Vanguard (Riot)", "Vanguard (Riot)", "Vanguard (Riot)" } },
            { "ac.vanguard.d", new[]{ "无畏契约 / 英雄联盟 · vgk 为内核驱动无法压制", "Valorant / LoL · vgk is a kernel driver (can't throttle)", "Valorant / LoL・vgk はカーネルドライバで不可" } },
            { "ac.eac.n", new[]{ "EasyAntiCheat (Epic)", "EasyAntiCheat (Epic)", "EasyAntiCheat (Epic)" } },
            { "ac.eac.d", new[]{ "俗称「小蓝熊」· Apex / 堡垒之夜 / 永劫无间 / 幻兽帕鲁 等", "Apex / Fortnite / Naraka / Palworld etc.", "Apex / Fortnite / Naraka / パルワールド など" } },
            { "ac.battleye.n", new[]{ "BattlEye", "BattlEye", "BattlEye" } },
            { "ac.battleye.d", new[]{ "PUBG / 彩虹六号 / DayZ / 逃离塔科夫 · BEDaisy 为驱动", "PUBG / Rainbow Six / DayZ / Tarkov · BEDaisy is a driver", "PUBG / R6 / DayZ / タルコフ・BEDaisy はドライバ" } },
            { "ac.eaac.n", new[]{ "EA Javelin (EA 反作弊)", "EA Javelin (EA AntiCheat)", "EA Javelin (EA アンチチート)" } },
            { "ac.eaac.d", new[]{ "战地 2042 / 战地 6 / FC 等 EA 游戏 · 另有内核驱动", "Battlefield 2042/6 / FC etc. · also has a kernel driver", "Battlefield 2042/6 / FC など・カーネルドライバもあり" } },
            { "ac.gameguard.n", new[]{ "nProtect GameGuard", "nProtect GameGuard", "nProtect GameGuard" } },
            { "ac.gameguard.d", new[]{ "DNF 等部分韩系网游", "DNF and some Korean MMOs", "DNF など一部の韓国系オンラインゲーム" } },
            { "ac.faceit.n", new[]{ "FACEIT 反作弊", "FACEIT AC", "FACEIT アンチチート" } },
            { "ac.faceit.d", new[]{ "CS2 第三方竞技平台", "CS2 third-party platform", "CS2 サードパーティ対戦プラットフォーム" } },
            { "ac.neac.n", new[]{ "NEAC 反作弊 (网易)", "NEAC (NetEase)", "NEAC (NetEase)" } },
            { "ac.neac.d", new[]{ "部分网易游戏 · 另有内核组件", "some NetEase games · also has kernel parts", "一部の NetEase ゲーム・カーネル部品もあり" } },
        };

        public static void Init()
        {
            string v = Settings.LoadStr("Lang", "");
            if (v == "en") Cur = 1;
            else if (v == "ja") Cur = 2;
            else if (v == "zh") Cur = 0;
            else
            {
                string n = System.Globalization.CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;
                Cur = n == "ja" ? 2 : (n == "zh" ? 0 : 1);
            }
        }

        public static void Set(int i)
        {
            Cur = i < 0 ? 0 : (i > 2 ? 2 : i);
            Settings.SaveStr("Lang", Cur == 1 ? "en" : (Cur == 2 ? "ja" : "zh"));
        }

        internal static List<string> AllKeys()
        {
            var keys = new List<string>();
            foreach (var kv in M) keys.Add(kv.Key);
            return keys;
        }

        internal static string[] Row(string key)
        {
            string[] a;
            return M.TryGetValue(key, out a) ? a : null;
        }

        public static string T(string key)
        {
            string[] a;
            if (M.TryGetValue(key, out a)) return a[Cur < a.Length ? Cur : 0];
            return key;
        }

        public static string F(string key, params object[] args) { return string.Format(T(key), args); }
    }


}
